<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <AssemblyName>M1.Ax.Erp</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <UseWindowsForms>True</UseWindowsForms>
    <TargetFramework>net48</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>15.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="M1.Core">
      <HintPath>..\..\..\M1\Tools\Assemblies\M1.Core.dll</HintPath>
    </Reference>
    <Reference Include="System.Data" />
    <Reference Include="System.Xml" />
    <Reference Include="M1Classes92">
      <HintPath>..\..\..\M1\Tools\Assemblies\M1Classes92.dll</HintPath>
    </Reference>
    <Reference Include="Avalara.AvaTax.Adapter">
      <HintPath>..\..\..\M1\Tools\Assemblies\Avalara.AvaTax.Adapter.dll</HintPath>
    </Reference>
    <Reference Include="M1.Forms.Controls">
      <HintPath>..\..\..\M1\Tools\Assemblies\M1.Forms.Controls.dll</HintPath>
    </Reference>
    <Reference Include="M1.ServiceCore">
      <HintPath>..\..\..\M1\Tools\Assemblies\M1.ServiceCore.dll</HintPath>
    </Reference>
    <Reference Include="M1.Extensions">
      <HintPath>..\..\..\M1\Tools\Assemblies\M1.Extensions.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.Exchange.WebServices">
      <HintPath>..\..\..\M1\Tools\Assemblies\Microsoft.Exchange.WebServices.dll</HintPath>
    </Reference>
    <Reference Include="M1.Script.Interfaces">
      <HintPath>..\..\..\M1\Tools\Assemblies\M1.Script.Interfaces.dll</HintPath>
    </Reference>
    <Reference Include="M1.WebCore">
      <HintPath>..\..\..\M1\Tools\Assemblies\M1.WebCore.dll</HintPath>
    </Reference>
    <Reference Include="System.Core" />
    <Reference Include="System.Net.Http" />
    <Reference Include="System.Data.DataSetExtensions" />
    <Reference Include="M1.ShippingServices">
      <HintPath>..\..\..\M1\Tools\Assemblies\M1.ShippingServices.dll</HintPath>
    </Reference>
    <Reference Include="ADODB" />
    <Reference Include="System.ComponentModel.DataAnnotations" />
    <Reference Include="System.Web" />
  </ItemGroup>
</Project>