<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <AssemblyName>M1.Core</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <UseWindowsForms>True</UseWindowsForms>
    <TargetFramework>net48</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>15.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup>
    <RootNamespace />
  </PropertyGroup>
  <ItemGroup>
    <None Remove="M1.Core.M1BindingSource.png" />
    <EmbeddedResource Include="M1.Core.M1BindingSource.png" LogicalName="M1.Core.M1BindingSource.png" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="System.Data" />
    <Reference Include="System.DirectoryServices.AccountManagement" />
    <Reference Include="SimpleImpersonation">
      <HintPath>..\..\..\M1\Tools\Assemblies\SimpleImpersonation.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.Exchange.WebServices">
      <HintPath>..\..\..\M1\Tools\Assemblies\Microsoft.Exchange.WebServices.dll</HintPath>
    </Reference>
    <Reference Include="M1.Extensions">
      <HintPath>..\..\..\M1\Tools\Assemblies\M1.Extensions.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.SqlServer.TransactSql.ScriptDom">
      <HintPath>..\..\..\M1\Tools\Assemblies\Microsoft.SqlServer.TransactSql.ScriptDom.dll</HintPath>
    </Reference>
    <Reference Include="Interop.ADODB">
      <HintPath>..\..\..\M1\Tools\Assemblies\Interop.ADODB.dll</HintPath>
    </Reference>
    <Reference Include="System.Core" />
    <Reference Include="System.Xml" />
    <Reference Include="System.Management" />
    <Reference Include="M1.Script.Interfaces">
      <HintPath>..\..\..\M1\Tools\Assemblies\M1.Script.Interfaces.dll</HintPath>
    </Reference>
    <Reference Include="Infragistics.Win.UltraWinGrid">
      <HintPath>..\..\..\M1\Tools\Assemblies\Infragistics.Win.UltraWinGrid.dll</HintPath>
    </Reference>
    <Reference Include="Infragistics.Win.UltraWinGrid.ExcelExport">
      <HintPath>..\..\..\M1\Tools\Assemblies\Infragistics.Win.UltraWinGrid.ExcelExport.dll</HintPath>
    </Reference>
    <Reference Include="Infragistics.Win.UltraWinGrid.DocumentExport">
      <HintPath>..\..\..\M1\Tools\Assemblies\Infragistics.Win.UltraWinGrid.DocumentExport.dll</HintPath>
    </Reference>
    <Reference Include="Infragistics.Win">
      <HintPath>..\..\..\M1\Tools\Assemblies\Infragistics.Win.dll</HintPath>
    </Reference>
    <Reference Include="Infragistics.Documents.Reports">
      <HintPath>..\..\..\M1\Tools\Assemblies\Infragistics.Documents.Reports.dll</HintPath>
    </Reference>
    <Reference Include="Interop.MSScriptControl">
      <HintPath>..\..\..\M1\Tools\Assemblies\Interop.MSScriptControl.dll</HintPath>
    </Reference>
    <Reference Include="CrystalDecisions.CrystalReports.Engine" />
    <Reference Include="CrystalDecisions.Shared" />
    <Reference Include="Microsoft.Identity.Client">
      <HintPath>..\..\..\M1\Tools\Assemblies\Microsoft.Identity.Client.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.Graph">
      <HintPath>..\..\..\M1\Tools\Assemblies\Microsoft.Graph.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.Graph.Core">
      <HintPath>..\..\..\M1\Tools\Assemblies\Microsoft.Graph.Core.dll</HintPath>
    </Reference>
    <Reference Include="System.Net.Http" />
    <Reference Include="Mail">
      <HintPath>..\..\..\M1\Tools\Assemblies\Mail.dll</HintPath>
    </Reference>
    <Reference Include="Newtonsoft.Json">
      <HintPath>..\..\..\M1\Tools\Assemblies\Newtonsoft.Json.dll</HintPath>
    </Reference>
    <Reference Include="System.DirectoryServices" />
    <Reference Include="M1.Cipher">
      <HintPath>..\..\..\M1\Tools\Assemblies\M1.Cipher.dll</HintPath>
    </Reference>
    <Reference Include="System.Data.DataSetExtensions" />
    <Reference Include="M1.Images">
      <HintPath>..\..\..\M1\Tools\Assemblies\M1.Images.dll</HintPath>
    </Reference>
    <Reference Include="System.Data.Linq" />
    <Reference Include="Infragistics.Shared">
      <HintPath>..\..\..\M1\Tools\Assemblies\Infragistics.Shared.dll</HintPath>
    </Reference>
    <Reference Include="Infragistics.Documents.Excel">
      <HintPath>..\..\..\M1\Tools\Assemblies\Infragistics.Documents.Excel.dll</HintPath>
    </Reference>
    <Reference Include="CrystalDecisions.ReportAppServer.DataSetConversion" />
    <Reference Include="Microsoft.CSharp" />
    <Reference Include="System.Web" />
  </ItemGroup>
</Project>