using M1.Core;

namespace M1.Ax.Erp.DD.DDConversions;

[DDConversion("9.2.076", "", "")]
public class v92076
{
	public v92076(DDConversionParms parms)
	{
		parms.DmoDD.ExecuteCommand(parms.DatabaseName, "DELETE FROM DDGridDetails WHERE dgGridID IN ('M1UNPOSTEDDMRSHIPMENTS','M1UNPOSTEDINSPECTIONS','M1UNPOSTEDMATISSUES','M1UNPOSTEDMFGRECEIPTS','M1UNPOSTEDRECEIPTS','M1UNPOSTEDRMARECEIPTS','M1UNPOSTEDSHIPMENTS','M1UNPOSTEDWHRECEIPTS','M1UNPOSTEDWHTRANSFERS') and dgUserID <> ''");
	}
}
