<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>M1.Ax.Core.DD</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net48</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>15.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup>
    <RootNamespace />
  </PropertyGroup>
  <ItemGroup>
    <None Remove="M1.Ax.Core.DD.DDFields.xml" />
    <None Remove="M1.Ax.Core.DD.DDGridDetails.xml" />
    <None Remove="M1.Ax.Core.DD.DDGrids.xml" />
    <None Remove="M1.Ax.Core.DD.DDTables.xml" />
    <None Remove="M1.Ax.Core.DD.DDForms.xml" />
    <None Remove="M1.Ax.Core.DD.DDObjectDetails.xml" />
    <None Remove="M1.Ax.Core.DD.DDObjects.xml" />
    <None Remove="M1.Ax.Core.DD.DDOpenWiths.xml" />
    <None Remove="M1.Ax.Core.DD.DDRelations.xml" />
    <EmbeddedResource Include="M1.Ax.Core.DD.DDFields.xml" LogicalName="M1.Ax.Core.DD.DDFields.xml" />
    <EmbeddedResource Include="M1.Ax.Core.DD.DDGridDetails.xml" LogicalName="M1.Ax.Core.DD.DDGridDetails.xml" />
    <EmbeddedResource Include="M1.Ax.Core.DD.DDGrids.xml" LogicalName="M1.Ax.Core.DD.DDGrids.xml" />
    <EmbeddedResource Include="M1.Ax.Core.DD.DDTables.xml" LogicalName="M1.Ax.Core.DD.DDTables.xml" />
    <EmbeddedResource Include="M1.Ax.Core.DD.DDForms.xml" LogicalName="M1.Ax.Core.DD.DDForms.xml" />
    <EmbeddedResource Include="M1.Ax.Core.DD.DDObjectDetails.xml" LogicalName="M1.Ax.Core.DD.DDObjectDetails.xml" />
    <EmbeddedResource Include="M1.Ax.Core.DD.DDObjects.xml" LogicalName="M1.Ax.Core.DD.DDObjects.xml" />
    <EmbeddedResource Include="M1.Ax.Core.DD.DDOpenWiths.xml" LogicalName="M1.Ax.Core.DD.DDOpenWiths.xml" />
    <EmbeddedResource Include="M1.Ax.Core.DD.DDRelations.xml" LogicalName="M1.Ax.Core.DD.DDRelations.xml" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="M1.Core">
      <HintPath>..\..\..\M1\Tools\Assemblies\M1.Core.dll</HintPath>
    </Reference>
    <Reference Include="System.Data" />
  </ItemGroup>
</Project>