using System.Diagnostics;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Runtime.Versioning;
using M1.Core;

[assembly: DDTableVersion("DDCode", "9.7.200")]
[assembly: DDTableVersion("DDCustomModules", "9.7.400")]
[assembly: DDTableVersion("DDFields", "9.7.500")]
[assembly: DDTableVersion("DDFieldExtensions", "9.2.827")]
[assembly: DDTableVersion("DDFieldExtensionTypes", "9.2.096")]
[assembly: DDTableVersion("DDFieldGroups", "9.2.053")]
[assembly: DDTableVersion("DDExplorer", "9.7.400")]
[assembly: DDTableVersion("DDForms", "9.6.100")]
[assembly: DDTableVersion("DDFormDetails", "9.6.100")]
[assembly: DDTableVersion("DDGrids", "9.7.400")]
[assembly: DDTableVersion("DDGridDetails", "9.7.400")]
[assembly: DDTableVersion("DDModules", "9.2.587")]
[assembly: DDTableVersion("DDObjects", "9.6.100")]
[assembly: DDTableVersion("DDObjectDetails", "9.4.200")]
[assembly: DDTableVersion("DDOpenWiths", "9.7.100")]
[assembly: DDTableVersion("DDRelations", "9.6.100")]
[assembly: DDTableVersion("DDSeries", "9.6.100")]
[assembly: DDTableVersion("DDSolutionDetails", "3.50.000")]
[assembly: DDTableVersion("DDSolutions", "3.50.000")]
[assembly: DDTableVersion("DDTables", "9.7.500")]
[assembly: DDTableVersion("DDUsers", "9.6.200")]
[assembly: DDTableVersion("DDVisualizers", "9.6.100")]
[assembly: DDTableVersion("WebBarcodes", "9.00.010")]
[assembly: DDTableVersion("WebControls", "9.00.010")]
[assembly: DDTableVersion("WebLists", "9.00.010")]
[assembly: DDTableVersion("WebScreens", "9.00.010")]
[assembly: DDTableVersion("WebOptions", "9.00.010")]
[assembly: DDTableVersion("WebServerFunctions", "9.00.010")]
[assembly: DDTableVersion("WebSessions", "8.00.240")]
[assembly: AssemblyTitle("M1.Ax.Erp.DD")]
[assembly: AssemblyDescription("")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("ECI Solutions")]
[assembly: AssemblyProduct("M1.Ax.Erp.DD")]
[assembly: AssemblyCopyright("Copyright © ECI Solutions 2021")]
[assembly: AssemblyTrademark("")]
[assembly: ComVisible(false)]
[assembly: Guid("25fc4041-bb81-4369-8e46-3acaa8cf4e60")]
[assembly: AssemblyFileVersion("9.7.500.0")]
[assembly: AssemblyVersion("9.7.500.0")]
