using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Text;
using System.Web.Http;
using M1.API.Filters;
using Microsoft.Win32;
using Swashbuckle.Application;

namespace M1.API;

public class SwaggerConfig
{
	private class AscendingAlphabeticComparer : IComparer<string>
	{
		public int Compare(string x, string y)
		{
			return x.CompareTo(y);
		}
	}

	private class DescendingAlphabeticComparer : IComparer<string>
	{
		public int Compare(string x, string y)
		{
			return y.CompareTo(x);
		}
	}

	public static void Register(HttpConfiguration config)
	{
		string devNotes = getDevNotes();
		config.EnableSwagger("swagger/docs/{apiVersion}", delegate(SwaggerDocsConfig c)
		{
			c.RootUrl((HttpRequestMessage req) => req.RequestUri.GetLeftPart(UriPartial.Authority) + req.GetRequestContext().VirtualPathRoot.TrimEnd('/'));
			c.Schemes(new string[2] { "http", "https" });
			c.SingleApiVersion("v1", "M1 API Documentation").Description("The API to integrate services with M1." + devNotes).Contact(delegate(ContactBuilder cc)
			{
				cc.Name("ECI Software Solutions - M1").Url("https://www.ecisolutions.com/manufacturers-and-job-shops/m1");
			});
			c.PrettyPrint();
			c.IncludeXmlComments(AppDomain.CurrentDomain.BaseDirectory + "\\M1.API.XML");
			c.DescribeAllEnumsAsStrings();
			c.OrderActionGroupsBy(new AscendingAlphabeticComparer());
			c.OperationFilter<HelpAuthorizationHeaderParameterOperationFilter>();
			c.DocumentFilter<SortOperationsByPathDocumentFilter>();
			c.DocumentFilter<CustomDocumentFilter>();
			c.ApiKey("apikey").Description("Provide API Key in the form 'apikey {ApiID}:{ApiKey}'").Name("Authorization")
				.In("header");
		});
	}

	private static string getDevNotes()
	{
		StringBuilder stringBuilder = new StringBuilder();
		stringBuilder.AppendLine();
		stringBuilder.AppendLine();
		stringBuilder.AppendLine("## Authentication Notes\n");
		stringBuilder.AppendLine();
		stringBuilder.AppendLine("There are 2 available Authentication Methods: **Hawk** and **ApiKey**.\n");
		stringBuilder.AppendLine("- All requests must include an Authorization header with either of the following Authorization headers:\n");
		stringBuilder.AppendLine("  - For **Hawk**, provide the amx access token in the format `amx {token}` where the token is generated by a pre-request script or using the M1 API Configuration Tool.\n");
		stringBuilder.AppendLine("  - For **ApiKey**, provide the apikey access token in the format `apikey {ApiID}:{ApiKey}` where `{ApiID}` and `{ApiKey}` are the values provided by M1.\n\n\n");
		stringBuilder.AppendLine("## Developer Notes for the M1 Private API (BOM and EDI resources):\n");
		stringBuilder.AppendLine("In All POST Methods:\n");
		stringBuilder.AppendLine("- Response content type and the parameter content type should be same.\n");
		stringBuilder.AppendLine("- All xml node names should be of camel case. For example:edI850SalesOrders.\n");
		stringBuilder.AppendLine("- There are some known issues in xml formats described in the help. Compare xml against relevant json models when constructing or contact M1.\n\n\n");
		stringBuilder.AppendLine("<!--COMMON-->\n");
		stringBuilder.AppendLine("## Developer Notes for the M1 Public API (ERP resource):\n");
		if (!string.IsNullOrEmpty(Registry.GetValue("HKEY_LOCAL_MACHINE\\SOFTWARE\\ECI\\M1", "HostedApiAuthenticationKey", string.Empty) as string))
		{
			stringBuilder.AppendLine("### Hosted Environment\n");
			stringBuilder.AppendLine("If you are using the public API for a hosted M1 customer, you must connect to the public API using the Integration Engine. Please contact M1 Support to assist with this process.\n");
		}
		stringBuilder.AppendLine("### Date and Time Fields\n");
		stringBuilder.AppendLine("All dates submitted to the API are assumed to be in local time. Likewise, all dates returned from the API are in local time.\n");
		stringBuilder.AppendLine("**Format of Date/Time Fields**\n");
		stringBuilder.AppendLine("When submitting date and datetime fields through the Web API, values should match the following formats `yyyy-MM-ddTHH:mm:ss` or `yyyy-MM-dd`\n");
		stringBuilder.AppendLine("### Filter Expressions\n");
		stringBuilder.AppendLine("For resources that support filtering, filter expressions can be applied as query string parameters in the format `M1Field[operator]value`\n");
		stringBuilder.AppendLine("**Operators**\n");
		stringBuilder.AppendLine("- `[eq]` Equal to the given value.\n");
		stringBuilder.AppendLine("- `[ne]` Not Equal to the given value.\n");
		stringBuilder.AppendLine("- `[gt]` Greater than the given value.\n");
		stringBuilder.AppendLine("- `[lt]` Less than the given value.\n");
		stringBuilder.AppendLine("Example:\n");
		stringBuilder.AppendLine("`?filter=impPartID[eq]CLIP&filter=impPartType[eq]2`\n");
		stringBuilder.AppendLine("If you have multiple filters to apply, add them as separate filter query parameters.\n");
		stringBuilder.AppendLine("### Paging Parameters\n");
		stringBuilder.AppendLine("The parameters `pageSize` and `pageNumber` can be provided separately but can be combined to implement server-side paging of results.\n");
		stringBuilder.AppendLine("Example:\n");
		stringBuilder.AppendLine("`?pageSize=100&pageNumber=5`\n");
		stringBuilder.AppendLine("Page Size defaults to 1000, which is also the maximum.\n");
		stringBuilder.AppendLine("Page Number defaults to 0, which is first page of results.\n");
		stringBuilder.AppendLine("### Order By Expressions\n");
		stringBuilder.AppendLine("For resources that support sorting, the order by expression is specified by adding the orderBy query string parameter in the format `M1Field[Operator],M1Field[Operator]`. The following operators are supported: `Asc` or `Desc`\n");
		stringBuilder.AppendLine("Example:\n");
		stringBuilder.AppendLine("`?orderBy=impPartID[Asc],impPartType[Desc]`\n");
		stringBuilder.AppendLine("### Concurrency Checking\n");
		stringBuilder.AppendLine("Unless otherwise noted, the PUT endpoint requires the row version field from all standard tables to be specified. This will ensure a concurrency check is performed and will make it less likely data is overwritten. If the row version is not the current value, the server will respond with an HTTP 409 Conflict status. This is likely an indication that another user has modified this record since you retrieved it. To resolve, retrieve the record again and include the current row version value.\n");
		stringBuilder.AppendLine("### Error Responses\n");
		stringBuilder.AppendLine("In general throughout the API, a 400 Bad Request Error is returned when invalid data is sent.\n");
		stringBuilder.AppendLine("Error responses are return in the JSON format shown below:\n");
		stringBuilder.AppendLine("**A sample 400 Bad Request or 500 Internal Server Error**\n");
		stringBuilder.AppendLine("```json");
		stringBuilder.AppendLine("{");
		stringBuilder.AppendLine("    \"description\": \"\",");
		stringBuilder.AppendLine("    \"status\": \"Error\",");
		stringBuilder.AppendLine("    \"payloadID\": \"\",");
		stringBuilder.AppendLine("    \"errors\": [");
		stringBuilder.AppendLine("        {");
		stringBuilder.AppendLine("            \"innerText\": \"Filter clause passed 'impPartType[foo]12' is invalid.\"");
		stringBuilder.AppendLine("        }");
		stringBuilder.AppendLine("    ],");
		stringBuilder.AppendLine("    \"warnings\": []");
		stringBuilder.AppendLine("}");
		stringBuilder.AppendLine("```\n");
		stringBuilder.AppendLine("### Product Code\n");
		stringBuilder.AppendLine("To use the BOM/EDI or ERP APIs, you require a product code issued by ECI. Please contact your account manager for further information.\n");
		return stringBuilder.ToString();
	}
}
