#!/usr/bin/env bash
set -Eeuo pipefail

source_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cost_config="/etc/cost-calculator/runtime.env"
cost_caddy_config="/etc/cost-calculator/caddy.env"
cost_users="/var/lib/cost-calculator/users/app_users.json"
config_root="/etc/shopify-order-listener"
runtime_config="$config_root/runtime.env"
state_root="/var/lib/shopify-order-listener"
secret_root="$state_root/secrets"
database_root="$state_root/database"
runtime_user="cost-calculator"
runtime_group="cost-calculator"
enable_writes=false
writes_choice="preserve"

log() { printf '\n==> %s\n' "$*"; }
fail() { printf '\nERROR: %s\n' "$*" >&2; exit 1; }

for argument in "$@"; do
    case "$argument" in
        --enable-m1-writes) writes_choice="enable" ;;
        --disable-m1-writes) writes_choice="disable" ;;
        --help|-h)
            printf 'Usage: sudo bash deployment/ubuntu/deploy-on-costing-vm.sh [--enable-m1-writes|--disable-m1-writes]\n'
            printf 'Installs beside an existing native cost-calculator deployment.\n'
            exit 0
            ;;
        *) fail "Unknown argument: $argument" ;;
    esac
done

[[ "${EUID:-$(id -u)}" -eq 0 ]] || fail "Run with sudo."
[[ -t 0 ]] || fail "Interactive input is required for first-time API credentials."
[[ -r "$cost_config" ]] || fail "The costing calculator runtime file is missing: $cost_config"
[[ -r "$cost_caddy_config" ]] || fail "The costing calculator Caddy environment is missing: $cost_caddy_config"
[[ -r "$cost_users" ]] || fail "The costing calculator user directory is missing: $cost_users"
[[ -r /etc/caddy/Caddyfile ]] || fail "The existing Caddyfile is missing."
id "$runtime_user" >/dev/null 2>&1 || fail "The existing $runtime_user service account is missing."

# Both files are root-owned configuration generated by the costing installer.
set -a
# shellcheck disable=SC1090
source "$cost_config"
set +a

[[ "${COST_ERP_DATABASE:-M1_ME}" == "M1_ME" ]] || \
    fail "The listener requires COST_ERP_DATABASE=M1_ME; found ${COST_ERP_DATABASE:-unset}."
for required in COST_DB_SERVER COST_DB_USERNAME COST_DB_PASSWORD_FILE; do
    [[ -n "${!required:-}" ]] || fail "$required is missing from $cost_config"
done
[[ -r "$COST_DB_PASSWORD_FILE" ]] || fail "The shared SQL password file is not readable: $COST_DB_PASSWORD_FILE"
[[ "$COST_DB_USERNAME" =~ ^[A-Za-z_][A-Za-z0-9_@\$-]{0,127}$ ]] || \
    fail "The costing SQL username contains unsupported characters."

existing_shop=""
existing_shopify_client_id=""
existing_m1_url="http://172.16.225.73:1937"
existing_m1_api_id=""
existing_writes="false"
if [[ -r "$runtime_config" ]]; then
    set -a
    # shellcheck disable=SC1090
    source "$runtime_config"
    set +a
    existing_shop="${SHOPIFY_SHOP:-}"
    existing_shopify_client_id="${SHOPIFY_CLIENT_ID:-}"
    existing_m1_url="${M1_API_BASE_URL:-$existing_m1_url}"
    existing_m1_api_id="${M1_API_ID:-}"
    existing_writes="${M1_WRITES_ENABLED:-false}"
fi
case "$writes_choice" in
    enable) enable_writes=true ;;
    disable) enable_writes=false ;;
    preserve) [[ "$existing_writes" == "true" ]] && enable_writes=true ;;
esac

prompt_value() {
    local label="$1" default_value="$2" result
    while true; do
        if [[ -n "$default_value" ]]; then
            read -r -p "$label [$default_value]: " result
            result="${result:-$default_value}"
        else
            read -r -p "$label: " result
        fi
        [[ -n "$result" && "$result" != *$'\n'* && "$result" != *$'\r'* ]] && {
            REPLY_VALUE="$result"
            return
        }
        printf 'A value is required.\n' >&2
    done
}

write_secret() {
    local label="$1" path="$2" first confirmation
    if [[ -s "$path" ]]; then
        read -r -s -p "$label (Enter to keep the existing value): " first
        printf '\n'
        [[ -n "$first" ]] || return
    else
        while [[ -z "${first:-}" ]]; do
            read -r -s -p "$label: " first
            printf '\n'
        done
    fi
    read -r -s -p "Confirm $label: " confirmation
    printf '\n'
    [[ "$first" == "$confirmation" ]] || fail "$label values did not match."
    printf '%s' "$first" > "$path"
    unset first confirmation
    chown root:"$runtime_group" "$path"
    chmod 0640 "$path"
}

write_environment_value() {
    local name="$1" value="$2"
    [[ "$value" != *$'\n'* && "$value" != *$'\r'* ]] || fail "Invalid newline in $name"
    printf '%s=' "$name"
    printf '%q\n' "$value"
}

log "Reading deployment values"
prompt_value "Shopify shop subdomain" "$existing_shop"
shopify_shop="$REPLY_VALUE"
shopify_shop="${shopify_shop%.myshopify.com}"
prompt_value "Shopify client ID" "$existing_shopify_client_id"
shopify_client_id="$REPLY_VALUE"
prompt_value "M1 Public API base URL" "$existing_m1_url"
m1_url="${REPLY_VALUE%/}"
prompt_value "M1 API ID" "$existing_m1_api_id"
m1_api_id="$REPLY_VALUE"

install -d -m 0750 -o root -g "$runtime_group" "$config_root"
install -d -m 0750 -o "$runtime_user" -g "$runtime_group" "$state_root"
install -d -m 0750 -o root -g "$runtime_group" "$secret_root" "$database_root"
for secret_file in "$secret_root/shopify_client_secret.txt" "$secret_root/m1_api_key.txt"; do
    if [[ ! -e "$secret_file" ]]; then
        install -m 0640 -o root -g "$runtime_group" /dev/null "$secret_file"
    fi
done

write_secret "Shopify client secret" "$secret_root/shopify_client_secret.txt"
write_secret "M1 API key" "$secret_root/m1_api_key.txt"
if [[ ! -s "$secret_root/session_secret.txt" ]]; then
    openssl rand -hex 32 > "$secret_root/session_secret.txt"
fi
chown root:"$runtime_group" "$secret_root/session_secret.txt"
chmod 0640 "$secret_root/session_secret.txt"

revision="$(git -C "$source_root" rev-parse --short HEAD 2>/dev/null || printf development)"
version="$revision-$(date -u +%Y%m%d%H%M%S)"
temporary_runtime="$(mktemp "$config_root/runtime.XXXXXX")"
{
    write_environment_value APP_VERSION "$version"
    write_environment_value SALES_ORDER_AUTH_REQUIRED true
    write_environment_value SALES_ORDER_USERS_JSON_FILE "$cost_users"
    write_environment_value SALES_ORDER_SESSION_SECRET_FILE "$secret_root/session_secret.txt"
    write_environment_value SALES_ORDER_STARTUP_SYNC true
    write_environment_value SALES_ORDER_BACKGROUND_SYNC true
    write_environment_value SALES_ORDER_STORAGE_MODE sql
    write_environment_value SALES_ORDER_DB_SERVER "$COST_DB_SERVER"
    write_environment_value SALES_ORDER_DB_USERNAME "$COST_DB_USERNAME"
    write_environment_value SALES_ORDER_DB_DRIVER "${COST_DB_DRIVER:-ODBC Driver 18 for SQL Server}"
    write_environment_value SALES_ORDER_DB_TRUST_SERVER_CERTIFICATE "${COST_DB_TRUST_SERVER_CERTIFICATE:-false}"
    write_environment_value SALES_ORDER_DB_PASSWORD_FILE "$COST_DB_PASSWORD_FILE"
    write_environment_value SHOPIFY_SHOP "$shopify_shop"
    write_environment_value SHOPIFY_CLIENT_ID "$shopify_client_id"
    write_environment_value SHOPIFY_CLIENT_SECRET_FILE "$secret_root/shopify_client_secret.txt"
    write_environment_value SHOPIFY_API_VERSION 2026-07
    write_environment_value M1_API_BASE_URL "$m1_url"
    write_environment_value M1_API_ID "$m1_api_id"
    write_environment_value M1_API_KEY_FILE "$secret_root/m1_api_key.txt"
    write_environment_value M1_WRITES_ENABLED "$enable_writes"
    write_environment_value M1_DEFAULT_WAREHOUSE 142
    write_environment_value M1_DEFAULT_BIN BIN1
    write_environment_value M1_DEFAULT_UOM EA
} > "$temporary_runtime"
chown root:"$runtime_group" "$temporary_runtime"
chmod 0640 "$temporary_runtime"
mv -f "$temporary_runtime" "$runtime_config"

log "Installing the sales-order service"
SALES_ORDER_SERVICE_USER="$runtime_user" \
SALES_ORDER_SERVICE_GROUP="$runtime_group" \
APP_VERSION="$version" \
    bash "$source_root/deployment/ubuntu/install.sh"

run_app_python() {
    runuser -u "$runtime_user" -- bash -c '
        runtime_file="$1"
        application_root="$2"
        shift 2
        cd "$application_root"
        set -a
        source "$runtime_file"
        set +a
        exec "$@"
    ' _ "$runtime_config" "/opt/shopify-order-listener/current/shopifyOrderListener" \
        "/opt/shopify-order-listener/current/.venv/bin/python" "$@"
}

render_bootstrap() {
    local target="$database_root/bootstrap-sales-orders.sql"
    {
        cat "$source_root/database/apply_all_migrations.sql"
        sed "s/cost_app_access/$COST_DB_USERNAME/g" "$source_root/database/grant_runtime_principal.sql"
    } > "$target"
    chown root:"$runtime_group" "$target"
    chmod 0640 "$target"
    printf '%s' "$target"
}

log "Checking the SalesOrders staging schema"
if ! run_app_python -m tools.apply_salesorders_migrations; then
    printf 'The staging schema is not ready; trying the shared costing SQL login once.\n'
    if ! run_app_python -m tools.apply_salesorders_migrations --apply; then
        bootstrap_file="$(render_bootstrap)"
        systemctl stop shopify-order-listener.service || true
        printf '\nThe costing runtime login is correctly restricted from creating schemas.\n' >&2
        printf 'A DBA must run this generated, non-secret SQL file against M1_ME once:\n\n  %s\n\n' "$bootstrap_file" >&2
        printf 'Then rerun this same installer; press Enter to keep the stored API secrets.\n' >&2
        exit 2
    fi
fi

log "Installing the persistent Caddy route"
install -d -m 0755 -o root -g root /usr/local/lib/shopify-order-listener
install -m 0755 -o root -g root \
    "$source_root/deployment/ubuntu/ensure-caddy-route.py" \
    /usr/local/lib/shopify-order-listener/ensure-caddy-route.py
install -d -m 0755 -o root -g root /etc/systemd/system/caddy.service.d
cat > /etc/systemd/system/caddy.service.d/shopify-order-listener.conf <<'EOF'
[Service]
ExecStartPre=/usr/bin/python3 /usr/local/lib/shopify-order-listener/ensure-caddy-route.py /etc/caddy/Caddyfile
EOF
chmod 0644 /etc/systemd/system/caddy.service.d/shopify-order-listener.conf
python3 /usr/local/lib/shopify-order-listener/ensure-caddy-route.py /etc/caddy/Caddyfile

set -a
# shellcheck disable=SC1090
source "$cost_caddy_config"
set +a
caddy validate --config /etc/caddy/Caddyfile
systemctl daemon-reload
systemctl restart caddy.service

log "Verifying SQL, M1, and Shopify"
run_app_python -m tools.deployment_preflight
systemctl restart shopify-order-listener.service

printf 'Waiting for the startup reconciliation to complete'
ready=false
for _ in $(seq 1 90); do
    if curl --fail --silent --max-time 3 http://127.0.0.1:8010/sales-orders/api/health >/dev/null; then
        ready=true
        break
    fi
    printf '.'
    sleep 3
done
printf '\n'
[[ "$ready" == true ]] || {
    journalctl -u shopify-order-listener.service -n 80 --no-pager >&2
    fail "The service did not become ready within 270 seconds."
}

caddy_root="/var/lib/caddy/data/caddy/pki/authorities/local/root.crt"
if [[ -r "$caddy_root" && -n "${APP_HOSTNAME:-}" ]]; then
    curl --fail --silent --cacert "$caddy_root" \
        --resolve "$APP_HOSTNAME:443:127.0.0.1" \
        "https://$APP_HOSTNAME/sales-orders/api/health" >/dev/null
fi

log "Deployment complete"
printf 'URL: https://%s/sales-orders/\n' "${APP_HOSTNAME:-costing.meziere.net}"
printf 'Authentication: shared with the cost calculator (%s)\n' "$cost_users"
printf 'SQL connection: shared from %s\n' "$cost_config"
printf 'M1 writes enabled: %s\n' "$enable_writes"
