using M1.Core;

namespace M1.Ax.Erp.DD;

[DBConversion("7.20.005", "Update Previous Amts on Invoice Revaluations table", "2009-03-26")]
public class v720005b
{
	public v720005b(DBConversionParms parms)
	{
		string text = "";
		text += "Update ARInvoiceRevaluations Set ";
		text += "\tarvPrevAmountBase = arpInvoiceTotalBase-arpDepositAppliedBase ";
		text += "\t- isnull((select sum(arnPaymentAmount + arnDiscountAmount + arnDiscountTaxAmount + arnSecondDiscountTaxAmount ";
		text += "\t\t\t\t- arnAdjustmentAmount - arnTaxAmount - arnSecondTaxAmount - arnExchangeAmount - arnUnrealisedExchangeAmt) ";
		text += "\t\tfrom ARPaymentLines inner join ARPaymentHeaders on arnARPaymentSessionID=artARPaymentSessionID and arnARPaymentHeaderID=artARPaymentHeaderID ";
		text += "\t\t where arnARInvoiceID=arpARInvoiceID AND ";
		text += "\t\t\t(ARPaymentHeaders.artGLFiscalYearID <= arvGLFiscalYearID AND ";
		text += "\t\t\t(ARPaymentHeaders.artGLFiscalYearID <> arvGLFiscalYearID OR ";
		text += "\t\t\tARPaymentHeaders.artGLFiscalYearID = arvGLFiscalYearID AND ";
		text += "\t\t\tARPaymentHeaders.artGLFiscalYearPeriodID <= arvGLFiscalYearPeriodID)) AND ";
		text += "\t\t\tARPaymentHeaders.artPostedToGL = -1 AND ";
		text += "\t\t\tARPaymentHeaders.artReceiptDate <= arvRevalueDate AND ";
		text += "\t\t\tARPaymentLines.arnOverpayment = 0),0) ";
		text += "\t+ isnull((select sum(arnPaymentAmount) ";
		text += "\t\tfrom ARPaymentLines inner join ARPaymentHeaders on arnARPaymentSessionID=artARPaymentSessionID and arnARPaymentHeaderID=artARPaymentHeaderID ";
		text += "\t\twhere artCreditARInvoiceID=arpARInvoiceID AND ";
		text += "\t\t\t(ARPaymentHeaders.artGLFiscalYearID <= arvGLFiscalYearID AND ";
		text += "\t\t\t(ARPaymentHeaders.artGLFiscalYearID <> arvGLFiscalYearID OR ";
		text += "\t\t\tARPaymentHeaders.artGLFiscalYearID = arvGLFiscalYearID AND ";
		text += "\t\t\tARPaymentHeaders.artGLFiscalYearPeriodID <= arvGLFiscalYearPeriodID)) AND ";
		text += "\t\t\tARPaymentHeaders.artPostedToGL = -1 AND ";
		text += "\t\t\tARPaymentHeaders.artReceiptDate <= arvRevalueDate),0) ";
		text += "\t- isnull((select sum(apnPaymentAmount + apnDiscountAmount + apnDiscountTaxAmount + apnSecondDiscountTaxAmount ";
		text += "\t\t\t\t+ apnAdjustmentAmount + apnTaxAmount + apnSecondTaxAmount - apnExchangeAmount - apnUnrealisedExchangeAmt) ";
		text += "\t\tfrom APPaymentLines inner join APPaymentHeaders on apnAPPaymentSessionID=aptAPPaymentSessionID and apnAPPaymentHeaderID=aptAPPaymentHeaderID ";
		text += "\t\twhere apnARInvoiceID=arpARInvoiceID AND ";
		text += "\t\t\t(APPaymentHeaders.aptGLFiscalYearID <= arvGLFiscalYearID AND ";
		text += "\t\t\t(APPaymentHeaders.aptGLFiscalYearID <> arvGLFiscalYearID OR ";
		text += "\t\t\tAPPaymentHeaders.aptGLFiscalYearID = arvGLFiscalYearID AND ";
		text += "\t\t\tAPPaymentHeaders.aptGLFiscalYearPeriodID <= arvGLFiscalYearPeriodID)) AND ";
		text += "\t\t\tAPPaymentHeaders.aptPostedToGL = -1 AND ";
		text += "\t\t\tAPPaymentHeaders.aptPaymentDate <= arvRevalueDate),0) ";
		text += "\t+ isnull((select sum(R.arvExchangeAmount) ";
		text += "\t\tfrom ARInvoiceRevaluations R ";
		text += "\t\twhere R.arvARInvoiceID=arpARInvoiceID AND ";
		text += "\t\t\tR.arvRevalueDate <= ARInvoiceRevaluations.arvRevalueDate And R.arvARInvoiceRevaluationID <> ARInvoiceRevaluations.arvARInvoiceRevaluationID),0), ";
		text += "\tarvPrevAmountForeign = arpInvoiceTotalForeign -  arpDepositAppliedForeign ";
		text += "\t- isnull((select sum(arnPaymentAmountForeign + arnDiscountAmountForeign + arnDiscountTaxAmountForeign + arnSecondDisTaxAmtForeign ";
		text += "\t\t\t\t- arnAdjustmentAmountForeign - arnTaxAmountForeign - arnSecondTaxAmountForeign) ";
		text += "\t\tfrom ARPaymentLines inner join ARPaymentHeaders on arnARPaymentSessionID=artARPaymentSessionID and arnARPaymentHeaderID=artARPaymentHeaderID ";
		text += "\t\t where arnARInvoiceID=arpARInvoiceID AND ";
		text += "\t\t\t(ARPaymentHeaders.artGLFiscalYearID <= arvGLFiscalYearID AND ";
		text += "\t\t\t(ARPaymentHeaders.artGLFiscalYearID <> arvGLFiscalYearID OR ";
		text += "\t\t\tARPaymentHeaders.artGLFiscalYearID = arvGLFiscalYearID AND ";
		text += "\t\t\tARPaymentHeaders.artGLFiscalYearPeriodID <= arvGLFiscalYearPeriodID)) AND ";
		text += "\t\t\tARPaymentHeaders.artPostedToGL = -1 AND ";
		text += "\t\t\tARPaymentHeaders.artReceiptDate <= arvRevalueDate AND ";
		text += "\t\t\tARPaymentLines.arnOverpayment = 0),0) ";
		text += "\t+ isnull((select sum(arnPaymentAmountForeign) ";
		text += "\t\tfrom ARPaymentLines inner join ARPaymentHeaders on arnARPaymentSessionID=artARPaymentSessionID and arnARPaymentHeaderID=artARPaymentHeaderID ";
		text += "\t\twhere artCreditARInvoiceID=arpARInvoiceID AND ";
		text += "\t\t\t(ARPaymentHeaders.artGLFiscalYearID <= arvGLFiscalYearID AND ";
		text += "\t\t\t(ARPaymentHeaders.artGLFiscalYearID <> arvGLFiscalYearID OR ";
		text += "\t\t\tARPaymentHeaders.artGLFiscalYearID = arvGLFiscalYearID AND ";
		text += "\t\t\tARPaymentHeaders.artGLFiscalYearPeriodID <= arvGLFiscalYearPeriodID)) AND ";
		text += "\t\t\tARPaymentHeaders.artPostedToGL = -1 AND ";
		text += "\t\t\tARPaymentHeaders.artReceiptDate <= arvRevalueDate),0) ";
		text += "\t- isnull((select sum(apnPaymentAmountForeign + apnDiscountAmountForeign + apnDiscountTaxAmountForeign + apnSecondDisTaxAmtForeign ";
		text += "\t\t\t\t+ apnAdjustmentAmountForeign + apnTaxAmountForeign + apnSecondTaxAmountForeign) ";
		text += "\t\tfrom APPaymentLines inner join APPaymentHeaders on apnAPPaymentSessionID=aptAPPaymentSessionID and apnAPPaymentHeaderID=aptAPPaymentHeaderID ";
		text += "\t\twhere apnARInvoiceID=arpARInvoiceID AND ";
		text += "\t\t\t(APPaymentHeaders.aptGLFiscalYearID <= arvGLFiscalYearID AND ";
		text += "\t\t\t(APPaymentHeaders.aptGLFiscalYearID <> arvGLFiscalYearID OR ";
		text += "\t\t\tAPPaymentHeaders.aptGLFiscalYearID = arvGLFiscalYearID AND ";
		text += "\t\t\tAPPaymentHeaders.aptGLFiscalYearPeriodID <= arvGLFiscalYearPeriodID)) AND ";
		text += "\t\t\tAPPaymentHeaders.aptPostedToGL = -1 AND ";
		text += "\t\t\tAPPaymentHeaders.aptPaymentDate <= arvRevalueDate),0) ";
		text += "from ARInvoices Inner Join ARInvoiceRevaluations on arpARInvoiceID = arvARInvoiceID ";
		parms.ServerManager.ExecuteCommand(null, parms.User, parms.DatabaseName, text);
		text = "";
		text += "Update APInvoiceRevaluations Set ";
		text += "\tapvPrevAmountBase = appInvoiceTotalBase ";
		text += "\t- isnull((select sum(apnPaymentAmount + apnDiscountAmount + apnDiscountTaxAmount + ";
		text += "\t\tapnSecondDiscountTaxAmount + apnAdjustmentAmount + apnTaxAmount + apnSecondTaxAmount + apnExchangeAmount + apnUnrealisedExchangeAmt) ";
		text += "\t\tfrom APPaymentLines inner join APPaymentHeaders on apnAPPaymentSessionID=aptAPPaymentSessionID and apnAPPaymentHeaderID=aptAPPaymentHeaderID ";
		text += "\t\twhere apnAPInvoiceID=appAPInvoiceID AND ";
		text += "\t\t\t(APPaymentHeaders.aptGLFiscalYearID <= apvGLFiscalYearID AND ";
		text += "\t\t\t(APPaymentHeaders.aptGLFiscalYearID <> apvGLFiscalYearID OR ";
		text += "\t\t\tAPPaymentHeaders.aptGLFiscalYearID = apvGLFiscalYearID AND ";
		text += "\t\t\tAPPaymentHeaders.aptGLFiscalYearPeriodID <= apvGLFiscalYearPeriodID)) AND ";
		text += "\t\t\tAPPaymentHeaders.aptPostedToGL = -1 AND ";
		text += "\t\t\tapnOverpayment = 0 AND ";
		text += "\t\t\tAPPaymentHeaders.aptPaymentDate <= apvRevalueDate),0) ";
		text += "\t+ isnull((select sum(apnPaymentAmount) from APPaymentLines inner join APPaymentHeaders on ";
		text += "\t\tapnAPPaymentSessionID=aptAPPaymentSessionID and apnAPPaymentHeaderID=aptAPPaymentHeaderID ";
		text += "\t\twhere aptCreditAPInvoiceID=appAPInvoiceID AND ";
		text += "\t\t\t(APPaymentHeaders.aptGLFiscalYearID <= apvGLFiscalYearID AND ";
		text += "\t\t\t(APPaymentHeaders.aptGLFiscalYearID <> apvGLFiscalYearID OR ";
		text += "\t\t\t APPaymentHeaders.aptGLFiscalYearID = apvGLFiscalYearID AND ";
		text += "\t\t\tAPPaymentHeaders.aptGLFiscalYearPeriodID <= apvGLFiscalYearPeriodID)) AND ";
		text += "\t\t\tAPPaymentHeaders.aptPostedToGL = -1 AND APPaymentHeaders.aptPaymentDate <= apvRevalueDate),0) ";
		text += "\t- isnull((select sum(arnPaymentAmount + arnDiscountAmount + arnDiscountTaxAmount + arnSecondDiscountTaxAmount - ";
		text += "\t\tarnAdjustmentAmount - arnTaxAmount - arnSecondTaxAmount + arnExchangeAmount + arnUnrealisedExchangeAmt) ";
		text += "\t\tfrom ARPaymentLines inner join ARPaymentHeaders on arnARPaymentSessionID=artARPaymentSessionID and arnARPaymentHeaderID=artARPaymentHeaderID ";
		text += "\t\twhere arnAPInvoiceID=appAPInvoiceID AND ";
		text += "\t\t\t(ARPaymentHeaders.artGLFiscalYearID <= apvGLFiscalYearID AND ";
		text += "\t\t\t(ARPaymentHeaders.artGLFiscalYearID <> apvGLFiscalYearID OR ";
		text += "\t\t\t ARPaymentHeaders.artGLFiscalYearID = apvGLFiscalYearID AND ";
		text += "\t\t\tARPaymentHeaders.artGLFiscalYearPeriodID <= apvGLFiscalYearPeriodID)) AND ";
		text += "\t\t\tARPaymentHeaders.artPostedToGL = -1 AND ARPaymentHeaders.artReceiptDate <= apvRevalueDate),0) ";
		text += "\t+ isnull((select sum(apvExchangeAmount) ";
		text += "\t\tfrom APInvoiceRevaluations R ";
		text += "\t\twhere R.apvAPInvoiceID=appAPInvoiceID AND ";
		text += "\t\t\tR.apvRevalueDate <= APInvoiceRevaluations.apvRevalueDate And R.apvAPInvoiceRevaluationID <> APInvoiceRevaluations.apvAPInvoiceRevaluationID),0), ";
		text += "\tapvPrevAmountForeign = appInvoiceTotalForeign ";
		text += "\t- isnull((select sum(apnPaymentAmountForeign + apnDiscountAmountForeign + apnDiscountTaxAmountForeign + ";
		text += "\t\tapnSecondDisTaxAmtForeign + apnAdjustmentAmountForeign + apnTaxAmountForeign + apnSecondTaxAmountForeign) ";
		text += "\t\tfrom APPaymentLines inner join APPaymentHeaders on apnAPPaymentSessionID=aptAPPaymentSessionID and apnAPPaymentHeaderID=aptAPPaymentHeaderID ";
		text += "\t\twhere apnAPInvoiceID=appAPInvoiceID AND ";
		text += "\t\t\t(APPaymentHeaders.aptGLFiscalYearID <=  apvGLFiscalYearID AND ";
		text += "\t\t\t(APPaymentHeaders.aptGLFiscalYearID <>  apvGLFiscalYearID OR ";
		text += "\t\t\tAPPaymentHeaders.aptGLFiscalYearID =  apvGLFiscalYearID AND ";
		text += "\t\t\tAPPaymentHeaders.aptGLFiscalYearPeriodID <=  apvGLFiscalYearPeriodID)) AND ";
		text += "\t\t\tAPPaymentHeaders.aptPostedToGL = -1 AND ";
		text += "\t\t\tapnOverpayment = 0 AND ";
		text += "\t\t\tAPPaymentHeaders.aptPaymentDate <= apvRevalueDate),0) ";
		text += "\t+ isnull((select sum(apnPaymentAmountForeign) from APPaymentLines inner join APPaymentHeaders on ";
		text += "\t\tapnAPPaymentSessionID=aptAPPaymentSessionID and apnAPPaymentHeaderID=aptAPPaymentHeaderID ";
		text += "\t\twhere aptCreditAPInvoiceID=appAPInvoiceID AND ";
		text += "\t\t(APPaymentHeaders.aptGLFiscalYearID <= apvGLFiscalYearID AND ";
		text += "\t\t(APPaymentHeaders.aptGLFiscalYearID <> apvGLFiscalYearID OR ";
		text += "\t\t APPaymentHeaders.aptGLFiscalYearID = apvGLFiscalYearID AND ";
		text += "\t\tAPPaymentHeaders.aptGLFiscalYearPeriodID <= apvGLFiscalYearPeriodID)) AND ";
		text += "\t\tAPPaymentHeaders.aptPostedToGL = -1 AND APPaymentHeaders.aptPaymentDate <= apvRevalueDate),0) ";
		text += "\t- isnull((select sum(arnPaymentAmountForeign + arnDiscountAmountForeign + arnDiscountTaxAmountForeign + arnSecondDisTaxAmtForeign - ";
		text += "\t\tarnAdjustmentAmountForeign - arnTaxAmountForeign - arnSecondTaxAmountForeign) ";
		text += "\t\tfrom ARPaymentLines ";
		text += "\t\tinner join ARPaymentHeaders on arnARPaymentSessionID=artARPaymentSessionID and arnARPaymentHeaderID=artARPaymentHeaderID ";
		text += "\t\twhere arnAPInvoiceID=appAPInvoiceID AND ";
		text += "\t\t(ARPaymentHeaders.artGLFiscalYearID <= apvGLFiscalYearID AND ";
		text += "\t\t(ARPaymentHeaders.artGLFiscalYearID <> apvGLFiscalYearID OR ";
		text += "\t\t ARPaymentHeaders.artGLFiscalYearID = apvGLFiscalYearID AND ";
		text += "\t\tARPaymentHeaders.artGLFiscalYearPeriodID <= apvGLFiscalYearPeriodID)) AND ";
		text += "\t\tARPaymentHeaders.artPostedToGL = -1 AND ARPaymentHeaders.artReceiptDate <= apvRevalueDate),0) ";
		text += "from APInvoices Inner Join APInvoiceRevaluations on appAPInvoiceID = apvAPInvoiceID ";
		parms.ServerManager.ExecuteCommand(null, parms.User, parms.DatabaseName, text);
	}
}
