using M1.Core;

namespace M1.Ax.Erp.DD;

[DBConversion("8.10.050", "Convert FinancialProperties to support unicode", "2013-10-17")]
public class v810RebuildFinancialProperties
{
	public v810RebuildFinancialProperties(DBConversionParms parms)
	{
		parms.Dmo.RebuildTable(null, parms.User, parms.DataDictionary, parms.DatabaseName, "FinancialProperties", new DmoField[136]
		{
			new DmoField("xafARARGLAccountID", "nvarchar", 11, 0, nullable: false),
			new DmoField("xafARCashGLAccountID", "nvarchar", 11, 0, nullable: false),
			new DmoField("xafARFreightGLAccountID", "nvarchar", 11, 0, nullable: false),
			new DmoField("xafARDiscountGLAccountID", "nvarchar", 11, 0, nullable: false),
			new DmoField("xafARCreateDiscountJournals", "bit", 1, 0, nullable: false),
			new DmoField("xafARTaxOnFreight", "bit", 1, 0, nullable: false),
			new DmoField("xafARGroupShipmentsByCustomer", "tinyint", 1, 0, nullable: false),
			new DmoField("xafARShowDeposits", "tinyint", 1, 0, nullable: false),
			new DmoField("xafAgingMethod", "tinyint", 1, 0, nullable: false),
			new DmoField("xafTaxOnReportMethod", "nvarchar", 1, 0, nullable: false),
			new DmoField("xafAgeByDaysInMonth", "bit", 1, 0, nullable: false),
			new DmoField("xafARAgingBucketID", "nvarchar", 5, 0, nullable: false),
			new DmoField("xafARAllowParentAccountPost", "bit", 1, 0, nullable: false),
			new DmoField("xafARDisableTaxFields", "bit", 1, 0, nullable: false),
			new DmoField("xafARExpressPost", "bit", 1, 0, nullable: false),
			new DmoField("xafARCreditUpdatesShipment", "bit", 1, 0, nullable: false),
			new DmoField("xafPOSCustomerOrganizationID", "nvarchar", 10, 0, nullable: false),
			new DmoField("xafPOSShowDiscounts", "bit", 1, 0, nullable: false),
			new DmoField("xafARFinanceChargeGLAccountID", "nvarchar", 11, 0, nullable: false),
			new DmoField("xafARFinanceChargeGraceDays", "smallint", 3, 0, nullable: false),
			new DmoField("xafARFinanceChargeLastRunDate", "datetime", 14, 0, nullable: true),
			new DmoField("xafARFinanceChargePercent", "numeric", 6, 3, nullable: false),
			new DmoField("xafARVerisignURL", "nvarchar", 120, 0, nullable: false),
			new DmoField("xafARVerisignPort", "int", 4, 0, nullable: false),
			new DmoField("xafARVerisignUserID", "nvarchar", 120, 0, nullable: false),
			new DmoField("xafARVerisignVendorID", "nvarchar", 120, 0, nullable: false),
			new DmoField("xafARVerisignPartnerID", "nvarchar", 120, 0, nullable: false),
			new DmoField("xafARVerisignPassword", "nvarchar(max)", 50, 0, nullable: true),
			new DmoField("xafARVerisignTimeoutSeconds", "int", 4, 0, nullable: false),
			new DmoField("xafARVerisignProxyAddress", "nvarchar", 15, 0, nullable: false),
			new DmoField("xafARVerisignProxyPort", "int", 4, 0, nullable: false),
			new DmoField("xafARVerisignProxyLogon", "nvarchar", 120, 0, nullable: false),
			new DmoField("xafARVerisignProxyPassword", "nvarchar", 120, 0, nullable: false),
			new DmoField("xafVerisignSettlementTime", "numeric", 5, 2, nullable: false),
			new DmoField("xafPartsMustExist", "bit", 1, 0, nullable: false),
			new DmoField("xafVerisignGroupByDay", "bit", 1, 0, nullable: false),
			new DmoField("xafAPAPGLAccountID", "nvarchar", 11, 0, nullable: false),
			new DmoField("xafAPCashGLAccountID", "nvarchar", 11, 0, nullable: false),
			new DmoField("xafAPFreightGLAccountID", "nvarchar", 11, 0, nullable: false),
			new DmoField("xafAPDiscountGLAccountID", "nvarchar", 11, 0, nullable: false),
			new DmoField("xafAPGroupReceiptsBySupplier", "tinyint", 1, 0, nullable: false),
			new DmoField("xafAPTaxOnFreight", "bit", 1, 0, nullable: false),
			new DmoField("xafAPDiscountOnTax", "bit", 1, 0, nullable: false),
			new DmoField("xafAPUpdateJobCosts", "bit", 1, 0, nullable: false),
			new DmoField("xafAPAPCostStartDate", "date", 14, 0, nullable: true),
			new DmoField("xafAPDisableTaxFields", "bit", 1, 0, nullable: false),
			new DmoField("xafAPPaymentMaxLinesPerPage", "tinyint", 2, 0, nullable: false),
			new DmoField("xafAPAgingBucketID", "nvarchar", 5, 0, nullable: false),
			new DmoField("xafAPAllowParentAccountPost", "bit", 1, 0, nullable: false),
			new DmoField("xafAPExpressPost", "bit", 1, 0, nullable: false),
			new DmoField("xafAPCreditUpdatesReceipt", "bit", 1, 0, nullable: false),
			new DmoField("xafAPAlwaysTakeDiscount", "bit", 1, 0, nullable: false),
			new DmoField("xafGLExpressPost", "bit", 1, 0, nullable: false),
			new DmoField("xafGLFiscalYearID", "smallint", 4, 0, nullable: false),
			new DmoField("xafGLFiscalYearPeriodID", "tinyint", 2, 0, nullable: false),
			new DmoField("xafGLRetainedEarningsAccountID", "nvarchar", 11, 0, nullable: false),
			new DmoField("xafGLPayrollImportFormat", "tinyint", 1, 0, nullable: false),
			new DmoField("xafGLPayrollImportLocation", "nvarchar(max)", 50, 0, nullable: true),
			new DmoField("xafPAShowHolidaysForSalary", "bit", 1, 0, nullable: false),
			new DmoField("xafPAPayrollSort", "tinyint", 1, 0, nullable: false),
			new DmoField("xafPAAllowParentAccountPost", "bit", 1, 0, nullable: false),
			new DmoField("xafPAExpressPost", "bit", 1, 0, nullable: false),
			new DmoField("xafPAAssignNumbersToEFT", "bit", 1, 0, nullable: false),
			new DmoField("xafPADeleteZeroPayHeaders", "bit", 1, 0, nullable: false),
			new DmoField("xafDisableMultiplePlants", "bit", 1, 0, nullable: false),
			new DmoField("xafGLCreateStockJournals", "bit", 1, 0, nullable: false),
			new DmoField("xafCOGSUseAccounts", "tinyint", 1, 0, nullable: false),
			new DmoField("xafSVarLaborGLAccountID", "nvarchar", 11, 0, nullable: false),
			new DmoField("xafSVarMaterialGLAccountID", "nvarchar", 11, 0, nullable: false),
			new DmoField("xafSVarSubcontractGLAccountID", "nvarchar", 11, 0, nullable: false),
			new DmoField("xafSVarOverheadGLAccountID", "nvarchar", 11, 0, nullable: false),
			new DmoField("xafPurchaseVarianceGLAccountID", "nvarchar", 11, 0, nullable: false),
			new DmoField("xafWIPLaborGLAccountID", "nvarchar", 11, 0, nullable: false),
			new DmoField("xafWIPMaterialGLAccountID", "nvarchar", 11, 0, nullable: false),
			new DmoField("xafWIPSubcontractGLAccountID", "nvarchar", 11, 0, nullable: false),
			new DmoField("xafWIPOverheadGLAccountID", "nvarchar", 11, 0, nullable: false),
			new DmoField("xafAccruedCreditorsGLAccountID", "nvarchar", 11, 0, nullable: false),
			new DmoField("xafLaborClearingGLAccountID", "nvarchar", 11, 0, nullable: false),
			new DmoField("xafOverheadClearingGLAccountID", "nvarchar", 11, 0, nullable: false),
			new DmoField("xafStockRevaluationGLAccountID", "nvarchar", 11, 0, nullable: false),
			new DmoField("xafDrawerCashStartAmount", "money", 12, 2, nullable: false),
			new DmoField("xafDrawerCashGLAccountID", "nvarchar", 11, 0, nullable: false),
			new DmoField("xafStoreCreditGLAccountID", "nvarchar", 11, 0, nullable: false),
			new DmoField("xafPOSShowCustSelector", "bit", 1, 0, nullable: false),
			new DmoField("xafPOSSalesGLAccountID", "nvarchar", 11, 0, nullable: false),
			new DmoField("xafFARoundToNearestDollar", "bit", 1, 0, nullable: false),
			new DmoField("xafAPAssignNumbersToEFT", "bit", 1, 0, nullable: false),
			new DmoField("xafIncludeLLInTermination", "bit", 1, 0, nullable: false),
			new DmoField("xafARDepositGLAccountID", "nvarchar", 11, 0, nullable: false),
			new DmoField("xafARCalculateTaxOnDeposit", "bit", 1, 0, nullable: false),
			new DmoField("xafCreateBankEntries", "bit", 1, 0, nullable: false),
			new DmoField("xafPALeaveBalanceCheck", "tinyint", 1, 0, nullable: false),
			new DmoField("xafARIncludeTaxInDepositCalc", "bit", 1, 0, nullable: false),
			new DmoField("xafRecalcSalarySacrifice", "bit", 1, 0, nullable: false),
			new DmoField("xafCreatedBy", "nvarchar", 20, 0, nullable: false),
			new DmoField("xafCreatedDate", "datetime", 14, 0, nullable: true),
			new DmoField("xafUniqueID", "uniqueidentifier", 16, 0, nullable: false),
			new DmoField("xafAPPaymentFilterPlant", "bit", 1, 0, nullable: false),
			new DmoField("xafARPaymentFilterPlant", "bit", 1, 0, nullable: false),
			new DmoField("xafPAUseDate", "tinyint", 1, 0, nullable: false),
			new DmoField("xafAPIncludeTaxInExpAmt", "bit", 1, 0, nullable: false),
			new DmoField("xafShipAwaitInvoiceGLAccountID", "nvarchar", 11, 0, nullable: false),
			new DmoField("xafARDefaultLaborPartGroupID", "nvarchar", 5, 0, nullable: false),
			new DmoField("xafStockInTransitGLAccountID", "nvarchar", 11, 0, nullable: false),
			new DmoField("xafAPDiscountOnFreight", "bit", 1, 0, nullable: false),
			new DmoField("xafARIncludeFrgtInDepositCalc", "bit", 1, 0, nullable: false),
			new DmoField("xafUsePayPalProcessing", "bit", 1, 0, nullable: false),
			new DmoField("xafCreditCardMethod", "tinyint", 1, 0, nullable: false),
			new DmoField("xafARNET1GatewayID", "nvarchar", 20, 0, nullable: false),
			new DmoField("xafARNET1MerchantKey", "nvarchar", 20, 0, nullable: false),
			new DmoField("xafARNET1Port", "int", 6, 0, nullable: false),
			new DmoField("xafARNET1TimeoutSeconds", "smallint", 4, 0, nullable: false),
			new DmoField("xafAvalaraAccountID", "nvarchar", 50, 0, nullable: false),
			new DmoField("xafAvalaraURL", "nvarchar", 120, 0, nullable: false),
			new DmoField("xafAvalaraCompanyCode", "nvarchar", 50, 0, nullable: false),
			new DmoField("xafAvalaraLicenseKey", "nvarchar", 50, 0, nullable: false),
			new DmoField("xafAvalaraTimeoutSeconds", "smallint", 4, 0, nullable: false),
			new DmoField("xafAvalaraTaxCodeID", "nvarchar", 5, 0, nullable: false),
			new DmoField("xafAvalaraForceAddressValidate", "bit", 1, 0, nullable: false),
			new DmoField("xafAvalaraDisableAddrValidate", "bit", 1, 0, nullable: false),
			new DmoField("xafAvalaraFilterCountry", "tinyint", 1, 0, nullable: false),
			new DmoField("xafAvalaraARInvoicePostOption", "tinyint", 1, 0, nullable: false),
			new DmoField("xafAvalaraDisableIgnoreLine", "bit", 1, 0, nullable: false),
			new DmoField("xafMiscReceiptVarianceAccount", "tinyint", 1, 0, nullable: false),
			new DmoField("xafSuperExportFilePath", "nvarchar", 200, 0, nullable: false),
			new DmoField("xafAvalaraCanadaGSTTaxCodeID", "nvarchar", 5, 0, nullable: false),
			new DmoField("xafAvalaraCanadaPSTTaxCodeID", "nvarchar", 5, 0, nullable: false),
			new DmoField("xafAvalaraCanadaHSTTaxCodeID", "nvarchar", 5, 0, nullable: false),
			new DmoField("xafAvalaraCanadaQSTTaxCodeID", "nvarchar", 5, 0, nullable: false),
			new DmoField("xafSTPProduction", "bit", 1, 0, nullable: false),
			new DmoField("xafSTPSenderID", "nvarchar", 50, 0, nullable: true),
			new DmoField("xafSTPPassword", "nvarchar", 50, 0, nullable: true),
			new DmoField("xafSTPProjectKey", "nvarchar", 50, 0, nullable: true),
			new DmoField("xafSTPDatastoreKey", "nvarchar", 50, 0, nullable: true),
			new DmoField("xafSTPMessageXchangeURI", "nvarchar", 200, 0, nullable: true),
			new DmoField("xafSTPTestMessageXchangeURI", "nvarchar", 200, 0, nullable: true)
		}, new DmoIndex[2]
		{
			new DmoIndex("XAFUNIQUEID", unique: true),
			new DmoIndex("xafPOSShowCustSelector", unique: false)
		}, mergeCustomFields: true, disableTriggers: true);
	}
}
