using M1.Core;

namespace M1.Ax.Erp.DD;

[DBConversion("8.10.050", "Convert ARRecurringInvoices to support unicode", "2013-10-17")]
public class v810RebuildARRecurringInvoices
{
	public v810RebuildARRecurringInvoices(DBConversionParms parms)
	{
		parms.Dmo.RebuildTable(null, parms.User, parms.DataDictionary, parms.DatabaseName, "ARRecurringInvoices", new DmoField[75]
		{
			new DmoField("arrARRecurringInvoiceID", "int", 6, 0, nullable: false),
			new DmoField("arrARInvoiceType", "tinyint", 1, 0, nullable: false),
			new DmoField("arrCustomerOrganizationID", "nvarchar", 10, 0, nullable: false),
			new DmoField("arrARInvoiceLocationID", "nvarchar", 5, 0, nullable: false),
			new DmoField("arrARInvoiceContactID", "nvarchar", 5, 0, nullable: false),
			new DmoField("arrShipOrganizationID", "nvarchar", 10, 0, nullable: false),
			new DmoField("arrShipLocationID", "nvarchar", 5, 0, nullable: false),
			new DmoField("arrShipContactID", "nvarchar", 5, 0, nullable: false),
			new DmoField("arrCycleCode", "nvarchar", 5, 0, nullable: false),
			new DmoField("arrRecurrenceType", "nvarchar", 1, 0, nullable: false),
			new DmoField("arrInvoiceDay", "tinyint", 2, 0, nullable: false),
			new DmoField("arrStartGLFiscalYearID", "smallint", 4, 0, nullable: false),
			new DmoField("arrStartGLFiscalYearPeriodID", "tinyint", 2, 0, nullable: false),
			new DmoField("arrEndGLFiscalYearID", "smallint", 4, 0, nullable: false),
			new DmoField("arrEndGLFiscalYearPeriodID", "tinyint", 2, 0, nullable: false),
			new DmoField("arrLastTransferredDate", "date", 14, 0, nullable: true),
			new DmoField("arrPaymentTermID", "nvarchar", 5, 0, nullable: false),
			new DmoField("arrStandardMessageID", "nvarchar", 10, 0, nullable: false),
			new DmoField("arrInvoiceCommentsRTF", "nvarchar(max)", 50, 0, nullable: true),
			new DmoField("arrInvoiceCommentsText", "nvarchar(max)", 50, 0, nullable: true),
			new DmoField("arrShippingMethodID", "nvarchar", 5, 0, nullable: false),
			new DmoField("arrShippingPaymentTypeID", "nvarchar", 5, 0, nullable: false),
			new DmoField("arrCurrencyRateID", "nvarchar", 5, 0, nullable: false),
			new DmoField("arrCustomRate", "bit", 1, 0, nullable: false),
			new DmoField("arrExchangeRate", "numeric", 13, 6, nullable: false),
			new DmoField("arrFullInvoiceSubtotalBase", "money", 12, 2, nullable: false),
			new DmoField("arrFullInvoiceSubtotalForeign", "money", 12, 2, nullable: false),
			new DmoField("arrDiscountTotalBase", "money", 12, 2, nullable: false),
			new DmoField("arrDiscountTotalForeign", "money", 12, 2, nullable: false),
			new DmoField("arrInvoiceSubtotalBase", "money", 12, 2, nullable: false),
			new DmoField("arrInvoiceSubtotalForeign", "money", 12, 2, nullable: false),
			new DmoField("arrFreightSubtotalBase", "money", 12, 2, nullable: false),
			new DmoField("arrFreightSubtotalForeign", "money", 12, 2, nullable: false),
			new DmoField("arrFreightAmountBase", "money", 12, 2, nullable: false),
			new DmoField("arrFreightAmountForeign", "money", 12, 2, nullable: false),
			new DmoField("arrFreightTotalBase", "money", 12, 2, nullable: false),
			new DmoField("arrFreightTotalForeign", "money", 12, 2, nullable: false),
			new DmoField("arrFreightTaxCodeID", "nvarchar", 5, 0, nullable: false),
			new DmoField("arrFreightTaxAmountBase", "money", 14, 4, nullable: false),
			new DmoField("arrFreightTaxAmountForeign", "money", 14, 4, nullable: false),
			new DmoField("arrSecondFreightTaxCodeID", "nvarchar", 5, 0, nullable: false),
			new DmoField("arrSecondFreightTaxAmtBase", "money", 14, 4, nullable: false),
			new DmoField("arrSecondFreightTaxAmtForeign", "money", 14, 4, nullable: false),
			new DmoField("arrTaxSubtotalBase", "money", 12, 2, nullable: false),
			new DmoField("arrTaxSubtotalForeign", "money", 12, 2, nullable: false),
			new DmoField("arrInvoiceTaxAmountBase", "money", 12, 2, nullable: false),
			new DmoField("arrInvoiceTaxAmountForeign", "money", 12, 2, nullable: false),
			new DmoField("arrInvoiceTotalBase", "money", 12, 2, nullable: false),
			new DmoField("arrInvoiceTotalForeign", "money", 12, 2, nullable: false),
			new DmoField("arrARGLAccountID", "nvarchar", 11, 0, nullable: false),
			new DmoField("arrSalesGLAccountID", "nvarchar", 11, 0, nullable: false),
			new DmoField("arrFreightGLAccountID", "nvarchar", 11, 0, nullable: false),
			new DmoField("arrDiscountGLAccountID", "nvarchar", 11, 0, nullable: false),
			new DmoField("arrResellerOrganizationID", "nvarchar", 10, 0, nullable: false),
			new DmoField("arrResellerLocationID", "nvarchar", 5, 0, nullable: false),
			new DmoField("arrResellerContactID", "nvarchar", 5, 0, nullable: false),
			new DmoField("arrResellerCommissionRate", "numeric", 5, 2, nullable: false),
			new DmoField("arrTotalForResellerCommission", "money", 12, 2, nullable: false),
			new DmoField("arrResellerCommissionAmount", "money", 12, 2, nullable: false),
			new DmoField("arrTotalForSalesCommission", "money", 12, 2, nullable: false),
			new DmoField("arrLineCommissionTotal", "money", 12, 2, nullable: false),
			new DmoField("arrSalesCommissionTotal", "money", 12, 2, nullable: false),
			new DmoField("arrCommissionAmountBase", "money", 12, 2, nullable: false),
			new DmoField("arrSplitPercentTotal", "numeric", 6, 2, nullable: false),
			new DmoField("arrFreeOnBoardDescription", "nvarchar", 15, 0, nullable: false),
			new DmoField("arrIncludeFreightInPrice", "bit", 1, 0, nullable: false),
			new DmoField("arrPlantID", "nvarchar", 5, 0, nullable: false),
			new DmoField("arrPlantDepartmentID", "nvarchar", 5, 0, nullable: false),
			new DmoField("arrProjectID", "nvarchar", 10, 0, nullable: false),
			new DmoField("arrDescription", "nvarchar", 50, 0, nullable: false),
			new DmoField("arrInactive", "bit", 1, 0, nullable: false),
			new DmoField("arrInactiveDate", "date", 14, 0, nullable: true),
			new DmoField("arrCreatedBy", "nvarchar", 20, 0, nullable: false),
			new DmoField("arrCreatedDate", "datetime", 14, 0, nullable: true),
			new DmoField("arrUniqueID", "uniqueidentifier", 16, 0, nullable: false)
		}, new DmoIndex[13]
		{
			new DmoIndex("ARRARRECURRINGINVOICEID", unique: true),
			new DmoIndex("ARRUNIQUEID", unique: true),
			new DmoIndex("arrARInvoiceType", unique: false),
			new DmoIndex("arrCustomerOrganizationID", unique: false),
			new DmoIndex("arrARInvoiceLocationID", unique: false),
			new DmoIndex("arrShipOrganizationID", unique: false),
			new DmoIndex("arrShipLocationID", unique: false),
			new DmoIndex("arrRecurrenceType", unique: false),
			new DmoIndex("arrResellerOrganizationID", unique: false),
			new DmoIndex("arrPlantID", unique: false),
			new DmoIndex("arrPlantDepartmentID", unique: false),
			new DmoIndex("arrProjectID", unique: false),
			new DmoIndex("arrInactive", unique: false)
		}, mergeCustomFields: true, disableTriggers: true);
	}
}
