using M1.Core;

namespace M1.Ax.Erp.DD;

[DBConversion("8.10.050", "Convert SerialNumberTransactions to support unicode", "2013-10-17")]
public class v810RebuildSerialNumberTransactions
{
	public v810RebuildSerialNumberTransactions(DBConversionParms parms)
	{
		parms.Dmo.RebuildTable(null, parms.User, parms.DataDictionary, parms.DatabaseName, "SerialNumberTransactions", new DmoField[45]
		{
			new DmoField("sntPartID", "nvarchar", 30, 0, nullable: false),
			new DmoField("sntPartRevisionID", "nvarchar", 15, 0, nullable: false),
			new DmoField("sntSerialNumberID", "nvarchar", 30, 0, nullable: false),
			new DmoField("sntSerialNumberTransactionID", "int", 4, 0, nullable: false),
			new DmoField("sntTransactionType", "tinyint", 2, 0, nullable: false),
			new DmoField("sntTransactionDate", "datetime", 14, 0, nullable: true),
			new DmoField("sntPartWarehouseLocationID", "nvarchar", 5, 0, nullable: false),
			new DmoField("sntPartBinID", "nvarchar", 15, 0, nullable: false),
			new DmoField("sntStatus", "tinyint", 2, 0, nullable: false),
			new DmoField("sntJobID", "nvarchar", 20, 0, nullable: false),
			new DmoField("sntJobAssemblyID", "int", 5, 0, nullable: false),
			new DmoField("sntJobMaterialID", "int", 5, 0, nullable: false),
			new DmoField("sntPartTransactionID", "int", 9, 0, nullable: false),
			new DmoField("sntReceiptID", "nvarchar", 10, 0, nullable: false),
			new DmoField("sntReceiptLineID", "smallint", 4, 0, nullable: false),
			new DmoField("sntShipmentID", "nvarchar", 10, 0, nullable: false),
			new DmoField("sntShipmentLineID", "smallint", 4, 0, nullable: false),
			new DmoField("sntInventoryCountID", "int", 9, 0, nullable: false),
			new DmoField("sntInventoryCountLineID", "int", 7, 0, nullable: false),
			new DmoField("sntNegativeTransaction", "bit", 1, 0, nullable: false),
			new DmoField("sntDMRShipmentID", "nvarchar", 10, 0, nullable: false),
			new DmoField("sntDMRShipmentLineID", "smallint", 4, 0, nullable: false),
			new DmoField("sntRMAReceiptID", "nvarchar", 10, 0, nullable: false),
			new DmoField("sntRMAReceiptLineID", "smallint", 4, 0, nullable: false),
			new DmoField("sntWarehouseTransferID", "nvarchar", 10, 0, nullable: false),
			new DmoField("sntWarehouseTransferLineID", "smallint", 4, 0, nullable: false),
			new DmoField("sntWarehouseReceiptID", "nvarchar", 10, 0, nullable: false),
			new DmoField("sntWarehouseReceiptLineID", "smallint", 4, 0, nullable: false),
			new DmoField("sntPOSTransactionID", "nvarchar", 10, 0, nullable: false),
			new DmoField("sntPOSTransactionLineID", "smallint", 4, 0, nullable: false),
			new DmoField("sntInspectionID", "nvarchar", 10, 0, nullable: false),
			new DmoField("sntInspectionLineID", "smallint", 4, 0, nullable: false),
			new DmoField("sntInspect", "bit", 1, 0, nullable: false),
			new DmoField("sntQualityRegisterID", "nvarchar", 10, 0, nullable: false),
			new DmoField("sntLandedCostID", "nvarchar", 10, 0, nullable: false),
			new DmoField("sntJobPartID", "nvarchar", 30, 0, nullable: false),
			new DmoField("sntJobPartRevisionID", "nvarchar", 15, 0, nullable: false),
			new DmoField("sntJobPartWarehouseLocationID", "nvarchar", 5, 0, nullable: false),
			new DmoField("sntJobPartBinID", "nvarchar", 15, 0, nullable: false),
			new DmoField("sntJobSerialNumberID", "nvarchar", 30, 0, nullable: false),
			new DmoField("sntTableName", "nvarchar", 30, 0, nullable: false),
			new DmoField("sntTableUniqueID", "uniqueidentifier", 16, 0, nullable: false),
			new DmoField("sntCreatedBy", "nvarchar", 20, 0, nullable: false),
			new DmoField("sntCreatedDate", "datetime", 14, 0, nullable: true),
			new DmoField("sntUniqueID", "uniqueidentifier", 16, 0, nullable: false)
		}, new DmoIndex[36]
		{
			new DmoIndex("SNTPARTID,SNTPARTREVISIONID,SNTSERIALNUMBERID,SNTSERIALNUMBERTRANSACTIONID", unique: true),
			new DmoIndex("SNTUNIQUEID", unique: true),
			new DmoIndex("sntPartID", unique: false),
			new DmoIndex("sntPartRevisionID", unique: false),
			new DmoIndex("sntSerialNumberID", unique: false),
			new DmoIndex("sntSerialNumberTransactionID", unique: false),
			new DmoIndex("sntTransactionType", unique: false),
			new DmoIndex("sntPartWarehouseLocationID", unique: false),
			new DmoIndex("sntPartBinID", unique: false),
			new DmoIndex("sntStatus", unique: false),
			new DmoIndex("sntJobID", unique: false),
			new DmoIndex("sntJobAssemblyID", unique: false),
			new DmoIndex("sntJobMaterialID", unique: false),
			new DmoIndex("sntPartTransactionID", unique: false),
			new DmoIndex("sntReceiptID", unique: false),
			new DmoIndex("sntReceiptLineID", unique: false),
			new DmoIndex("sntShipmentID", unique: false),
			new DmoIndex("sntShipmentLineID", unique: false),
			new DmoIndex("sntInventoryCountID", unique: false),
			new DmoIndex("sntInventoryCountLineID", unique: false),
			new DmoIndex("sntDMRShipmentID", unique: false),
			new DmoIndex("sntDMRShipmentLineID", unique: false),
			new DmoIndex("sntRMAReceiptID", unique: false),
			new DmoIndex("sntRMAReceiptLineID", unique: false),
			new DmoIndex("sntWarehouseTransferID", unique: false),
			new DmoIndex("sntWarehouseTransferLineID", unique: false),
			new DmoIndex("sntWarehouseReceiptID", unique: false),
			new DmoIndex("sntWarehouseReceiptLineID", unique: false),
			new DmoIndex("sntPOSTransactionID", unique: false),
			new DmoIndex("sntPOSTransactionLineID", unique: false),
			new DmoIndex("sntInspectionID", unique: false),
			new DmoIndex("sntInspectionLineID", unique: false),
			new DmoIndex("sntQualityRegisterID", unique: false),
			new DmoIndex("sntLandedCostID", unique: false),
			new DmoIndex("sntTableName", unique: false),
			new DmoIndex("sntTableUniqueID", unique: false)
		}, mergeCustomFields: true, disableTriggers: true);
	}
}
