using M1.Core;

namespace M1.Ax.Erp.DD;

[DBConversion("8.10.050", "Convert Organizations to support unicode", "2013-10-17")]
public class v810RebuildOrganizations
{
	public v810RebuildOrganizations(DBConversionParms parms)
	{
		parms.ServerManager.ExecuteCommand(null, parms.User, parms.DatabaseName, "Update Organizations Set cmoForm1099Box = 0 Where cmoForm1099Box = -1");
		parms.Dmo.RebuildTable(null, parms.User, parms.DataDictionary, parms.DatabaseName, "Organizations", new DmoField[130]
		{
			new DmoField("cmoOrganizationID", "nvarchar", 10, 0, nullable: false),
			new DmoField("cmoName", "nvarchar", 50, 0, nullable: false),
			new DmoField("cmoAddressLine1", "nvarchar", 50, 0, nullable: false),
			new DmoField("cmoAddressLine2", "nvarchar", 50, 0, nullable: false),
			new DmoField("cmoAddressLine3", "nvarchar", 50, 0, nullable: false),
			new DmoField("cmoCity", "nvarchar", 30, 0, nullable: false),
			new DmoField("cmoCounty", "nvarchar", 30, 0, nullable: false),
			new DmoField("cmoState", "nvarchar", 3, 0, nullable: false),
			new DmoField("cmoPostCode", "nvarchar", 10, 0, nullable: false),
			new DmoField("cmoCountry", "nvarchar", 20, 0, nullable: false),
			new DmoField("cmoPhoneNumber", "nvarchar", 20, 0, nullable: false),
			new DmoField("cmoAlternatePhoneNumber", "nvarchar", 20, 0, nullable: false),
			new DmoField("cmoFaxNumber", "nvarchar", 20, 0, nullable: false),
			new DmoField("cmoEMailAddress", "nvarchar(max)", 50, 0, nullable: true),
			new DmoField("cmoWebAddress", "nvarchar", 50, 0, nullable: false),
			new DmoField("cmoOrganizationAccountID", "nvarchar", 20, 0, nullable: false),
			new DmoField("cmoARInvoiceContactID", "nvarchar", 5, 0, nullable: false),
			new DmoField("cmoQuoteContactID", "nvarchar", 5, 0, nullable: false),
			new DmoField("cmoShipContactID", "nvarchar", 5, 0, nullable: false),
			new DmoField("cmoPurchaseContactID", "nvarchar", 5, 0, nullable: false),
			new DmoField("cmoEstablishedDate", "date", 14, 0, nullable: true),
			new DmoField("cmoAPInvoiceContactID", "nvarchar", 5, 0, nullable: false),
			new DmoField("cmoPrintStatement", "bit", 1, 0, nullable: false),
			new DmoField("cmoEmployeeCount", "int", 6, 0, nullable: false),
			new DmoField("cmoFinanceCompany", "bit", 1, 0, nullable: false),
			new DmoField("cmoCompetitor", "bit", 1, 0, nullable: false),
			new DmoField("cmoLongDescriptionRTF", "nvarchar(max)", 50, 0, nullable: true),
			new DmoField("cmoLongDescriptionText", "nvarchar(max)", 50, 0, nullable: true),
			new DmoField("cmoCustomerStatus", "tinyint", 1, 0, nullable: false),
			new DmoField("cmoCustomerProspectDate", "date", 14, 0, nullable: true),
			new DmoField("cmoCustomerActiveDate", "date", 14, 0, nullable: true),
			new DmoField("cmoCustomerInactiveDate", "date", 14, 0, nullable: true),
			new DmoField("cmoSupplierStatus", "tinyint", 1, 0, nullable: false),
			new DmoField("cmoSupplierProspectDate", "date", 14, 0, nullable: true),
			new DmoField("cmoSupplierActiveDate", "date", 14, 0, nullable: true),
			new DmoField("cmoSupplierInactiveDate", "date", 14, 0, nullable: true),
			new DmoField("cmoRequires1099", "bit", 1, 0, nullable: false),
			new DmoField("cmoSupplierPaymentTermID", "nvarchar", 5, 0, nullable: false),
			new DmoField("cmoSupplierShippingMethodID", "nvarchar", 5, 0, nullable: false),
			new DmoField("cmoSupplierTaxable", "bit", 1, 0, nullable: false),
			new DmoField("cmoSupplierTaxCodeID", "nvarchar", 5, 0, nullable: false),
			new DmoField("cmoSupplierSecondTaxCodeID", "nvarchar", 5, 0, nullable: false),
			new DmoField("cmoAccountManagerEmployeeID", "nvarchar", 10, 0, nullable: false),
			new DmoField("cmoCustomerGroupID", "nvarchar", 5, 0, nullable: false),
			new DmoField("cmoCustomerTaxable", "bit", 1, 0, nullable: false),
			new DmoField("cmoCustomerTaxCodeID", "nvarchar", 5, 0, nullable: false),
			new DmoField("cmoCustomerSecondTaxCodeID", "nvarchar", 5, 0, nullable: false),
			new DmoField("cmoCustomerPaymentTermsID", "nvarchar", 5, 0, nullable: false),
			new DmoField("cmoCalculateFinanceCharges", "bit", 1, 0, nullable: false),
			new DmoField("cmoIncludeFreightInPrice", "bit", 1, 0, nullable: false),
			new DmoField("cmoCurrencyRateID", "nvarchar", 5, 0, nullable: false),
			new DmoField("cmoCreditHold", "bit", 1, 0, nullable: false),
			new DmoField("cmoCustomerCreditLimit", "money", 12, 2, nullable: false),
			new DmoField("cmoDefaultQuoteLocationID", "nvarchar", 5, 0, nullable: false),
			new DmoField("cmoDefaultShipLocationID", "nvarchar", 5, 0, nullable: false),
			new DmoField("cmoDefaultARInvoiceLocationID", "nvarchar", 5, 0, nullable: false),
			new DmoField("cmoDefaultPurchaseLocationID", "nvarchar", 5, 0, nullable: false),
			new DmoField("cmoDefaultAPInvoiceLocationID", "nvarchar", 5, 0, nullable: false),
			new DmoField("cmoDropShipOrganizationID", "nvarchar", 10, 0, nullable: false),
			new DmoField("cmoDropShipLocationID", "nvarchar", 5, 0, nullable: false),
			new DmoField("cmoEFTDescription", "nvarchar", 20, 0, nullable: false),
			new DmoField("cmoTaxExemptNumber", "nvarchar", 16, 0, nullable: false),
			new DmoField("cmoDirectPayment", "bit", 1, 0, nullable: false),
			new DmoField("cmoFederalID", "nvarchar", 20, 0, nullable: false),
			new DmoField("cmoBankInitials", "nvarchar", 3, 0, nullable: false),
			new DmoField("cmoBSBNumber", "nvarchar", 10, 0, nullable: false),
			new DmoField("cmoBankAccountName", "nvarchar", 50, 0, nullable: false),
			new DmoField("cmoBankAccountNumber", "nvarchar", 20, 0, nullable: false),
			new DmoField("cmoNonTaxReasonID", "nvarchar", 5, 0, nullable: false),
			new DmoField("cmoCustomerShippingMethodID", "nvarchar", 5, 0, nullable: false),
			new DmoField("cmoJobPriorityID", "tinyint", 2, 0, nullable: false),
			new DmoField("cmoCustomerShipPaymentTypeID", "nvarchar", 5, 0, nullable: false),
			new DmoField("cmoARInvoicePerShipmentLine", "bit", 1, 0, nullable: false),
			new DmoField("cmoCreatedFromWeb", "bit", 1, 0, nullable: false),
			new DmoField("cmoResellerStatus", "tinyint", 1, 0, nullable: false),
			new DmoField("cmoResellerProspectDate", "date", 14, 0, nullable: true),
			new DmoField("cmoResellerActiveDate", "date", 14, 0, nullable: true),
			new DmoField("cmoResellerInactiveDate", "date", 14, 0, nullable: true),
			new DmoField("cmoResellerOrganizationID", "nvarchar", 10, 0, nullable: false),
			new DmoField("cmoResellerLocationID", "nvarchar", 5, 0, nullable: false),
			new DmoField("cmoResellerContactID", "nvarchar", 5, 0, nullable: false),
			new DmoField("cmoResellerCommissionRate", "numeric", 5, 2, nullable: false),
			new DmoField("cmoRequiresInspection", "bit", 1, 0, nullable: false),
			new DmoField("cmoUPSAcctNumber", "nvarchar", 6, 0, nullable: false),
			new DmoField("cmoUPSBillingOption", "nvarchar", 20, 0, nullable: false),
			new DmoField("cmoResidentialAddress", "bit", 1, 0, nullable: false),
			new DmoField("cmoAttachmentFileFolder", "nvarchar(max)", 50, 0, nullable: true),
			new DmoField("cmoSupplierAccredited", "bit", 1, 0, nullable: false),
			new DmoField("cmoSupplierAccreditedDate", "date", 14, 0, nullable: true),
			new DmoField("cmoSupplierRatingID", "nvarchar", 5, 0, nullable: false),
			new DmoField("cmoBankAccountType", "nvarchar", 2, 0, nullable: false),
			new DmoField("cmoFreeOnBoardDescription", "nvarchar", 15, 0, nullable: false),
			new DmoField("cmoCreatedBy", "nvarchar", 20, 0, nullable: false),
			new DmoField("cmoCreatedDate", "datetime", 14, 0, nullable: true),
			new DmoField("cmoUniqueID", "uniqueidentifier", 16, 0, nullable: false),
			new DmoField("cmoCountryCode", "nvarchar", 2, 0, nullable: false),
			new DmoField("cmoHDAttachmentFilePath", "nvarchar(max)", 50, 0, nullable: true),
			new DmoField("cmoAPIncludeTaxInRetention", "bit", 1, 0, nullable: false),
			new DmoField("cmoARIncludeTaxInRetention", "bit", 1, 0, nullable: false),
			new DmoField("cmoUPS3rdPartyOrganizationID", "nvarchar", 10, 0, nullable: false),
			new DmoField("cmoUPS3rdPartyLocationID", "nvarchar", 5, 0, nullable: false),
			new DmoField("cmoForm1099Box", "tinyint", 2, 0, nullable: false),
			new DmoField("cmoEFTCode", "nvarchar", 12, 0, nullable: false),
			new DmoField("cmoEFTParticulars", "nvarchar", 12, 0, nullable: false),
			new DmoField("cmoAvalaraUseCodes", "nvarchar", 1, 0, nullable: false),
			new DmoField("cmoAvalaraAddressValidated", "bit", 1, 0, nullable: false),
			new DmoField("cmoContractor", "bit", 1, 0, nullable: false),
			new DmoField("cmoTaxReportable", "bit", 1, 0, nullable: false),
			new DmoField("cmoLastName", "nvarchar", 30, 0, nullable: false),
			new DmoField("cmoFirstGivenName", "nvarchar", 15, 0, nullable: false),
			new DmoField("cmoSecondGivenName", "nvarchar", 15, 0, nullable: false),
			new DmoField("cmoTradingName", "nvarchar(max)", 50, 0, nullable: true),
			new DmoField("cmoCreatedFromMobile", "bit", 1, 0, nullable: false),
			new DmoField("cmoIgnoreAvalara", "bit", 1, 0, nullable: false),
			new DmoField("cmoSuperFund", "bit", 1, 0, nullable: false),
			new DmoField("cmoSuperFundID", "nvarchar", 50, 0, nullable: false),
			new DmoField("cmoSuperFundName", "nvarchar", 60, 0, nullable: false),
			new DmoField("cmoSuperFundEmployerID", "nvarchar", 16, 0, nullable: false),
			new DmoField("cmoSuperClearingHouse", "bit", 1, 0, nullable: false),
			new DmoField("cmoUPSValidated", "bit", 1, 0, nullable: false),
			new DmoField("cmoBareCostOfDuty", "bit", 1, 0, nullable: false),
			new DmoField("cmoBareTransportationCost", "bit", 1, 0, nullable: false),
			new DmoField("cmoEDIIntegrated", "bit", 1, 0, nullable: false),
			new DmoField("cmoFedExAccountNumber", "nvarchar", 15, 0, nullable: false),
			new DmoField("cmoFedEx3rdPartyOrganizationID", "nvarchar", 10, 0, nullable: false),
			new DmoField("cmoFedEx3rdPartyLocationID", "nvarchar", 5, 0, nullable: false),
			new DmoField("cmoFedExBillingOption", "nvarchar", 20, 0, nullable: false),
			new DmoField("cmoIBAN", "nvarchar", 50, 0, nullable: false),
			new DmoField("cmoBIC", "nvarchar", 50, 0, nullable: false),
			new DmoField("cmoUPSWSBillingOption", "nvarchar", 20, 0, nullable: false)
		}, new DmoIndex[12]
		{
			new DmoIndex("CMOORGANIZATIONID", unique: true),
			new DmoIndex("CMOUNIQUEID", unique: true),
			new DmoIndex("cmoName", unique: false),
			new DmoIndex("cmoPrintStatement", unique: false),
			new DmoIndex("cmoFinanceCompany", unique: false),
			new DmoIndex("cmoCompetitor", unique: false),
			new DmoIndex("cmoCustomerStatus", unique: false),
			new DmoIndex("cmoSupplierStatus", unique: false),
			new DmoIndex("cmoRequires1099", unique: false),
			new DmoIndex("cmoDropShipOrganizationID", unique: false),
			new DmoIndex("cmoResellerOrganizationID", unique: false),
			new DmoIndex("cmoSupplierRatingID", unique: false)
		}, mergeCustomFields: true, disableTriggers: true);
	}
}
