using M1.Core;

namespace M1.Ax.Erp.DD;

[DBConversion("8.10.050", "Convert Jobs to support unicode", "2013-10-17")]
public class v810RebuildJobs
{
	public v810RebuildJobs(DBConversionParms parms)
	{
		parms.Dmo.RebuildTable(null, parms.User, parms.DataDictionary, parms.DatabaseName, "Jobs", new DmoField[63]
		{
			new DmoField("jmpJobID", "nvarchar", 20, 0, nullable: false),
			new DmoField("jmpPlantDepartmentID", "nvarchar", 5, 0, nullable: false),
			new DmoField("jmpPlantID", "nvarchar", 5, 0, nullable: false),
			new DmoField("jmpProductionDueDate", "date", 14, 0, nullable: true),
			new DmoField("jmpCustomerOrganizationID", "nvarchar", 10, 0, nullable: false),
			new DmoField("jmpJobDate", "date", 14, 0, nullable: true),
			new DmoField("jmpPartID", "nvarchar", 30, 0, nullable: false),
			new DmoField("jmpPartRevisionID", "nvarchar", 15, 0, nullable: false),
			new DmoField("jmpPartWareHouseLocationID", "nvarchar", 5, 0, nullable: false),
			new DmoField("jmpPartBinID", "nvarchar", 15, 0, nullable: false),
			new DmoField("jmpCallID", "nvarchar", 10, 0, nullable: false),
			new DmoField("jmpUnitOfMeasure", "nvarchar", 2, 0, nullable: false),
			new DmoField("jmpPartShortDescription", "nvarchar", 50, 0, nullable: false),
			new DmoField("jmpPartLongDescriptionRTF", "nvarchar(max)", 50, 0, nullable: true),
			new DmoField("jmpPartLongDescriptionText", "nvarchar(max)", 50, 0, nullable: true),
			new DmoField("jmpOrderQuantity", "numeric", 15, 5, nullable: false),
			new DmoField("jmpInventoryQuantity", "numeric", 15, 5, nullable: false),
			new DmoField("jmpScrapQuantity", "numeric", 15, 5, nullable: false),
			new DmoField("jmpReworkQuantity", "numeric", 15, 5, nullable: false),
			new DmoField("jmpReworkDate", "datetime", 14, 0, nullable: true),
			new DmoField("jmpProductionQuantity", "numeric", 15, 5, nullable: false),
			new DmoField("jmpScheduledStartDate", "date", 14, 0, nullable: true),
			new DmoField("jmpScheduledStartHour", "numeric", 5, 2, nullable: false),
			new DmoField("jmpScheduledDueDate", "date", 14, 0, nullable: true),
			new DmoField("jmpScheduledDueHour", "numeric", 5, 2, nullable: false),
			new DmoField("jmpFirm", "bit", 1, 0, nullable: false),
			new DmoField("jmpJobPriorityID", "tinyint", 2, 0, nullable: false),
			new DmoField("jmpTimeAndMaterial", "bit", 1, 0, nullable: false),
			new DmoField("jmpPlanningComplete", "bit", 1, 0, nullable: false),
			new DmoField("jmpPlannerEmployeeID", "nvarchar", 10, 0, nullable: false),
			new DmoField("jmpScheduleComplete", "bit", 1, 0, nullable: false),
			new DmoField("jmpScheduleLocked", "bit", 1, 0, nullable: false),
			new DmoField("jmpReleasedToFloor", "bit", 1, 0, nullable: false),
			new DmoField("jmpOnHold", "bit", 1, 0, nullable: false),
			new DmoField("jmpReadyToPrint", "bit", 1, 0, nullable: false),
			new DmoField("jmpProductionComplete", "bit", 1, 0, nullable: false),
			new DmoField("jmpQuantityCompleted", "numeric", 15, 5, nullable: false),
			new DmoField("jmpCompletedDate", "date", 14, 0, nullable: true),
			new DmoField("jmpQuantityShipped", "numeric", 15, 5, nullable: false),
			new DmoField("jmpQuantityReceivedToInventory", "numeric", 15, 5, nullable: false),
			new DmoField("jmpQuoteID", "nvarchar", 10, 0, nullable: false),
			new DmoField("jmpQuoteLineID", "smallint", 4, 0, nullable: false),
			new DmoField("jmpSourceMethodID", "nvarchar", 30, 0, nullable: false),
			new DmoField("jmpSourceRevisionID", "nvarchar", 15, 0, nullable: false),
			new DmoField("jmpRMAClaimID", "nvarchar", 10, 0, nullable: false),
			new DmoField("jmpRMAClaimLineID", "smallint", 4, 0, nullable: false),
			new DmoField("jmpRMAClaimProblemID", "smallint", 4, 0, nullable: false),
			new DmoField("jmpProjectID", "nvarchar", 10, 0, nullable: false),
			new DmoField("jmpProductionNotesRTF", "nvarchar(max)", 50, 0, nullable: true),
			new DmoField("jmpProductionNotesText", "nvarchar(max)", 50, 0, nullable: true),
			new DmoField("jmpDocuments", "nvarchar(max)", 50, 0, nullable: true),
			new DmoField("jmpClosed", "bit", 1, 0, nullable: false),
			new DmoField("jmpClosedDate", "date", 14, 0, nullable: true),
			new DmoField("jmpProjectAreaID", "nvarchar", 15, 0, nullable: false),
			new DmoField("jmpScrapQuantityCompleted", "numeric", 15, 5, nullable: false),
			new DmoField("jmpShipOrganizationID", "nvarchar", 10, 0, nullable: false),
			new DmoField("jmpNonConformanceID", "nvarchar", 10, 0, nullable: false),
			new DmoField("jmpShipLocationID", "nvarchar", 5, 0, nullable: false),
			new DmoField("jmpPartForecastYearID", "smallint", 4, 0, nullable: false),
			new DmoField("jmpPartForecastPeriodID", "smallint", 4, 0, nullable: false),
			new DmoField("jmpCreatedBy", "nvarchar", 20, 0, nullable: false),
			new DmoField("jmpCreatedDate", "datetime", 14, 0, nullable: true),
			new DmoField("jmpUniqueID", "uniqueidentifier", 16, 0, nullable: false)
		}, new DmoIndex[28]
		{
			new DmoIndex("JMPJOBID", unique: true),
			new DmoIndex("JMPUNIQUEID", unique: true),
			new DmoIndex("jmpPlantDepartmentID", unique: false),
			new DmoIndex("jmpPlantID", unique: false),
			new DmoIndex("jmpProductionDueDate", unique: false),
			new DmoIndex("jmpCustomerOrganizationID", unique: false),
			new DmoIndex("jmpJobDate", unique: false),
			new DmoIndex("jmpPartID", unique: false),
			new DmoIndex("jmpPartRevisionID", unique: false),
			new DmoIndex("jmpPartWareHouseLocationID", unique: false),
			new DmoIndex("jmpPartBinID", unique: false),
			new DmoIndex("jmpCallID", unique: false),
			new DmoIndex("jmpScheduleLocked", unique: false),
			new DmoIndex("jmpReleasedToFloor", unique: false),
			new DmoIndex("jmpOnHold", unique: false),
			new DmoIndex("jmpReadyToPrint", unique: false),
			new DmoIndex("jmpProductionComplete", unique: false),
			new DmoIndex("jmpSourceMethodID", unique: false),
			new DmoIndex("jmpSourceRevisionID", unique: false),
			new DmoIndex("jmpRMAClaimID", unique: false),
			new DmoIndex("jmpRMAClaimLineID", unique: false),
			new DmoIndex("jmpRMAClaimProblemID", unique: false),
			new DmoIndex("jmpProjectID", unique: false),
			new DmoIndex("jmpClosed", unique: false),
			new DmoIndex("jmpProjectAreaID", unique: false),
			new DmoIndex("jmpShipOrganizationID", unique: false),
			new DmoIndex("jmpNonConformanceID", unique: false),
			new DmoIndex("jmpReworkDate", unique: false)
		}, mergeCustomFields: true, disableTriggers: true);
	}
}
