using M1.Core;

namespace M1.Ax.Erp.DD;

[DBConversion("8.10.050", "Convert RMAClaimLines to support unicode", "2013-10-17")]
public class v810RebuildRMAClaimLines
{
	public v810RebuildRMAClaimLines(DBConversionParms parms)
	{
		parms.Dmo.RebuildTable(null, parms.User, parms.DataDictionary, parms.DatabaseName, "RMAClaimLines", new DmoField[62]
		{
			new DmoField("ralRMAClaimID", "nvarchar", 10, 0, nullable: false),
			new DmoField("ralRMAClaimLineID", "smallint", 4, 0, nullable: false),
			new DmoField("ralPartID", "nvarchar", 30, 0, nullable: false),
			new DmoField("ralPartRevisionID", "nvarchar", 15, 0, nullable: false),
			new DmoField("ralPartWarehouseLocationID", "nvarchar", 5, 0, nullable: false),
			new DmoField("ralPartBinID", "nvarchar", 15, 0, nullable: false),
			new DmoField("ralPartGroupID", "nvarchar", 5, 0, nullable: false),
			new DmoField("ralPartShortDescription", "nvarchar", 50, 0, nullable: false),
			new DmoField("ralUnitOfMeasure", "nvarchar", 2, 0, nullable: false),
			new DmoField("ralQuantity", "numeric", 15, 5, nullable: false),
			new DmoField("ralUnitCost", "numeric", 15, 5, nullable: false),
			new DmoField("ralUnitPrice", "numeric", 15, 5, nullable: false),
			new DmoField("ralExtendedCost", "money", 12, 2, nullable: false),
			new DmoField("ralExtendedPrice", "money", 12, 2, nullable: false),
			new DmoField("ralActionType", "nvarchar", 5, 0, nullable: false),
			new DmoField("ralReturnToSupplier", "bit", 1, 0, nullable: false),
			new DmoField("ralReturnReasonID", "nvarchar", 5, 0, nullable: false),
			new DmoField("ralSupplierOrganizationID", "nvarchar", 10, 0, nullable: false),
			new DmoField("ralPurchaseLocationID", "nvarchar", 5, 0, nullable: false),
			new DmoField("ralSupplierAuthorizationNumber", "nvarchar", 20, 0, nullable: false),
			new DmoField("ralShippingMethodID", "nvarchar", 5, 0, nullable: false),
			new DmoField("ralTrackingNumber", "nvarchar", 30, 0, nullable: false),
			new DmoField("ralRequiredDate", "date", 14, 0, nullable: true),
			new DmoField("ralReturnedDate", "date", 14, 0, nullable: true),
			new DmoField("ralReceivedDate", "date", 14, 0, nullable: true),
			new DmoField("ralShippedDate", "date", 14, 0, nullable: true),
			new DmoField("ralInvoicedComplete", "bit", 1, 0, nullable: false),
			new DmoField("ralTransferredToSalesOrder", "bit", 1, 0, nullable: false),
			new DmoField("ralQuantityReceived", "numeric", 15, 5, nullable: false),
			new DmoField("ralReceivedComplete", "bit", 1, 0, nullable: false),
			new DmoField("ralQualityRegisterID", "nvarchar", 10, 0, nullable: false),
			new DmoField("ralProjectID", "nvarchar", 10, 0, nullable: false),
			new DmoField("ralProjectAreaID", "nvarchar", 15, 0, nullable: false),
			new DmoField("ralOrgPartID", "nvarchar", 30, 0, nullable: false),
			new DmoField("ralOrgPartShortDescription", "nvarchar", 50, 0, nullable: false),
			new DmoField("ralSupplierShippingMethodID", "nvarchar", 5, 0, nullable: false),
			new DmoField("ralSupplierTrackingNumber", "nvarchar", 30, 0, nullable: false),
			new DmoField("ralCustomerToPayForShipping", "bit", 1, 0, nullable: false),
			new DmoField("ralShippingPaymentTypeID", "nvarchar", 5, 0, nullable: false),
			new DmoField("ralPartLongDescriptionText", "nvarchar(max)", 50, 0, nullable: true),
			new DmoField("ralPartLongDescriptionRTF", "nvarchar(max)", 50, 0, nullable: true),
			new DmoField("ralShipmentID", "nvarchar", 10, 0, nullable: false),
			new DmoField("ralShipmentLineID", "smallint", 4, 0, nullable: false),
			new DmoField("ralSalesOrderID", "nvarchar", 10, 0, nullable: false),
			new DmoField("ralSalesOrderLineID", "smallint", 4, 0, nullable: false),
			new DmoField("ralSalesOrderDeliveryID", "smallint", 4, 0, nullable: false),
			new DmoField("ralUnitCostForeign", "numeric", 15, 5, nullable: false),
			new DmoField("ralUnitPriceForeign", "numeric", 15, 5, nullable: false),
			new DmoField("ralExtendedCostForeign", "money", 12, 2, nullable: false),
			new DmoField("ralExtendedPriceForeign", "money", 12, 2, nullable: false),
			new DmoField("ralFullUnitPriceBase", "numeric", 15, 5, nullable: false),
			new DmoField("ralFullUnitPriceForeign", "numeric", 15, 5, nullable: false),
			new DmoField("ralDiscountPercent", "numeric", 6, 2, nullable: false),
			new DmoField("ralUnitDiscountBase", "numeric", 15, 5, nullable: false),
			new DmoField("ralUnitDiscountForeign", "numeric", 15, 5, nullable: false),
			new DmoField("ralFullExtendedPriceBase", "money", 12, 2, nullable: false),
			new DmoField("ralFullExtendedPriceForeign", "money", 12, 2, nullable: false),
			new DmoField("ralExtendedDiscountBase", "money", 12, 2, nullable: false),
			new DmoField("ralExtendedDiscountForeign", "money", 12, 2, nullable: false),
			new DmoField("ralCreatedBy", "nvarchar", 20, 0, nullable: false),
			new DmoField("ralCreatedDate", "datetime", 14, 0, nullable: true),
			new DmoField("ralUniqueID", "uniqueidentifier", 16, 0, nullable: false)
		}, new DmoIndex[22]
		{
			new DmoIndex("RALRMACLAIMID,RALRMACLAIMLINEID", unique: true),
			new DmoIndex("RALUNIQUEID", unique: true),
			new DmoIndex("ralRMAClaimID", unique: false),
			new DmoIndex("ralRMAClaimLineID", unique: false),
			new DmoIndex("ralPartID", unique: false),
			new DmoIndex("ralPartRevisionID", unique: false),
			new DmoIndex("ralPartWarehouseLocationID", unique: false),
			new DmoIndex("ralPartBinID", unique: false),
			new DmoIndex("ralPartGroupID", unique: false),
			new DmoIndex("ralReturnReasonID", unique: false),
			new DmoIndex("ralSupplierOrganizationID", unique: false),
			new DmoIndex("ralPurchaseLocationID", unique: false),
			new DmoIndex("ralInvoicedComplete", unique: false),
			new DmoIndex("ralQualityRegisterID", unique: false),
			new DmoIndex("ralProjectID", unique: false),
			new DmoIndex("ralProjectAreaID", unique: false),
			new DmoIndex("ralOrgPartID", unique: false),
			new DmoIndex("ralShipmentID", unique: false),
			new DmoIndex("ralShipmentLineID", unique: false),
			new DmoIndex("ralSalesOrderID", unique: false),
			new DmoIndex("ralSalesOrderLineID", unique: false),
			new DmoIndex("ralSalesOrderDeliveryID", unique: false)
		}, mergeCustomFields: true, disableTriggers: true);
	}
}
