using M1.Core;

namespace M1.Ax.Erp.DD;

[DBConversion("8.10.050", "Convert JobOperations to support unicode", "2013-10-17")]
public class v810RebuildJobOperations
{
	public v810RebuildJobOperations(DBConversionParms parms)
	{
		parms.Dmo.RebuildTable(null, parms.User, parms.DataDictionary, parms.DatabaseName, "JobOperations", new DmoField[89]
		{
			new DmoField("jmoJobID", "nvarchar", 20, 0, nullable: false),
			new DmoField("jmoJobAssemblyID", "int", 5, 0, nullable: false),
			new DmoField("jmoJobOperationID", "int", 5, 0, nullable: false),
			new DmoField("jmoOperationType", "tinyint", 1, 0, nullable: false),
			new DmoField("jmoAddedOperation", "bit", 1, 0, nullable: false),
			new DmoField("jmoPrototypeOperation", "bit", 1, 0, nullable: false),
			new DmoField("jmoPlantDepartmentID", "nvarchar", 5, 0, nullable: false),
			new DmoField("jmoPlantID", "nvarchar", 5, 0, nullable: false),
			new DmoField("jmoWorkCenterID", "nvarchar", 5, 0, nullable: false),
			new DmoField("jmoProcessID", "nvarchar", 5, 0, nullable: false),
			new DmoField("jmoProcessShortDescription", "nvarchar", 50, 0, nullable: false),
			new DmoField("jmoProcessLongDescriptionRTF", "nvarchar(max)", 50, 0, nullable: true),
			new DmoField("jmoProcessLongDescriptionText", "nvarchar(max)", 50, 0, nullable: true),
			new DmoField("jmoQuantityPerAssembly", "numeric", 13, 6, nullable: false),
			new DmoField("jmoQueueTime", "numeric", 6, 2, nullable: false),
			new DmoField("jmoSetupHours", "numeric", 8, 2, nullable: false),
			new DmoField("jmoProductionStandard", "numeric", 10, 4, nullable: false),
			new DmoField("jmoStandardFactor", "nvarchar", 2, 0, nullable: false),
			new DmoField("jmoSetupRate", "numeric", 8, 2, nullable: false),
			new DmoField("jmoProductionRate", "numeric", 8, 2, nullable: false),
			new DmoField("jmoOverheadRate", "numeric", 8, 2, nullable: false),
			new DmoField("jmoOperationQuantity", "numeric", 15, 5, nullable: false),
			new DmoField("jmoQuantityComplete", "numeric", 15, 5, nullable: false),
			new DmoField("jmoSetupPercentComplete", "smallint", 3, 0, nullable: false),
			new DmoField("jmoActualSetupHours", "numeric", 8, 2, nullable: false),
			new DmoField("jmoActualProductionHours", "numeric", 8, 2, nullable: false),
			new DmoField("jmoQuantityToInspect", "numeric", 15, 5, nullable: false),
			new DmoField("jmoScrapQuantityReceived", "numeric", 15, 5, nullable: false),
			new DmoField("jmoQuantityToReturn", "numeric", 15, 5, nullable: false),
			new DmoField("jmoMoveTime", "numeric", 6, 2, nullable: false),
			new DmoField("jmoSetupComplete", "bit", 1, 0, nullable: false),
			new DmoField("jmoProductionComplete", "bit", 1, 0, nullable: false),
			new DmoField("jmoOverlapSourceLink", "tinyint", 1, 0, nullable: false),
			new DmoField("jmoOverlapDestinationLink", "tinyint", 1, 0, nullable: false),
			new DmoField("jmoOverlap", "tinyint", 1, 0, nullable: false),
			new DmoField("jmoOverlapOperationID", "int", 5, 0, nullable: false),
			new DmoField("jmoOverlapOffsetTime", "numeric", 8, 2, nullable: false),
			new DmoField("jmoMachineType", "tinyint", 1, 0, nullable: false),
			new DmoField("jmoWorkCenterMachineID", "smallint", 3, 0, nullable: false),
			new DmoField("jmoPartID", "nvarchar", 30, 0, nullable: false),
			new DmoField("jmoPartRevisionID", "nvarchar", 15, 0, nullable: false),
			new DmoField("jmoPartWarehouseLocationID", "nvarchar", 5, 0, nullable: false),
			new DmoField("jmoPartBinID", "nvarchar", 15, 0, nullable: false),
			new DmoField("jmoUnitOfMeasure", "nvarchar", 2, 0, nullable: false),
			new DmoField("jmoSupplierOrganizationID", "nvarchar", 10, 0, nullable: false),
			new DmoField("jmoPurchaseLocationID", "nvarchar", 5, 0, nullable: false),
			new DmoField("jmoFirm", "bit", 1, 0, nullable: false),
			new DmoField("jmoPurchaseOrderID", "nvarchar", 10, 0, nullable: false),
			new DmoField("jmoEstimatedUnitCost", "numeric", 15, 5, nullable: false),
			new DmoField("jmoMinimumCharge", "numeric", 8, 2, nullable: false),
			new DmoField("jmoSetupCharge", "numeric", 9, 2, nullable: false),
			new DmoField("jmoCalculatedUnitCost", "numeric", 15, 5, nullable: false),
			new DmoField("jmoQuantityBreak1", "numeric", 15, 5, nullable: false),
			new DmoField("jmoUnitCost1", "numeric", 15, 5, nullable: false),
			new DmoField("jmoQuantityBreak2", "numeric", 15, 5, nullable: false),
			new DmoField("jmoUnitCost2", "numeric", 15, 5, nullable: false),
			new DmoField("jmoQuantityBreak3", "numeric", 15, 5, nullable: false),
			new DmoField("jmoUnitCost3", "numeric", 15, 5, nullable: false),
			new DmoField("jmoQuantityBreak4", "numeric", 15, 5, nullable: false),
			new DmoField("jmoUnitCost4", "numeric", 15, 5, nullable: false),
			new DmoField("jmoQuantityBreak5", "numeric", 15, 5, nullable: false),
			new DmoField("jmoUnitCost5", "numeric", 15, 5, nullable: false),
			new DmoField("jmoQuantityBreak6", "numeric", 15, 5, nullable: false),
			new DmoField("jmoUnitCost6", "numeric", 15, 5, nullable: false),
			new DmoField("jmoQuantityBreak7", "numeric", 15, 5, nullable: false),
			new DmoField("jmoUnitCost7", "numeric", 15, 5, nullable: false),
			new DmoField("jmoQuantityBreak8", "numeric", 15, 5, nullable: false),
			new DmoField("jmoUnitCost8", "numeric", 15, 5, nullable: false),
			new DmoField("jmoQuantityBreak9", "numeric", 15, 5, nullable: false),
			new DmoField("jmoUnitCost9", "numeric", 15, 5, nullable: false),
			new DmoField("jmoStartDate", "date", 14, 0, nullable: true),
			new DmoField("jmoDueDate", "date", 14, 0, nullable: true),
			new DmoField("jmoStartHour", "numeric", 5, 2, nullable: false),
			new DmoField("jmoDueHour", "numeric", 5, 2, nullable: false),
			new DmoField("jmoEstimatedProductionHours", "numeric", 8, 2, nullable: false),
			new DmoField("jmoCompletedSetupHours", "numeric", 8, 2, nullable: false),
			new DmoField("jmoCompletedProductionHours", "numeric", 8, 2, nullable: false),
			new DmoField("jmoDocuments", "nvarchar(max)", 50, 0, nullable: true),
			new DmoField("jmoSFEMessageRTF", "nvarchar(max)", 50, 0, nullable: true),
			new DmoField("jmoSFEMessageText", "nvarchar(max)", 50, 0, nullable: true),
			new DmoField("jmoClosed", "bit", 1, 0, nullable: false),
			new DmoField("jmoInspectionComplete", "bit", 1, 0, nullable: false),
			new DmoField("jmoInspectionStatus", "tinyint", 1, 0, nullable: false),
			new DmoField("jmoInspectionType", "tinyint", 1, 0, nullable: false),
			new DmoField("jmoRFQID", "nvarchar", 10, 0, nullable: false),
			new DmoField("jmoMachinesToSchedule", "smallint", 3, 0, nullable: false),
			new DmoField("jmoCreatedBy", "nvarchar", 20, 0, nullable: false),
			new DmoField("jmoCreatedDate", "datetime", 14, 0, nullable: true),
			new DmoField("jmoUniqueID", "uniqueidentifier", 16, 0, nullable: false)
		}, new DmoIndex[18]
		{
			new DmoIndex("JMOJOBID,JMOJOBASSEMBLYID,JMOJOBOPERATIONID", unique: true),
			new DmoIndex("JMOUNIQUEID", unique: true),
			new DmoIndex("jmoJobID", unique: false),
			new DmoIndex("jmoJobAssemblyID", unique: false),
			new DmoIndex("jmoJobOperationID", unique: false),
			new DmoIndex("jmoOperationType", unique: false),
			new DmoIndex("jmoPlantDepartmentID", unique: false),
			new DmoIndex("jmoPlantID", unique: false),
			new DmoIndex("jmoWorkCenterID", unique: false),
			new DmoIndex("jmoSetupComplete", unique: false),
			new DmoIndex("jmoProductionComplete", unique: false),
			new DmoIndex("jmoWorkCenterMachineID", unique: false),
			new DmoIndex("jmoPartID", unique: false),
			new DmoIndex("jmoPartRevisionID", unique: false),
			new DmoIndex("jmoStartDate", unique: false),
			new DmoIndex("jmoStartHour", unique: false),
			new DmoIndex("jmoClosed", unique: false),
			new DmoIndex("jmoInspectionType", unique: false)
		}, mergeCustomFields: true, disableTriggers: true);
	}
}
