using M1.Core;

namespace M1.Ax.Erp.DD;

[DBConversion("8.10.050", "Convert ReceiptLines to support unicode", "2013-10-17")]
public class v810RebuildReceiptLines
{
	public v810RebuildReceiptLines(DBConversionParms parms)
	{
		parms.ServerManager.ExecuteCommand(null, parms.User, parms.DatabaseName, "Update ReceiptLines Set rmlForm1099Box = 0 Where rmlForm1099Box = -1");
		parms.Dmo.RebuildTable(null, parms.User, parms.DataDictionary, parms.DatabaseName, "ReceiptLines", new DmoField[66]
		{
			new DmoField("rmlReceiptID", "nvarchar", 10, 0, nullable: false),
			new DmoField("rmlReceiptLineID", "smallint", 4, 0, nullable: false),
			new DmoField("rmlPurchaseOrderID", "nvarchar", 10, 0, nullable: false),
			new DmoField("rmlPurchaseOrderLineID", "smallint", 4, 0, nullable: false),
			new DmoField("rmlRMAClaimID", "nvarchar", 10, 0, nullable: false),
			new DmoField("rmlDMRClaimID", "nvarchar", 10, 0, nullable: false),
			new DmoField("rmlDMRClaimLineID", "smallint", 4, 0, nullable: false),
			new DmoField("rmlRMAClaimLineID", "smallint", 4, 0, nullable: false),
			new DmoField("rmlJobID", "nvarchar", 20, 0, nullable: false),
			new DmoField("rmlJobAssemblyID", "int", 5, 0, nullable: false),
			new DmoField("rmlJobType", "tinyint", 1, 0, nullable: false),
			new DmoField("rmlJobMaterialID", "int", 5, 0, nullable: false),
			new DmoField("rmlJobOperationID", "int", 5, 0, nullable: false),
			new DmoField("rmlPartID", "nvarchar", 30, 0, nullable: false),
			new DmoField("rmlPartRevisionID", "nvarchar", 15, 0, nullable: false),
			new DmoField("rmlOrgPartID", "nvarchar", 30, 0, nullable: false),
			new DmoField("rmlOrgPartShortDescription", "nvarchar", 50, 0, nullable: false),
			new DmoField("rmlDescription", "nvarchar", 50, 0, nullable: false),
			new DmoField("rmlPartLongDescriptionRTF", "nvarchar(max)", 50, 0, nullable: true),
			new DmoField("rmlPartLongDescriptionText", "nvarchar(max)", 50, 0, nullable: true),
			new DmoField("rmlPartWarehouseLocationID", "nvarchar", 5, 0, nullable: false),
			new DmoField("rmlPartBinID", "nvarchar", 15, 0, nullable: false),
			new DmoField("rmlKitPart", "bit", 1, 0, nullable: false),
			new DmoField("rmlPurchaseQuantityReceived", "numeric", 15, 5, nullable: false),
			new DmoField("rmlPurchaseUnitOfMeasure", "nvarchar", 2, 0, nullable: false),
			new DmoField("rmlPurchaseUnitCost", "numeric", 15, 5, nullable: false),
			new DmoField("rmlSetupCharge", "numeric", 9, 2, nullable: false),
			new DmoField("rmlConversionFactor", "numeric", 14, 8, nullable: false),
			new DmoField("rmlInventoryQuantityReceived", "numeric", 15, 5, nullable: false),
			new DmoField("rmlJobQuantityReceived", "numeric", 15, 5, nullable: false),
			new DmoField("rmlInventoryUnitOfMeasure", "nvarchar", 2, 0, nullable: false),
			new DmoField("rmlInventoryUnitCost", "numeric", 15, 5, nullable: false),
			new DmoField("rmlPOReceivedComplete", "bit", 1, 0, nullable: false),
			new DmoField("rmlJobReceivedComplete", "bit", 1, 0, nullable: false),
			new DmoField("rmlInvoicedComplete", "bit", 1, 0, nullable: false),
			new DmoField("rmlRequiresInspection", "bit", 1, 0, nullable: false),
			new DmoField("rmlReference", "nvarchar", 30, 0, nullable: false),
			new DmoField("rmlHeatLot", "nvarchar", 50, 0, nullable: false),
			new DmoField("rmlClosed", "bit", 1, 0, nullable: false),
			new DmoField("rmlInspectionNotesText", "nvarchar(max)", 50, 0, nullable: true),
			new DmoField("rmlInspectionNotesRTF", "nvarchar(max)", 50, 0, nullable: true),
			new DmoField("rmlProjectID", "nvarchar", 10, 0, nullable: false),
			new DmoField("rmlProjectAreaID", "nvarchar", 15, 0, nullable: false),
			new DmoField("rmlTrackSerialNumbers", "bit", 1, 0, nullable: false),
			new DmoField("rmlSalesOrderID", "nvarchar", 10, 0, nullable: false),
			new DmoField("rmlSalesOrderLineID", "smallint", 4, 0, nullable: false),
			new DmoField("rmlSalesOrderDeliveryID", "smallint", 4, 0, nullable: false),
			new DmoField("rmlInspected", "bit", 1, 0, nullable: false),
			new DmoField("rmlPurchaseUnitCostForeign", "numeric", 15, 5, nullable: false),
			new DmoField("rmlSetupChargeForeign", "numeric", 9, 2, nullable: false),
			new DmoField("rmlInventoryUnitCostForeign", "numeric", 15, 5, nullable: false),
			new DmoField("rmlCurrencyRateID", "nvarchar", 5, 0, nullable: false),
			new DmoField("rmlCustomRate", "bit", 1, 0, nullable: false),
			new DmoField("rmlExchangeRate", "numeric", 13, 6, nullable: false),
			new DmoField("rmlReceiptDate", "datetime", 14, 0, nullable: true),
			new DmoField("rmlDutyUnitCost", "numeric", 15, 5, nullable: false),
			new DmoField("rmlFreightUnitCost", "numeric", 15, 5, nullable: false),
			new DmoField("rmlMiscUnitCost", "numeric", 15, 5, nullable: false),
			new DmoField("rmlPostedToGL", "bit", 1, 0, nullable: false),
			new DmoField("rmlReversed", "bit", 1, 0, nullable: false),
			new DmoField("rmlReverseReceiptID", "nvarchar", 10, 0, nullable: false),
			new DmoField("rmlReverseReceiptLineID", "smallint", 4, 0, nullable: false),
			new DmoField("rmlForm1099Box", "tinyint", 2, 0, nullable: false),
			new DmoField("rmlCreatedBy", "nvarchar", 20, 0, nullable: false),
			new DmoField("rmlCreatedDate", "datetime", 14, 0, nullable: true),
			new DmoField("rmlUniqueID", "uniqueidentifier", 16, 0, nullable: false)
		}, new DmoIndex[28]
		{
			new DmoIndex("RMLRECEIPTID,RMLRECEIPTLINEID", unique: true),
			new DmoIndex("RMLUNIQUEID", unique: true),
			new DmoIndex("rmlReceiptID", unique: false),
			new DmoIndex("rmlReceiptLineID", unique: false),
			new DmoIndex("rmlPurchaseOrderID", unique: false),
			new DmoIndex("rmlPurchaseOrderLineID", unique: false),
			new DmoIndex("rmlRMAClaimID", unique: false),
			new DmoIndex("rmlDMRClaimID", unique: false),
			new DmoIndex("rmlDMRClaimLineID", unique: false),
			new DmoIndex("rmlRMAClaimLineID", unique: false),
			new DmoIndex("rmlJobID", unique: false),
			new DmoIndex("rmlJobAssemblyID", unique: false),
			new DmoIndex("rmlJobType", unique: false),
			new DmoIndex("rmlJobMaterialID", unique: false),
			new DmoIndex("rmlJobOperationID", unique: false),
			new DmoIndex("rmlPartID", unique: false),
			new DmoIndex("rmlPartRevisionID", unique: false),
			new DmoIndex("rmlOrgPartID", unique: false),
			new DmoIndex("rmlPOReceivedComplete", unique: false),
			new DmoIndex("rmlInvoicedComplete", unique: false),
			new DmoIndex("rmlRequiresInspection", unique: false),
			new DmoIndex("rmlProjectID", unique: false),
			new DmoIndex("rmlProjectAreaID", unique: false),
			new DmoIndex("rmlSalesOrderID", unique: false),
			new DmoIndex("rmlSalesOrderLineID", unique: false),
			new DmoIndex("rmlSalesOrderDeliveryID", unique: false),
			new DmoIndex("rmlReverseReceiptID", unique: false),
			new DmoIndex("rmlReverseReceiptLineID", unique: false)
		}, mergeCustomFields: true, disableTriggers: true);
	}
}
