using M1.Core;

namespace M1.Ax.Erp.DD;

[DBConversion("8.10.050", "Convert ARInvoices to support unicode", "2013-10-17")]
public class v810RebuildARInvoices
{
	public v810RebuildARInvoices(DBConversionParms parms)
	{
		parms.Dmo.RebuildTable(null, parms.User, parms.DataDictionary, parms.DatabaseName, "ARInvoices", new DmoField[109]
		{
			new DmoField("arpARInvoiceID", "nvarchar", 10, 0, nullable: false),
			new DmoField("arpInvoiceType", "tinyint", 1, 0, nullable: false),
			new DmoField("arpPlantDepartmentID", "nvarchar", 5, 0, nullable: false),
			new DmoField("arpPlantID", "nvarchar", 5, 0, nullable: false),
			new DmoField("arpCreditARInvoiceID", "nvarchar", 10, 0, nullable: false),
			new DmoField("arpOpenInvoiceLoad", "bit", 1, 0, nullable: false),
			new DmoField("arpCreditReasonID", "nvarchar", 5, 0, nullable: false),
			new DmoField("arpCustomerOrganizationID", "nvarchar", 10, 0, nullable: false),
			new DmoField("arpARInvoiceLocationID", "nvarchar", 5, 0, nullable: false),
			new DmoField("arpARInvoiceContactID", "nvarchar", 5, 0, nullable: false),
			new DmoField("arpShipOrganizationID", "nvarchar", 10, 0, nullable: false),
			new DmoField("arpShipLocationID", "nvarchar", 5, 0, nullable: false),
			new DmoField("arpShipContactID", "nvarchar", 5, 0, nullable: false),
			new DmoField("arpInvoiceDate", "date", 14, 0, nullable: true),
			new DmoField("arpTaxDate", "date", 14, 0, nullable: true),
			new DmoField("arpPaymentTermID", "nvarchar", 5, 0, nullable: false),
			new DmoField("arpDueDate", "date", 14, 0, nullable: true),
			new DmoField("arpDiscountDueDate", "date", 14, 0, nullable: true),
			new DmoField("arpOrderDate", "date", 14, 0, nullable: true),
			new DmoField("arpFreeOnBoardDescription", "nvarchar", 15, 0, nullable: false),
			new DmoField("arpStandardMessageID", "nvarchar", 10, 0, nullable: false),
			new DmoField("arpInvoiceCommentsRTF", "nvarchar(max)", 50, 0, nullable: true),
			new DmoField("arpInvoiceCommentsText", "nvarchar(max)", 50, 0, nullable: true),
			new DmoField("arpReadyToPrint", "bit", 1, 0, nullable: false),
			new DmoField("arpShippingMethodID", "nvarchar", 5, 0, nullable: false),
			new DmoField("arpShippingPaymentTypeID", "nvarchar", 5, 0, nullable: false),
			new DmoField("arpGLFiscalYearID", "smallint", 4, 0, nullable: false),
			new DmoField("arpGLFiscalYearPeriodID", "tinyint", 2, 0, nullable: false),
			new DmoField("arpCurrencyRateID", "nvarchar", 5, 0, nullable: false),
			new DmoField("arpCustomRate", "bit", 1, 0, nullable: false),
			new DmoField("arpExchangeRate", "numeric", 13, 6, nullable: false),
			new DmoField("arpOriginalExchangeRate", "numeric", 13, 6, nullable: false),
			new DmoField("arpFullInvoiceSubtotalBase", "money", 12, 2, nullable: false),
			new DmoField("arpFullInvoiceSubtotalForeign", "money", 12, 2, nullable: false),
			new DmoField("arpDiscountTotalBase", "money", 12, 2, nullable: false),
			new DmoField("arpDiscountTotalForeign", "money", 12, 2, nullable: false),
			new DmoField("arpInvoiceSubtotalBase", "money", 12, 2, nullable: false),
			new DmoField("arpInvoiceSubtotalForeign", "money", 12, 2, nullable: false),
			new DmoField("arpFreightSubtotalBase", "money", 12, 2, nullable: false),
			new DmoField("arpFreightSubtotalForeign", "money", 12, 2, nullable: false),
			new DmoField("arpIncludeFreightInPrice", "bit", 1, 0, nullable: false),
			new DmoField("arpFreightAmountBase", "money", 12, 2, nullable: false),
			new DmoField("arpFreightAmountForeign", "money", 12, 2, nullable: false),
			new DmoField("arpFreightTotalBase", "money", 12, 2, nullable: false),
			new DmoField("arpFreightTotalForeign", "money", 12, 2, nullable: false),
			new DmoField("arpFreightTaxCodeID", "nvarchar", 5, 0, nullable: false),
			new DmoField("arpFreightTaxAmountBase", "money", 14, 4, nullable: false),
			new DmoField("arpFreightTaxAmountForeign", "money", 14, 4, nullable: false),
			new DmoField("arpSecondFreightTaxCodeID", "nvarchar", 5, 0, nullable: false),
			new DmoField("arpSecondFreightTaxAmtBase", "money", 14, 4, nullable: false),
			new DmoField("arpSecondFreightTaxAmtForeign", "money", 14, 4, nullable: false),
			new DmoField("arpTaxSubtotalBase", "money", 12, 2, nullable: false),
			new DmoField("arpTaxSubtotalForeign", "money", 12, 2, nullable: false),
			new DmoField("arpInvoiceTaxAmountBase", "money", 12, 2, nullable: false),
			new DmoField("arpInvoiceTaxAmountForeign", "money", 12, 2, nullable: false),
			new DmoField("arpInvoiceTotalBase", "money", 12, 2, nullable: false),
			new DmoField("arpInvoiceTotalForeign", "money", 12, 2, nullable: false),
			new DmoField("arpResellerCommissionAmount", "money", 12, 2, nullable: false),
			new DmoField("arpInvoiceBalanceBase", "money", 12, 2, nullable: false),
			new DmoField("arpInvoiceBalanceForeign", "money", 12, 2, nullable: false),
			new DmoField("arpSplitPercentTotal", "numeric", 6, 2, nullable: false),
			new DmoField("arpTotalForResellerCommission", "money", 12, 2, nullable: false),
			new DmoField("arpTotalForSalesCommission", "money", 12, 2, nullable: false),
			new DmoField("arpLineCommissionTotal", "money", 12, 2, nullable: false),
			new DmoField("arpSalesCommissionTotal", "money", 12, 2, nullable: false),
			new DmoField("arpResellerOrganizationID", "nvarchar", 10, 0, nullable: false),
			new DmoField("arpResellerLocationID", "nvarchar", 5, 0, nullable: false),
			new DmoField("arpResellerContactID", "nvarchar", 5, 0, nullable: false),
			new DmoField("arpResellerCommissionRate", "numeric", 5, 2, nullable: false),
			new DmoField("arpCommissionAmountBase", "money", 12, 2, nullable: false),
			new DmoField("arpOverpayment", "bit", 1, 0, nullable: false),
			new DmoField("arpPointOfSaleTerminalID", "nvarchar", 5, 0, nullable: false),
			new DmoField("arpOnHold", "bit", 1, 0, nullable: false),
			new DmoField("arpRefundCheckRequired", "bit", 1, 0, nullable: false),
			new DmoField("arpARGLAccountID", "nvarchar", 11, 0, nullable: false),
			new DmoField("arpSalesGLAccountID", "nvarchar", 11, 0, nullable: false),
			new DmoField("arpFreightGLAccountID", "nvarchar", 11, 0, nullable: false),
			new DmoField("arpDiscountGLAccountID", "nvarchar", 11, 0, nullable: false),
			new DmoField("arpPostedToGL", "bit", 1, 0, nullable: false),
			new DmoField("arpPaidDate", "date", 14, 0, nullable: true),
			new DmoField("arpPostedDate", "date", 14, 0, nullable: true),
			new DmoField("arpPaidComplete", "bit", 1, 0, nullable: false),
			new DmoField("arpProjectID", "nvarchar", 10, 0, nullable: false),
			new DmoField("arpIncludeTaxInRetention", "bit", 1, 0, nullable: false),
			new DmoField("arpRetentionTotalBase", "money", 12, 2, nullable: false),
			new DmoField("arpRetentionTotalForeign", "money", 12, 2, nullable: false),
			new DmoField("arpRetentionPaidBase", "money", 12, 2, nullable: false),
			new DmoField("arpRetentionPaidForeign", "money", 12, 2, nullable: false),
			new DmoField("arpRetentionBalanceBase", "money", 12, 2, nullable: false),
			new DmoField("arpRetentionBalanceForeign", "money", 12, 2, nullable: false),
			new DmoField("arpRecurringInvoice", "bit", 1, 0, nullable: false),
			new DmoField("arpDepositGLAccountID", "nvarchar", 11, 0, nullable: false),
			new DmoField("arpDepositAppliedBase", "money", 12, 2, nullable: false),
			new DmoField("arpDepositAppliedForeign", "money", 12, 2, nullable: false),
			new DmoField("arpDepositTransferredBase", "money", 12, 2, nullable: false),
			new DmoField("arpDepositTransferredForeign", "money", 12, 2, nullable: false),
			new DmoField("arpAvalaraTaxCalculated", "bit", 1, 0, nullable: false),
			new DmoField("arpDepositBalanceBase", "money", 12, 2, nullable: false),
			new DmoField("arpAvalaraOverrideTax", "bit", 1, 0, nullable: false),
			new DmoField("arpDepositBalanceForeign", "money", 12, 2, nullable: false),
			new DmoField("arpOverPaymentSessionID", "int", 9, 0, nullable: false),
			new DmoField("arpOverPaymentHeaderID", "int", 9, 0, nullable: false),
			new DmoField("arpDepositCredit", "bit", 1, 0, nullable: false),
			new DmoField("arpCreatedBy", "nvarchar", 20, 0, nullable: false),
			new DmoField("arpCreatedDate", "datetime", 14, 0, nullable: true),
			new DmoField("arpUniqueID", "uniqueidentifier", 16, 0, nullable: false),
			new DmoField("arpCreditDate", "date", 14, 0, nullable: true),
			new DmoField("arpEDITransferred", "bit", 1, 0, nullable: false),
			new DmoField("arpEDITransferredDate", "date", 14, 0, nullable: true)
		}, new DmoIndex[18]
		{
			new DmoIndex("ARPARINVOICEID", unique: true),
			new DmoIndex("ARPUNIQUEID", unique: true),
			new DmoIndex("arpPlantDepartmentID", unique: false),
			new DmoIndex("arpPlantID", unique: false),
			new DmoIndex("arpCustomerOrganizationID", unique: false),
			new DmoIndex("arpARInvoiceLocationID", unique: false),
			new DmoIndex("arpShipOrganizationID", unique: false),
			new DmoIndex("arpReadyToPrint", unique: false),
			new DmoIndex("arpGLFiscalYearID", unique: false),
			new DmoIndex("arpGLFiscalYearPeriodID", unique: false),
			new DmoIndex("arpResellerOrganizationID", unique: false),
			new DmoIndex("arpPointOfSaleTerminalID", unique: false),
			new DmoIndex("arpOnHold", unique: false),
			new DmoIndex("arpRefundCheckRequired", unique: false),
			new DmoIndex("arpPostedToGL", unique: false),
			new DmoIndex("arpPaidDate", unique: false),
			new DmoIndex("arpPaidComplete", unique: false),
			new DmoIndex("arpProjectID", unique: false)
		}, mergeCustomFields: true, disableTriggers: true);
	}
}
