using M1.Core;

namespace M1.Ax.Erp.DD;

[DBConversion("8.10.050", "Convert IncomeTaxYearTotals to support unicode", "2013-10-17")]
public class v810RebuildIncomeTaxYearTotals
{
	public v810RebuildIncomeTaxYearTotals(DBConversionParms parms)
	{
		parms.Dmo.RebuildTable(null, parms.User, parms.DataDictionary, parms.DatabaseName, "IncomeTaxYearTotals", new DmoField[150]
		{
			new DmoField("pahIncomeTaxYearID", "smallint", 4, 0, nullable: false),
			new DmoField("pahPlantID", "nvarchar", 5, 0, nullable: false),
			new DmoField("pahIncomeTaxYearTotalID", "smallint", 4, 0, nullable: false),
			new DmoField("pahPayrollEmployeeID", "nvarchar", 10, 0, nullable: false),
			new DmoField("pahUSControlNumber", "int", 6, 0, nullable: false),
			new DmoField("pahEmployeeTaxFileNumber", "nvarchar", 11, 0, nullable: false),
			new DmoField("pahEmployeeFirstName", "nvarchar", 40, 0, nullable: false),
			new DmoField("pahEmployeeLastName", "nvarchar", 20, 0, nullable: false),
			new DmoField("pahEmployeeFederalID", "nvarchar", 20, 0, nullable: false),
			new DmoField("pahEmployeeAddressLine1", "nvarchar", 50, 0, nullable: false),
			new DmoField("pahEmployeeAddressLine2", "nvarchar", 50, 0, nullable: false),
			new DmoField("pahEmployeeCity", "nvarchar", 30, 0, nullable: false),
			new DmoField("pahEmployeeState", "nvarchar", 3, 0, nullable: false),
			new DmoField("pahEmployeePostCode", "nvarchar", 10, 0, nullable: false),
			new DmoField("pahEmployeeCountry", "nvarchar", 20, 0, nullable: false),
			new DmoField("pahEmployeeBirthDate", "date", 14, 0, nullable: true),
			new DmoField("pahEmployeeHireDate", "date", 14, 0, nullable: true),
			new DmoField("pahUSVoid", "bit", 1, 0, nullable: false),
			new DmoField("pahUSWages", "money", 11, 2, nullable: false),
			new DmoField("pahUSFederalIncomeTax", "money", 11, 2, nullable: false),
			new DmoField("pahUSSocialSecurityWages", "money", 11, 2, nullable: false),
			new DmoField("pahUSSocialSecurityTax", "money", 11, 2, nullable: false),
			new DmoField("pahUSMedicareWages", "money", 11, 2, nullable: false),
			new DmoField("pahUSMedicareTax", "money", 11, 2, nullable: false),
			new DmoField("pahUSSocialSecurityTips", "money", 11, 2, nullable: false),
			new DmoField("pahUSAllocatedTips", "money", 11, 2, nullable: false),
			new DmoField("pahUSAdvanceEICPayment", "money", 11, 2, nullable: false),
			new DmoField("pahUSDependentCareBenefits", "money", 11, 2, nullable: false),
			new DmoField("pahUSNonqualifiedPlans", "money", 11, 2, nullable: false),
			new DmoField("pahUSBox12aCode", "nvarchar", 2, 0, nullable: false),
			new DmoField("pahUSBox12aAmount", "money", 11, 2, nullable: false),
			new DmoField("pahUSBox12bCode", "nvarchar", 2, 0, nullable: false),
			new DmoField("pahUSBox12bAmount", "money", 11, 2, nullable: false),
			new DmoField("pahUSBox12cCode", "nvarchar", 2, 0, nullable: false),
			new DmoField("pahUSBox12cAmount", "money", 11, 2, nullable: false),
			new DmoField("pahUSBox12dCode", "nvarchar", 2, 0, nullable: false),
			new DmoField("pahUSBox12dAmount", "money", 11, 2, nullable: false),
			new DmoField("pahUSStatutoryEmployee", "bit", 1, 0, nullable: false),
			new DmoField("pahUSRetirementPlan", "bit", 1, 0, nullable: false),
			new DmoField("pahUSThirdPartySickPay", "bit", 1, 0, nullable: false),
			new DmoField("pahUSOther", "nvarchar", 20, 0, nullable: false),
			new DmoField("pahUSState1", "nvarchar", 2, 0, nullable: false),
			new DmoField("pahUSEmployerState1IDNumber", "nvarchar", 15, 0, nullable: false),
			new DmoField("pahUSState1Wages", "money", 11, 2, nullable: false),
			new DmoField("pahUSState1Tax", "money", 11, 2, nullable: false),
			new DmoField("pahUSLocal1Wages", "money", 11, 2, nullable: false),
			new DmoField("pahUSLocal1Tax", "money", 11, 2, nullable: false),
			new DmoField("pahUSLocality1Name", "nvarchar", 10, 0, nullable: false),
			new DmoField("pahUSState2", "nvarchar", 2, 0, nullable: false),
			new DmoField("pahUSEmployerState2IDNumber", "nvarchar", 15, 0, nullable: false),
			new DmoField("pahUSState2Wages", "money", 11, 2, nullable: false),
			new DmoField("pahUSState2Tax", "money", 11, 2, nullable: false),
			new DmoField("pahUSLocal2Wages", "money", 11, 2, nullable: false),
			new DmoField("pahUSLocal2Tax", "money", 11, 2, nullable: false),
			new DmoField("pahUSLocality2Name", "nvarchar", 10, 0, nullable: false),
			new DmoField("pahAUSPAYGSummaryType", "nvarchar", 1, 0, nullable: false),
			new DmoField("pahAUSPaymentStartDate", "date", 14, 0, nullable: true),
			new DmoField("pahAUSPaymentEndDate", "date", 14, 0, nullable: true),
			new DmoField("pahAUSReportableFringeBenefits", "money", 8, 0, nullable: false),
			new DmoField("pahAUSTotalTaxWithheld", "money", 8, 0, nullable: false),
			new DmoField("pahAUSWithholdingRate", "numeric", 6, 2, nullable: false),
			new DmoField("pahAUSGrossPayments", "money", 8, 0, nullable: false),
			new DmoField("pahAUSCDEPWages", "money", 8, 0, nullable: false),
			new DmoField("pahAUSOtherIncome", "money", 8, 0, nullable: false),
			new DmoField("pahAUSAllowance1Description", "nvarchar", 20, 0, nullable: false),
			new DmoField("pahAUSAllowance1Amount", "money", 8, 0, nullable: false),
			new DmoField("pahAUSAllowance2Description", "nvarchar", 20, 0, nullable: false),
			new DmoField("pahAUSAllowance2Amount", "money", 8, 0, nullable: false),
			new DmoField("pahAUSAllowance3Description", "nvarchar", 20, 0, nullable: false),
			new DmoField("pahAUSAllowance3Amount", "money", 8, 0, nullable: false),
			new DmoField("pahAUSAllowance4Description", "nvarchar", 20, 0, nullable: false),
			new DmoField("pahAUSAllowance4Amount", "money", 8, 0, nullable: false),
			new DmoField("pahAUSTotalAllowances", "money", 8, 0, nullable: false),
			new DmoField("pahAUSLumpSumPaymentA", "money", 8, 0, nullable: false),
			new DmoField("pahAUSLumpSumPaymentB", "money", 8, 0, nullable: false),
			new DmoField("pahAUSLumpSumPaymentD", "money", 8, 0, nullable: false),
			new DmoField("pahAUSLumpSumPaymentE", "money", 8, 0, nullable: false),
			new DmoField("pahAUSUnionName", "nvarchar", 50, 0, nullable: false),
			new DmoField("pahAUSUnionFees", "money", 8, 0, nullable: false),
			new DmoField("pahAUSPaymentDate", "date", 14, 0, nullable: true),
			new DmoField("pahAUSDaysBefore1983", "int", 5, 0, nullable: false),
			new DmoField("pahAUSDaysAfter1983", "int", 5, 0, nullable: false),
			new DmoField("pahAUSCGTExempt", "money", 8, 0, nullable: false),
			new DmoField("pahAUSNonQualifying", "money", 8, 0, nullable: false),
			new DmoField("pahAUSUndeducted", "money", 8, 0, nullable: false),
			new DmoField("pahCreatedBy", "nvarchar", 20, 0, nullable: false),
			new DmoField("pahCreatedDate", "datetime", 14, 0, nullable: true),
			new DmoField("pahAUSConcessional", "money", 8, 0, nullable: false),
			new DmoField("pahAUSPre1983Component", "money", 8, 0, nullable: false),
			new DmoField("pahAUSPost1983UntaxedElement", "money", 8, 0, nullable: false),
			new DmoField("pahAUSPost1983TaxedElement", "money", 8, 0, nullable: false),
			new DmoField("pahAUSPost1994Invalidity", "money", 8, 0, nullable: false),
			new DmoField("pahAUSAssessableAmount", "money", 8, 0, nullable: false),
			new DmoField("pahAUSDeathBenefit", "nvarchar", 1, 0, nullable: false),
			new DmoField("pahAUSTypeOfDeathBenefit", "nvarchar", 1, 0, nullable: false),
			new DmoField("pahClosed", "bit", 1, 0, nullable: false),
			new DmoField("pahAUSAmendIndicator", "nvarchar", 1, 0, nullable: false),
			new DmoField("pahAUSTransitTermination", "nvarchar", 1, 0, nullable: false),
			new DmoField("pahAUSRelatedPriorTermination", "nvarchar", 1, 0, nullable: false),
			new DmoField("pahAUSTaxFreeAmount", "money", 8, 0, nullable: false),
			new DmoField("pahUSBox14ADescription", "nvarchar", 5, 0, nullable: false),
			new DmoField("pahUSBox14AAmount", "money", 11, 2, nullable: false),
			new DmoField("pahUSBox14BDescription", "nvarchar", 5, 0, nullable: false),
			new DmoField("pahUSBox14BAmount", "money", 11, 2, nullable: false),
			new DmoField("pahUSBox14CDescription", "nvarchar", 5, 0, nullable: false),
			new DmoField("pahUSBox14CAmount", "money", 11, 2, nullable: false),
			new DmoField("pahCABusinessNumber", "nvarchar", 20, 0, nullable: false),
			new DmoField("pahCAExemptCPPQPP", "bit", 1, 0, nullable: false),
			new DmoField("pahCAExemptEI", "bit", 1, 0, nullable: false),
			new DmoField("pahCAExemptPPIP", "bit", 1, 0, nullable: false),
			new DmoField("pahCAEmploymentCode", "tinyint", 2, 0, nullable: false),
			new DmoField("pahCAEmploymentIncome", "money", 11, 2, nullable: false),
			new DmoField("pahCAIncomeTaxDeducted", "money", 11, 2, nullable: false),
			new DmoField("pahCAEmployeeCPPContributions", "money", 8, 2, nullable: false),
			new DmoField("pahCAEmployeeQPPContributions", "money", 8, 2, nullable: false),
			new DmoField("pahCACPPQPPPensionableEarnings", "money", 9, 2, nullable: false),
			new DmoField("pahCAEmployeeEIPremiums", "money", 8, 2, nullable: false),
			new DmoField("pahCAEIInsurableEarnings", "money", 9, 2, nullable: false),
			new DmoField("pahCARPPContributions", "money", 9, 2, nullable: false),
			new DmoField("pahCARPPRegistrationNumber", "nvarchar", 7, 0, nullable: false),
			new DmoField("pahCAUnionDues", "money", 9, 2, nullable: false),
			new DmoField("pahCACharitableDonations", "money", 10, 2, nullable: false),
			new DmoField("pahCAPensionAdjustment", "money", 9, 2, nullable: false),
			new DmoField("pahCAEmployeePPIPPremiums", "money", 8, 2, nullable: false),
			new DmoField("pahCAPPIPInsurableEarnings", "money", 9, 2, nullable: false),
			new DmoField("pahCAOtherBox1Code", "tinyint", 2, 0, nullable: false),
			new DmoField("pahCAOtherBox1Amount", "money", 10, 2, nullable: false),
			new DmoField("pahCAOtherBox2Code", "tinyint", 2, 0, nullable: false),
			new DmoField("pahCAOtherBox2Amount", "money", 10, 2, nullable: false),
			new DmoField("pahCAOtherBox3Code", "tinyint", 2, 0, nullable: false),
			new DmoField("pahCAOtherBox3Amount", "money", 10, 2, nullable: false),
			new DmoField("pahCAOtherBox4Code", "tinyint", 2, 0, nullable: false),
			new DmoField("pahCAOtherBox4Amount", "money", 10, 2, nullable: false),
			new DmoField("pahCAOtherBox5Code", "tinyint", 2, 0, nullable: false),
			new DmoField("pahCAOtherBox5Amount", "money", 10, 2, nullable: false),
			new DmoField("pahCAOtherBox6Code", "tinyint", 2, 0, nullable: false),
			new DmoField("pahCAOtherBox6Amount", "money", 10, 2, nullable: false),
			new DmoField("pahCAEmployerCPPContributions", "money", 8, 2, nullable: false),
			new DmoField("pahCAEmployerEIPremiums", "money", 8, 2, nullable: false),
			new DmoField("pahCAEmploymentProvince", "nvarchar", 2, 0, nullable: false),
			new DmoField("pahAUSReportableSuper", "money", 8, 0, nullable: false),
			new DmoField("pahAUSLumpSumPaymentAType", "nvarchar", 1, 0, nullable: false),
			new DmoField("pahAUSWorkplaceGiving", "money", 8, 0, nullable: false),
			new DmoField("pahAUSExemptForeignIncome", "money", 8, 0, nullable: false),
			new DmoField("pahAUSDeductibleAnnuity", "money", 8, 0, nullable: false),
			new DmoField("pahAUSPSIPaymentType", "nvarchar", 3, 0, nullable: false),
			new DmoField("pahAUSForeignTaxPaid", "money", 8, 0, nullable: false),
			new DmoField("pahAUSForeignGrossPaymentType", "nvarchar", 1, 0, nullable: false),
			new DmoField("pahAUSETPPaymentType", "nvarchar", 1, 0, nullable: false),
			new DmoField("pahUniqueID", "uniqueidentifier", 16, 0, nullable: false)
		}, new DmoIndex[6]
		{
			new DmoIndex("PAHINCOMETAXYEARID,PAHPLANTID,PAHINCOMETAXYEARTOTALID", unique: true),
			new DmoIndex("PAHUNIQUEID", unique: true),
			new DmoIndex("pahIncomeTaxYearID", unique: false),
			new DmoIndex("pahPlantID", unique: false),
			new DmoIndex("pahIncomeTaxYearTotalID", unique: false),
			new DmoIndex("pahPayrollEmployeeID", unique: false)
		}, mergeCustomFields: true, disableTriggers: true);
	}
}
