using M1.Core;

namespace M1.Ax.Erp.DD;

[DBConversion("8.10.050", "Convert SalesOrders to support unicode", "2013-10-17")]
public class v810RebuildSalesOrders
{
	public v810RebuildSalesOrders(DBConversionParms parms)
	{
		parms.Dmo.RebuildTable(null, parms.User, parms.DataDictionary, parms.DatabaseName, "SalesOrders", new DmoField[81]
		{
			new DmoField("ompSalesOrderID", "nvarchar", 10, 0, nullable: false),
			new DmoField("ompPlantID", "nvarchar", 5, 0, nullable: false),
			new DmoField("ompPlantDepartmentID", "nvarchar", 5, 0, nullable: false),
			new DmoField("ompCustomerOrganizationID", "nvarchar", 10, 0, nullable: false),
			new DmoField("ompARInvoiceLocationID", "nvarchar", 5, 0, nullable: false),
			new DmoField("ompARInvoiceContactID", "nvarchar", 5, 0, nullable: false),
			new DmoField("ompQuoteLocationID", "nvarchar", 5, 0, nullable: false),
			new DmoField("ompQuoteContactID", "nvarchar", 5, 0, nullable: false),
			new DmoField("ompShipOrganizationID", "nvarchar", 10, 0, nullable: false),
			new DmoField("ompShipLocationID", "nvarchar", 5, 0, nullable: false),
			new DmoField("ompShipContactID", "nvarchar", 5, 0, nullable: false),
			new DmoField("ompCustomerPO", "nvarchar", 40, 0, nullable: false),
			new DmoField("ompRequestedShipDate", "date", 14, 0, nullable: true),
			new DmoField("ompOrderDate", "date", 14, 0, nullable: true),
			new DmoField("ompFreeOnBoardDescription", "nvarchar", 15, 0, nullable: false),
			new DmoField("ompShippingMethodID", "nvarchar", 5, 0, nullable: false),
			new DmoField("ompShippingPaymentTypeID", "nvarchar", 5, 0, nullable: false),
			new DmoField("ompPaymentTermID", "nvarchar", 5, 0, nullable: false),
			new DmoField("ompResellerOrganizationID", "nvarchar", 10, 0, nullable: false),
			new DmoField("ompResellerLocationID", "nvarchar", 5, 0, nullable: false),
			new DmoField("ompResellerContactID", "nvarchar", 5, 0, nullable: false),
			new DmoField("ompOrderCommentsRTF", "nvarchar(max)", 50, 0, nullable: true),
			new DmoField("ompOrderCommentsText", "nvarchar(max)", 50, 0, nullable: true),
			new DmoField("ompCreatedFromWeb", "bit", 1, 0, nullable: false),
			new DmoField("ompReadyToPrint", "bit", 1, 0, nullable: false),
			new DmoField("ompStandardMessageID", "nvarchar", 10, 0, nullable: false),
			new DmoField("ompCurrencyRateID", "nvarchar", 5, 0, nullable: false),
			new DmoField("ompCustomRate", "bit", 1, 0, nullable: false),
			new DmoField("ompExchangeRate", "numeric", 13, 6, nullable: false),
			new DmoField("ompFullOrderSubtotalBase", "money", 12, 2, nullable: false),
			new DmoField("ompFullOrderSubtotalForeign", "money", 12, 2, nullable: false),
			new DmoField("ompDiscountTotalBase", "money", 12, 2, nullable: false),
			new DmoField("ompDiscountTotalForeign", "money", 12, 2, nullable: false),
			new DmoField("ompOrderSubtotalBase", "money", 12, 2, nullable: false),
			new DmoField("ompOrderSubTotalForeign", "money", 12, 2, nullable: false),
			new DmoField("ompFreightSubtotalBase", "money", 12, 2, nullable: false),
			new DmoField("ompFreightSubtotalForeign", "money", 12, 2, nullable: false),
			new DmoField("ompTotalOrderWeight", "numeric", 15, 5, nullable: false),
			new DmoField("ompFreightAmountBase", "money", 12, 2, nullable: false),
			new DmoField("ompFreightAmountForeign", "money", 12, 2, nullable: false),
			new DmoField("ompFreightTotalBase", "money", 12, 2, nullable: false),
			new DmoField("ompFreightTotalForeign", "money", 12, 2, nullable: false),
			new DmoField("ompFreightTaxCodeID", "nvarchar", 5, 0, nullable: false),
			new DmoField("ompFreightTaxAmountBase", "money", 14, 4, nullable: false),
			new DmoField("ompFreightTaxAmountForeign", "money", 14, 4, nullable: false),
			new DmoField("ompSecondFreightTaxCodeID", "nvarchar", 5, 0, nullable: false),
			new DmoField("ompSecondFreightTaxAmtBase", "money", 14, 4, nullable: false),
			new DmoField("ompSecondFreightTaxAmtForeign", "money", 14, 4, nullable: false),
			new DmoField("ompOrderTaxAmountBase", "money", 12, 2, nullable: false),
			new DmoField("ompOrderTaxAmountForeign", "money", 12, 2, nullable: false),
			new DmoField("ompOrderTotalBase", "money", 12, 2, nullable: false),
			new DmoField("ompOrderTotalForeign", "money", 12, 2, nullable: false),
			new DmoField("ompStatus", "tinyint", 1, 0, nullable: false),
			new DmoField("ompApprovalRequestDate", "datetime", 14, 0, nullable: true),
			new DmoField("ompApprovalDecisionDate", "datetime", 14, 0, nullable: true),
			new DmoField("ompNextApprovalEmployeeID", "nvarchar", 10, 0, nullable: false),
			new DmoField("ompProjectID", "nvarchar", 10, 0, nullable: false),
			new DmoField("ompClosed", "bit", 1, 0, nullable: false),
			new DmoField("ompClosedDate", "date", 14, 0, nullable: true),
			new DmoField("ompDeposit", "bit", 1, 0, nullable: false),
			new DmoField("ompDepositPercent", "numeric", 6, 2, nullable: false),
			new DmoField("ompDepositCreated", "bit", 1, 0, nullable: false),
			new DmoField("ompDepositAmountBase", "money", 12, 2, nullable: false),
			new DmoField("ompDepositAmountForeign", "money", 12, 2, nullable: false),
			new DmoField("ompCallID", "nvarchar", 10, 0, nullable: false),
			new DmoField("ompAvalaraTaxCalculated", "bit", 1, 0, nullable: false),
			new DmoField("ompCreatedBy", "nvarchar", 20, 0, nullable: false),
			new DmoField("ompCreatedDate", "datetime", 14, 0, nullable: true),
			new DmoField("ompUniqueID", "uniqueidentifier", 16, 0, nullable: false),
			new DmoField("ompUPSAccountNumber", "nvarchar", 6, 0, nullable: false),
			new DmoField("ompFedExAccountNumber", "nvarchar", 15, 0, nullable: false),
			new DmoField("ompEasyOrderEnabled", "bit", 1, 0, nullable: false),
			new DmoField("ompCreatedByEDI", "bit", 1, 0, nullable: false),
			new DmoField("ompEasyOrderID", "nvarchar", 50, 0, nullable: false),
			new DmoField("ompUPSBillingOption", "nvarchar", 20, 0, nullable: false),
			new DmoField("ompFedExBillingOption", "nvarchar", 20, 0, nullable: false),
			new DmoField("ompFedEx3rdPartyOrganizationID", "nvarchar", 10, 0, nullable: false),
			new DmoField("ompFedEx3rdPartyLocationID", "nvarchar", 5, 0, nullable: false),
			new DmoField("ompUPS3rdPartyOrganizationID", "nvarchar", 10, 0, nullable: false),
			new DmoField("ompUPS3rdPartyLocationID", "nvarchar", 5, 0, nullable: false),
			new DmoField("ompEasyOrderStatus", "tinyint", 1, 0, nullable: false)
		}, new DmoIndex[16]
		{
			new DmoIndex("OMPSALESORDERID", unique: true),
			new DmoIndex("OMPUNIQUEID", unique: true),
			new DmoIndex("ompPlantID", unique: false),
			new DmoIndex("ompPlantDepartmentID", unique: false),
			new DmoIndex("ompCustomerOrganizationID", unique: false),
			new DmoIndex("ompARInvoiceLocationID", unique: false),
			new DmoIndex("ompShipOrganizationID", unique: false),
			new DmoIndex("ompCustomerPO", unique: false),
			new DmoIndex("ompOrderDate", unique: false),
			new DmoIndex("ompResellerOrganizationID", unique: false),
			new DmoIndex("ompReadyToPrint", unique: false),
			new DmoIndex("ompStatus", unique: false),
			new DmoIndex("ompNextApprovalEmployeeID", unique: false),
			new DmoIndex("ompProjectID", unique: false),
			new DmoIndex("ompClosed", unique: false),
			new DmoIndex("ompCallID", unique: false)
		}, mergeCustomFields: true, disableTriggers: true);
	}
}
