using M1.Core;

namespace M1.Ax.Erp.DD;

[DBConversion("8.10.050", "Convert PartRevisions to support unicode", "2013-10-17")]
public class v810RebuildPartRevisions
{
	public v810RebuildPartRevisions(DBConversionParms parms)
	{
		parms.ServerManager.ExecuteCommand(null, parms.User, parms.DatabaseName, "Update PartRevisions Set imrRequiresInspection = 1 WHERE imrRequiresInspection < 0");
		parms.Dmo.RebuildTable(null, parms.User, parms.DataDictionary, parms.DatabaseName, "PartRevisions", new DmoField[99]
		{
			new DmoField("imrPartID", "nvarchar", 30, 0, nullable: false),
			new DmoField("imrPartRevisionID", "nvarchar", 15, 0, nullable: false),
			new DmoField("imrShortDescription", "nvarchar", 50, 0, nullable: false),
			new DmoField("imrLongDescriptionRTF", "nvarchar(max)", 50, 0, nullable: true),
			new DmoField("imrLongDescriptionText", "nvarchar(max)", 50, 0, nullable: true),
			new DmoField("imrLongDescriptionHTML", "nvarchar(max)", 50, 0, nullable: true),
			new DmoField("imrUniversalProductCode", "nvarchar", 13, 0, nullable: false),
			new DmoField("imrEffectiveStartDate", "date", 14, 0, nullable: true),
			new DmoField("imrEffectiveEndDate", "date", 14, 0, nullable: true),
			new DmoField("imrWebSuppressWhenSold", "bit", 1, 0, nullable: false),
			new DmoField("imrInventoryUnitOfMeasure", "nvarchar", 2, 0, nullable: false),
			new DmoField("imrPurchaseUnitOfMeasure", "nvarchar", 2, 0, nullable: false),
			new DmoField("imrQuantityOnHand", "numeric", 15, 5, nullable: false),
			new DmoField("imrQuantityAllocated", "numeric", 15, 5, nullable: false),
			new DmoField("imrQuantityToInspect", "numeric", 15, 5, nullable: false),
			new DmoField("imrQuantityToReturn", "numeric", 15, 5, nullable: false),
			new DmoField("imrMinimumQuantity", "numeric", 15, 5, nullable: false),
			new DmoField("imrMaximumQuantity", "numeric", 15, 5, nullable: false),
			new DmoField("imrManufacturingLotSize", "numeric", 15, 5, nullable: false),
			new DmoField("imrAverageLaborCost", "numeric", 15, 5, nullable: false),
			new DmoField("imrAverageOverheadCost", "numeric", 15, 5, nullable: false),
			new DmoField("imrAverageMaterialCost", "numeric", 15, 5, nullable: false),
			new DmoField("imrAverageSubcontractCost", "numeric", 15, 5, nullable: false),
			new DmoField("imrLastLaborCost", "numeric", 15, 5, nullable: false),
			new DmoField("imrLastOverheadCost", "numeric", 15, 5, nullable: false),
			new DmoField("imrLastMaterialCost", "numeric", 15, 5, nullable: false),
			new DmoField("imrLastSubcontractCost", "numeric", 15, 5, nullable: false),
			new DmoField("imrStandardLaborCost", "numeric", 15, 5, nullable: false),
			new DmoField("imrStandardOverheadCost", "numeric", 15, 5, nullable: false),
			new DmoField("imrStandardMaterialCost", "numeric", 15, 5, nullable: false),
			new DmoField("imrStandardSubcontractCost", "numeric", 15, 5, nullable: false),
			new DmoField("imrLeadTime", "smallint", 3, 0, nullable: false),
			new DmoField("imrConversionFactor", "numeric", 14, 8, nullable: false),
			new DmoField("imrConfigured", "bit", 1, 0, nullable: false),
			new DmoField("imrUseQuotePrice", "bit", 1, 0, nullable: false),
			new DmoField("imrSupplierOrganizationID", "nvarchar", 10, 0, nullable: false),
			new DmoField("imrPurchaseLocationID", "nvarchar", 5, 0, nullable: false),
			new DmoField("imrPreferredRefExists", "bit", 1, 0, nullable: false),
			new DmoField("imrProductionNotesRTF", "nvarchar(max)", 50, 0, nullable: true),
			new DmoField("imrProductionNotesText", "nvarchar(max)", 50, 0, nullable: true),
			new DmoField("imrDocuments", "nvarchar(max)", 50, 0, nullable: true),
			new DmoField("imrSourceMethodID", "nvarchar", 30, 0, nullable: false),
			new DmoField("imrSourceRevisionID", "nvarchar", 15, 0, nullable: false),
			new DmoField("imrInactive", "bit", 1, 0, nullable: false),
			new DmoField("imrPartImageFileName", "nvarchar", 70, 0, nullable: false),
			new DmoField("imrLastReceiptDate", "date", 14, 0, nullable: true),
			new DmoField("imrFormID", "nvarchar", 75, 0, nullable: false),
			new DmoField("imrRequiresInspection", "tinyint", 1, 0, nullable: false),
			new DmoField("imrInspectionNotesText", "nvarchar(max)", 50, 0, nullable: true),
			new DmoField("imrInspectionNotesRTF", "nvarchar(max)", 50, 0, nullable: true),
			new DmoField("imrSheetSizeX", "numeric", 12, 3, nullable: false),
			new DmoField("imrSheetSizeY", "numeric", 12, 3, nullable: false),
			new DmoField("imrBarLength", "numeric", 12, 3, nullable: false),
			new DmoField("imrWeight", "numeric", 15, 5, nullable: false),
			new DmoField("imrWebConfigMode", "bit", 1, 0, nullable: false),
			new DmoField("imrWebConfigPriceRule", "bit", 1, 0, nullable: false),
			new DmoField("imrFdxPackaging", "nvarchar", 14, 0, nullable: false),
			new DmoField("imrFdxPackageLength", "int", 3, 0, nullable: false),
			new DmoField("imrFdxPackageWidth", "int", 3, 0, nullable: false),
			new DmoField("imrFdxPackageHeight", "int", 3, 0, nullable: false),
			new DmoField("imrFdxHandlingCost", "numeric", 7, 2, nullable: false),
			new DmoField("imrFdxPackagingCost", "numeric", 7, 2, nullable: false),
			new DmoField("imrFdxShipCostMarkupPct", "numeric", 5, 2, nullable: false),
			new DmoField("imrFdxOneItemPerShipment", "bit", 1, 0, nullable: false),
			new DmoField("imrFdxNonstandardContainer", "bit", 1, 0, nullable: false),
			new DmoField("imrQuantityOnOrderSales", "numeric", 15, 5, nullable: false),
			new DmoField("imrQuantityOnOrderPurchases", "numeric", 15, 5, nullable: false),
			new DmoField("imrWebShowToPartOrgRef", "bit", 1, 0, nullable: false),
			new DmoField("imrPurchaseableItem", "bit", 1, 0, nullable: false),
			new DmoField("imrWebSellableToAll", "bit", 1, 0, nullable: false),
			new DmoField("imrAverageDutyCost", "numeric", 15, 5, nullable: false),
			new DmoField("imrAverageFreightCost", "numeric", 15, 5, nullable: false),
			new DmoField("imrAverageMiscCost", "numeric", 15, 5, nullable: false),
			new DmoField("imrLastDutyCost", "numeric", 15, 5, nullable: false),
			new DmoField("imrLastFreightCost", "numeric", 15, 5, nullable: false),
			new DmoField("imrLastMiscCost", "numeric", 15, 5, nullable: false),
			new DmoField("imrStandardDutyCost", "numeric", 15, 5, nullable: false),
			new DmoField("imrStandardFreightCost", "numeric", 15, 5, nullable: false),
			new DmoField("imrStandardMiscCost", "numeric", 15, 5, nullable: false),
			new DmoField("imrTariffID", "nvarchar", 5, 0, nullable: false),
			new DmoField("imrVolume", "numeric", 15, 5, nullable: false),
			new DmoField("imrSuppressShortDescription", "bit", 1, 0, nullable: false),
			new DmoField("imrProductCategoryID", "nvarchar", 30, 0, nullable: false),
			new DmoField("imrProductCategoryLineID", "smallint", 4, 0, nullable: false),
			new DmoField("imrCreatedBy", "nvarchar", 20, 0, nullable: false),
			new DmoField("imrCreatedDate", "datetime", 14, 0, nullable: true),
			new DmoField("imrUniqueID", "uniqueidentifier", 16, 0, nullable: false),
			new DmoField("imrEasyOrderPartID", "nvarchar", 30, 0, nullable: false),
			new DmoField("imrCountryOfManufacture", "nvarchar", 2, 0, nullable: false),
			new DmoField("imrCommodityCode", "nvarchar", 20, 0, nullable: false),
			new DmoField("imrWeightUnitOfMeasure", "nvarchar", 3, 0, nullable: false),
			new DmoField("imrCommodityDescription", "nvarchar", 35, 0, nullable: false),
			new DmoField("imrBlanketPeriodBegin", "date", 14, 0, nullable: true),
			new DmoField("imrBlanketPeriodEnd", "date", 14, 0, nullable: true),
			new DmoField("imrNetCostCode", "nvarchar", 2, 0, nullable: false),
			new DmoField("imrPreferenceCriteria", "nvarchar", 1, 0, nullable: false),
			new DmoField("imrProducerDetermination", "nvarchar", 5, 0, nullable: false),
			new DmoField("imrNetCostBeginDate", "date", 14, 0, nullable: true),
			new DmoField("imrNetCostEndDate", "date", 14, 0, nullable: true)
		}, new DmoIndex[12]
		{
			new DmoIndex("IMRPARTID,IMRPARTREVISIONID", unique: true),
			new DmoIndex("IMRUNIQUEID", unique: true),
			new DmoIndex("imrPartID", unique: false),
			new DmoIndex("imrPartRevisionID", unique: false),
			new DmoIndex("imrShortDescription", unique: false),
			new DmoIndex("imrUniversalProductCode", unique: false),
			new DmoIndex("imrConfigured", unique: false),
			new DmoIndex("imrSourceMethodID", unique: false),
			new DmoIndex("imrSourceRevisionID", unique: false),
			new DmoIndex("imrInactive", unique: false),
			new DmoIndex("imrFormID", unique: false),
			new DmoIndex("imrTariffID", unique: false)
		}, mergeCustomFields: true, disableTriggers: true);
	}
}
