using M1.Core;

namespace M1.Ax.Erp.DD;

[DBConversion("8.10.050", "Convert PartMemos to support unicode", "2013-10-17")]
public class v810RebuildPartMemos
{
	public v810RebuildPartMemos(DBConversionParms parms)
	{
		parms.Dmo.RebuildTable(null, parms.User, parms.DataDictionary, parms.DatabaseName, "PartMemos", new DmoField[45]
		{
			new DmoField("imkPartID", "nvarchar", 30, 0, nullable: false),
			new DmoField("imkPartRevisionID", "nvarchar", 15, 0, nullable: false),
			new DmoField("imkPartMemoID", "smallint", 4, 0, nullable: false),
			new DmoField("imkMemoDate", "date", 14, 0, nullable: true),
			new DmoField("imkShowInInspections", "bit", 1, 0, nullable: false),
			new DmoField("imkShortDescription", "nvarchar", 50, 0, nullable: false),
			new DmoField("imkLongDescriptionRTF", "nvarchar(max)", 50, 0, nullable: true),
			new DmoField("imkLongDescriptionText", "nvarchar(max)", 50, 0, nullable: true),
			new DmoField("imkShowInPriceAndAvailability", "bit", 1, 0, nullable: false),
			new DmoField("imkShowInCalls", "bit", 1, 0, nullable: false),
			new DmoField("imkShowInLeads", "bit", 1, 0, nullable: false),
			new DmoField("imkShowInSalesOrders", "bit", 1, 0, nullable: false),
			new DmoField("imkShowInServiceContracts", "bit", 1, 0, nullable: false),
			new DmoField("imkShowInShipments", "bit", 1, 0, nullable: false),
			new DmoField("imkShowInARInvoices", "bit", 1, 0, nullable: false),
			new DmoField("imkShowInNonconformances", "bit", 1, 0, nullable: false),
			new DmoField("imkShowInRFQs", "bit", 1, 0, nullable: false),
			new DmoField("imkShowInPurchaseOrders", "bit", 1, 0, nullable: false),
			new DmoField("imkShowInReceipts", "bit", 1, 0, nullable: false),
			new DmoField("imkShowInAPInvoices", "bit", 1, 0, nullable: false),
			new DmoField("imkShowInRMAClaims", "bit", 1, 0, nullable: false),
			new DmoField("imkShowInRMAReceipts", "bit", 1, 0, nullable: false),
			new DmoField("imkShowInDMRClaims", "bit", 1, 0, nullable: false),
			new DmoField("imkShowInDMRShipments", "bit", 1, 0, nullable: false),
			new DmoField("imkShowInChangeRequests", "bit", 1, 0, nullable: false),
			new DmoField("imkShowInKnowledgebasePages", "bit", 1, 0, nullable: false),
			new DmoField("imkShowInQualityRegisters", "bit", 1, 0, nullable: false),
			new DmoField("imkShowInWarehouseRequisitions", "bit", 1, 0, nullable: false),
			new DmoField("imkShowInWarehouseTransfers", "bit", 1, 0, nullable: false),
			new DmoField("imkShowInWarehouseReceipts", "bit", 1, 0, nullable: false),
			new DmoField("imkShowInJobs", "bit", 1, 0, nullable: false),
			new DmoField("imkShowInJobAssemblies", "bit", 1, 0, nullable: false),
			new DmoField("imkShowInJobMaterials", "bit", 1, 0, nullable: false),
			new DmoField("imkShowInJobOperations", "bit", 1, 0, nullable: false),
			new DmoField("imkShowInQuoteLines", "bit", 1, 0, nullable: false),
			new DmoField("imkShowInQuoteAssemblies", "bit", 1, 0, nullable: false),
			new DmoField("imkShowInQuoteMaterials", "bit", 1, 0, nullable: false),
			new DmoField("imkShowInQuoteOperations", "bit", 1, 0, nullable: false),
			new DmoField("imkShowInPartRevisions", "bit", 1, 0, nullable: false),
			new DmoField("imkShowInPartAssemblies", "bit", 1, 0, nullable: false),
			new DmoField("imkShowInPartMaterials", "bit", 1, 0, nullable: false),
			new DmoField("imkShowInPartOperations", "bit", 1, 0, nullable: false),
			new DmoField("imkCreatedBy", "nvarchar", 20, 0, nullable: false),
			new DmoField("imkCreatedDate", "datetime", 14, 0, nullable: true),
			new DmoField("imkUniqueID", "uniqueidentifier", 16, 0, nullable: false)
		}, new DmoIndex[41]
		{
			new DmoIndex("IMKPARTID,IMKPARTREVISIONID,IMKPARTMEMOID", unique: true),
			new DmoIndex("IMKUNIQUEID", unique: true),
			new DmoIndex("imkPartID", unique: false),
			new DmoIndex("imkPartRevisionID", unique: false),
			new DmoIndex("imkPartMemoID", unique: false),
			new DmoIndex("imkMemoDate", unique: false),
			new DmoIndex("imkShowInInspections", unique: false),
			new DmoIndex("imkShowInPriceAndAvailability", unique: false),
			new DmoIndex("imkShowInCalls", unique: false),
			new DmoIndex("imkShowInLeads", unique: false),
			new DmoIndex("imkShowInSalesOrders", unique: false),
			new DmoIndex("imkShowInServiceContracts", unique: false),
			new DmoIndex("imkShowInShipments", unique: false),
			new DmoIndex("imkShowInARInvoices", unique: false),
			new DmoIndex("imkShowInNonconformances", unique: false),
			new DmoIndex("imkShowInRFQs", unique: false),
			new DmoIndex("imkShowInPurchaseOrders", unique: false),
			new DmoIndex("imkShowInReceipts", unique: false),
			new DmoIndex("imkShowInAPInvoices", unique: false),
			new DmoIndex("imkShowInRMAClaims", unique: false),
			new DmoIndex("imkShowInRMAReceipts", unique: false),
			new DmoIndex("imkShowInDMRClaims", unique: false),
			new DmoIndex("imkShowInDMRShipments", unique: false),
			new DmoIndex("imkShowInChangeRequests", unique: false),
			new DmoIndex("imkShowInKnowledgebasePages", unique: false),
			new DmoIndex("imkShowInQualityRegisters", unique: false),
			new DmoIndex("imkShowInWarehouseRequisitions", unique: false),
			new DmoIndex("imkShowInWarehouseTransfers", unique: false),
			new DmoIndex("imkShowInWarehouseReceipts", unique: false),
			new DmoIndex("imkShowInJobs", unique: false),
			new DmoIndex("imkShowInJobAssemblies", unique: false),
			new DmoIndex("imkShowInJobMaterials", unique: false),
			new DmoIndex("imkShowInJobOperations", unique: false),
			new DmoIndex("imkShowInQuoteLines", unique: false),
			new DmoIndex("imkShowInQuoteAssemblies", unique: false),
			new DmoIndex("imkShowInQuoteMaterials", unique: false),
			new DmoIndex("imkShowInQuoteOperations", unique: false),
			new DmoIndex("imkShowInPartRevisions", unique: false),
			new DmoIndex("imkShowInPartAssemblies", unique: false),
			new DmoIndex("imkShowInPartMaterials", unique: false),
			new DmoIndex("imkShowInPartOperations", unique: false)
		}, mergeCustomFields: true, disableTriggers: true);
	}
}
