using M1.Core;

namespace M1.Ax.Erp.DD;

[DBConversion("8.10.050", "Convert PartTransactions to support unicode", "2013-10-17")]
public class v810RebuildPartTransactions
{
	public v810RebuildPartTransactions(DBConversionParms parms)
	{
		parms.Dmo.RebuildTable(null, parms.User, parms.DataDictionary, parms.DatabaseName, "PartTransactions", new DmoField[123]
		{
			new DmoField("imtPartTransactionID", "int", 9, 0, nullable: false),
			new DmoField("imtTableName", "nvarchar", 30, 0, nullable: false),
			new DmoField("imtTableUniqueID", "uniqueidentifier", 16, 0, nullable: false),
			new DmoField("imtTransactionType", "tinyint", 1, 0, nullable: false),
			new DmoField("imtSource", "tinyint", 2, 0, nullable: false),
			new DmoField("imtReceiptType", "tinyint", 1, 0, nullable: false),
			new DmoField("imtIssueType", "tinyint", 1, 0, nullable: false),
			new DmoField("imtNonInventoryTransaction", "bit", 1, 0, nullable: false),
			new DmoField("imtPurchaseOrderID", "nvarchar", 10, 0, nullable: false),
			new DmoField("imtPurchaseOrderLineID", "smallint", 4, 0, nullable: false),
			new DmoField("imtJobID", "nvarchar", 20, 0, nullable: false),
			new DmoField("imtJobAssemblyID", "int", 5, 0, nullable: false),
			new DmoField("imtJobType", "tinyint", 1, 0, nullable: false),
			new DmoField("imtJobMaterialID", "int", 5, 0, nullable: false),
			new DmoField("imtJobMaterialComponentID", "int", 5, 0, nullable: false),
			new DmoField("imtJobOperationID", "int", 5, 0, nullable: false),
			new DmoField("imtJobCompleteStatus", "bit", 1, 0, nullable: false),
			new DmoField("imtPartID", "nvarchar", 30, 0, nullable: false),
			new DmoField("imtPartRevisionID", "nvarchar", 15, 0, nullable: false),
			new DmoField("imtPartWarehouseLocationID", "nvarchar", 5, 0, nullable: false),
			new DmoField("imtPartBinID", "nvarchar", 15, 0, nullable: false),
			new DmoField("imtSupplierOrganizationID", "nvarchar", 10, 0, nullable: false),
			new DmoField("imtPurchaseLocationID", "nvarchar", 5, 0, nullable: false),
			new DmoField("imtPreviousQuantityOnHand", "numeric", 15, 5, nullable: false),
			new DmoField("imtInventoryQuantityReceived", "numeric", 15, 5, nullable: false),
			new DmoField("imtScrapQuantity", "numeric", 15, 5, nullable: false),
			new DmoField("imtInspectionStatus", "nvarchar", 1, 0, nullable: false),
			new DmoField("imtQuantityToInspect", "numeric", 15, 5, nullable: false),
			new DmoField("imtQuantityToReturn", "numeric", 15, 5, nullable: false),
			new DmoField("imtPurchaseQuantityReceived", "numeric", 15, 5, nullable: false),
			new DmoField("imtPurchaseUnitOfMeasure", "nvarchar", 2, 0, nullable: false),
			new DmoField("imtInventoryUnitOfMeasure", "nvarchar", 2, 0, nullable: false),
			new DmoField("imtPurchaseUnitCost", "numeric", 15, 5, nullable: false),
			new DmoField("imtSetupCharge", "numeric", 9, 2, nullable: false),
			new DmoField("imtPOLineReceivedComplete", "bit", 1, 0, nullable: false),
			new DmoField("imtReference", "nvarchar", 30, 0, nullable: false),
			new DmoField("imtHeatLot", "nvarchar", 50, 0, nullable: false),
			new DmoField("imtTransactionDate", "datetime", 14, 0, nullable: true),
			new DmoField("imtUserID", "nvarchar", 20, 0, nullable: false),
			new DmoField("imtUnitLaborCost", "numeric", 15, 5, nullable: false),
			new DmoField("imtPrevUnitLaborCost", "numeric", 15, 5, nullable: false),
			new DmoField("imtPrevUnitOverheadCost", "numeric", 15, 5, nullable: false),
			new DmoField("imtUnitOverheadCost", "numeric", 15, 5, nullable: false),
			new DmoField("imtUnitMaterialCost", "numeric", 15, 5, nullable: false),
			new DmoField("imtPrevUnitMaterialCost", "numeric", 15, 5, nullable: false),
			new DmoField("imtPrevUnitSubcontractCost", "numeric", 15, 5, nullable: false),
			new DmoField("imtUnitSubcontractCost", "numeric", 15, 5, nullable: false),
			new DmoField("imtSalesOrderID", "nvarchar", 10, 0, nullable: false),
			new DmoField("imtShipmentID", "nvarchar", 10, 0, nullable: false),
			new DmoField("imtShipmentLineID", "smallint", 4, 0, nullable: false),
			new DmoField("imtShipmentComponentID", "smallint", 4, 0, nullable: false),
			new DmoField("imtReceiptID", "nvarchar", 10, 0, nullable: false),
			new DmoField("imtReceiptLineID", "smallint", 4, 0, nullable: false),
			new DmoField("imtReceiptComponentID", "smallint", 4, 0, nullable: false),
			new DmoField("imtRequiresInspection", "bit", 1, 0, nullable: false),
			new DmoField("imtDMRShipmentID", "nvarchar", 10, 0, nullable: false),
			new DmoField("imtDMRShipmentLineID", "smallint", 4, 0, nullable: false),
			new DmoField("imtRMAReceiptID", "nvarchar", 10, 0, nullable: false),
			new DmoField("imtRMAReceiptLineID", "smallint", 4, 0, nullable: false),
			new DmoField("imtInspectionID", "nvarchar", 10, 0, nullable: false),
			new DmoField("imtInspectionLineID", "smallint", 4, 0, nullable: false),
			new DmoField("imtEstUnitMaterialCost", "numeric", 15, 5, nullable: false),
			new DmoField("imtEstUnitSubcontractCost", "numeric", 15, 5, nullable: false),
			new DmoField("imtEstUnitLaborCost", "numeric", 15, 5, nullable: false),
			new DmoField("imtEstUnitOverheadCost", "numeric", 15, 5, nullable: false),
			new DmoField("imtEstUnitCostOfGoodsSold", "numeric", 15, 5, nullable: false),
			new DmoField("imtEstTotalMaterialCost", "money", 12, 2, nullable: false),
			new DmoField("imtEstTotalSubcontractCost", "money", 12, 2, nullable: false),
			new DmoField("imtEstTotalLaborCost", "money", 12, 2, nullable: false),
			new DmoField("imtEstTotalOverheadCost", "money", 12, 2, nullable: false),
			new DmoField("imtEstTotalCostOfGoodsSold", "money", 12, 2, nullable: false),
			new DmoField("imtActualUnitMaterialCost", "numeric", 15, 5, nullable: false),
			new DmoField("imtActualUnitSubcontractCost", "numeric", 15, 5, nullable: false),
			new DmoField("imtActualUnitLaborCost", "numeric", 15, 5, nullable: false),
			new DmoField("imtActualUnitOverheadCost", "numeric", 15, 5, nullable: false),
			new DmoField("imtActualUnitCostOfGoodsSold", "numeric", 15, 5, nullable: false),
			new DmoField("imtActualTotalMaterialCost", "money", 12, 2, nullable: false),
			new DmoField("imtActualTotalSubcontractCost", "money", 12, 2, nullable: false),
			new DmoField("imtActualTotalLaborCost", "money", 12, 2, nullable: false),
			new DmoField("imtActualTotalOverheadCost", "money", 12, 2, nullable: false),
			new DmoField("imtActualTotalCostOfGoodsSold", "money", 12, 2, nullable: false),
			new DmoField("imtCOGSCalculatedDate", "datetime", 14, 0, nullable: true),
			new DmoField("imtCOGSPostedToGL", "bit", 1, 0, nullable: false),
			new DmoField("imtPOSTransactionID", "nvarchar", 10, 0, nullable: false),
			new DmoField("imtPOSTransactionLineID", "smallint", 4, 0, nullable: false),
			new DmoField("imtInventoryCountID", "int", 9, 0, nullable: false),
			new DmoField("imtInventoryCountLineID", "int", 7, 0, nullable: false),
			new DmoField("imtWarehouseTransferID", "nvarchar", 10, 0, nullable: false),
			new DmoField("imtWarehouseTransferLineID", "smallint", 4, 0, nullable: false),
			new DmoField("imtWarehouseReceiptID", "nvarchar", 10, 0, nullable: false),
			new DmoField("imtWarehouseReceiptLineID", "smallint", 4, 0, nullable: false),
			new DmoField("imtProjectID", "nvarchar", 10, 0, nullable: false),
			new DmoField("imtProjectAreaID", "nvarchar", 15, 0, nullable: false),
			new DmoField("imtPlantID", "nvarchar", 5, 0, nullable: false),
			new DmoField("imtWarehouseTransComponentID", "smallint", 4, 0, nullable: false),
			new DmoField("imtWarehouseReceiptComponentID", "smallint", 4, 0, nullable: false),
			new DmoField("imtNonNettable", "bit", 1, 0, nullable: false),
			new DmoField("imtUnitDutyCost", "numeric", 15, 5, nullable: false),
			new DmoField("imtEstUnitDutyCost", "numeric", 15, 5, nullable: false),
			new DmoField("imtEstTotalDutyCost", "money", 12, 2, nullable: false),
			new DmoField("imtActualUnitDutyCost", "numeric", 15, 5, nullable: false),
			new DmoField("imtActualTotalDutyCost", "money", 12, 2, nullable: false),
			new DmoField("imtPrevUnitDutyCost", "numeric", 15, 5, nullable: false),
			new DmoField("imtCreatedBy", "nvarchar", 20, 0, nullable: false),
			new DmoField("imtUnitFreightCost", "numeric", 15, 5, nullable: false),
			new DmoField("imtCreatedDate", "datetime", 14, 0, nullable: true),
			new DmoField("imtEstUnitFreightCost", "numeric", 15, 5, nullable: false),
			new DmoField("imtUniqueID", "uniqueidentifier", 16, 0, nullable: false),
			new DmoField("imtEstTotalFreightCost", "money", 12, 2, nullable: false),
			new DmoField("imtActualUnitFreightCost", "numeric", 15, 5, nullable: false),
			new DmoField("imtActualTotalFreightCost", "money", 12, 2, nullable: false),
			new DmoField("imtPrevUnitFreightCost", "numeric", 15, 5, nullable: false),
			new DmoField("imtUnitMiscCost", "numeric", 15, 5, nullable: false),
			new DmoField("imtEstUnitMiscCost", "numeric", 15, 5, nullable: false),
			new DmoField("imtEstTotalMiscCost", "money", 12, 2, nullable: false),
			new DmoField("imtActualUnitMiscCost", "numeric", 15, 5, nullable: false),
			new DmoField("imtActualTotalMiscCost", "money", 12, 2, nullable: false),
			new DmoField("imtPrevUnitMiscCost", "numeric", 15, 5, nullable: false),
			new DmoField("imtMiscIssueReasonID", "nvarchar", 5, 0, nullable: false),
			new DmoField("imtUnitCostAverage", "numeric", 15, 5, nullable: false),
			new DmoField("imtUnitCostLast", "numeric", 15, 5, nullable: false),
			new DmoField("imtUnitCostStandard", "numeric", 15, 5, nullable: false),
			new DmoField("imtCreatedFromMobile", "bit", 1, 0, nullable: false)
		}, new DmoIndex[24]
		{
			new DmoIndex("IMTPARTTRANSACTIONID", unique: true),
			new DmoIndex("IMTUNIQUEID", unique: true),
			new DmoIndex("imtTableName", unique: false),
			new DmoIndex("imtTableUniqueID", unique: false),
			new DmoIndex("imtTransactionType", unique: false),
			new DmoIndex("imtReceiptType", unique: false),
			new DmoIndex("imtIssueType", unique: false),
			new DmoIndex("imtJobID", unique: false),
			new DmoIndex("imtJobAssemblyID", unique: false),
			new DmoIndex("imtJobType", unique: false),
			new DmoIndex("imtJobMaterialID", unique: false),
			new DmoIndex("imtJobMaterialComponentID", unique: false),
			new DmoIndex("imtJobOperationID", unique: false),
			new DmoIndex("imtPartID", unique: false),
			new DmoIndex("imtPartRevisionID", unique: false),
			new DmoIndex("imtPartWarehouseLocationID", unique: false),
			new DmoIndex("imtPartBinID", unique: false),
			new DmoIndex("imtInventoryQuantityReceived", unique: false),
			new DmoIndex("imtInspectionStatus", unique: false),
			new DmoIndex("imtTransactionDate", unique: false),
			new DmoIndex("imtInventoryCountID", unique: false),
			new DmoIndex("imtInventoryCountLineID", unique: false),
			new DmoIndex("imtPlantID", unique: false),
			new DmoIndex("imtNonNettable", unique: false)
		}, mergeCustomFields: true, disableTriggers: true);
	}
}
