using M1.Core;

namespace M1.Ax.Erp.DD;

[DBConversion("8.10.050", "Convert JobMaterials to support unicode", "2013-10-17")]
public class v810RebuildJobMaterials
{
	public v810RebuildJobMaterials(DBConversionParms parms)
	{
		parms.Dmo.RebuildTable(null, parms.User, parms.DataDictionary, parms.DatabaseName, "JobMaterials", new DmoField[72]
		{
			new DmoField("jmmJobID", "nvarchar", 20, 0, nullable: false),
			new DmoField("jmmJobAssemblyID", "int", 5, 0, nullable: false),
			new DmoField("jmmJobMaterialID", "int", 5, 0, nullable: false),
			new DmoField("jmmPartID", "nvarchar", 30, 0, nullable: false),
			new DmoField("jmmPartRevisionID", "nvarchar", 15, 0, nullable: false),
			new DmoField("jmmPartWarehouseLocationID", "nvarchar", 5, 0, nullable: false),
			new DmoField("jmmPartBinID", "nvarchar", 15, 0, nullable: false),
			new DmoField("jmmUnitOfMeasure", "nvarchar", 2, 0, nullable: false),
			new DmoField("jmmPartShortDescription", "nvarchar", 50, 0, nullable: false),
			new DmoField("jmmPartLongDescriptionRTF", "nvarchar(max)", 50, 0, nullable: true),
			new DmoField("jmmPartLongDescriptionText", "nvarchar(max)", 50, 0, nullable: true),
			new DmoField("jmmQuantityPerAssembly", "numeric", 13, 6, nullable: false),
			new DmoField("jmmScrapPercent", "numeric", 6, 2, nullable: false),
			new DmoField("jmmScrapQuantity", "numeric", 15, 5, nullable: false),
			new DmoField("jmmEstimatedQuantity", "numeric", 15, 5, nullable: false),
			new DmoField("jmmEstimatedUnitCost", "numeric", 15, 5, nullable: false),
			new DmoField("jmmMinimumCharge", "numeric", 8, 2, nullable: false),
			new DmoField("jmmCalculatedUnitCost", "numeric", 15, 5, nullable: false),
			new DmoField("jmmKitPart", "bit", 1, 0, nullable: false),
			new DmoField("jmmQuantityBreak1", "numeric", 15, 5, nullable: false),
			new DmoField("jmmUnitCost1", "numeric", 15, 5, nullable: false),
			new DmoField("jmmQuantityBreak2", "numeric", 15, 5, nullable: false),
			new DmoField("jmmUnitCost2", "numeric", 15, 5, nullable: false),
			new DmoField("jmmQuantityBreak3", "numeric", 15, 5, nullable: false),
			new DmoField("jmmUnitCost3", "numeric", 15, 5, nullable: false),
			new DmoField("jmmQuantityBreak4", "numeric", 15, 5, nullable: false),
			new DmoField("jmmUnitCost4", "numeric", 15, 5, nullable: false),
			new DmoField("jmmQuantityBreak5", "numeric", 15, 5, nullable: false),
			new DmoField("jmmUnitCost5", "numeric", 15, 5, nullable: false),
			new DmoField("jmmQuantityBreak6", "numeric", 15, 5, nullable: false),
			new DmoField("jmmUnitCost6", "numeric", 15, 5, nullable: false),
			new DmoField("jmmQuantityBreak7", "numeric", 15, 5, nullable: false),
			new DmoField("jmmUnitCost7", "numeric", 15, 5, nullable: false),
			new DmoField("jmmQuantityBreak8", "numeric", 15, 5, nullable: false),
			new DmoField("jmmUnitCost8", "numeric", 15, 5, nullable: false),
			new DmoField("jmmQuantityBreak9", "numeric", 15, 5, nullable: false),
			new DmoField("jmmUnitCost9", "numeric", 15, 5, nullable: false),
			new DmoField("jmmSupplierOrganizationID", "nvarchar", 10, 0, nullable: false),
			new DmoField("jmmPurchaseLocationID", "nvarchar", 5, 0, nullable: false),
			new DmoField("jmmFirm", "bit", 1, 0, nullable: false),
			new DmoField("jmmPurchaseOrderID", "nvarchar", 10, 0, nullable: false),
			new DmoField("jmmLeadTime", "smallint", 3, 0, nullable: false),
			new DmoField("jmmDueInDate", "date", 14, 0, nullable: true),
			new DmoField("jmmOrderByDate", "date", 14, 0, nullable: true),
			new DmoField("jmmQuantityAllocated", "numeric", 15, 5, nullable: false),
			new DmoField("jmmQuantityToReturn", "numeric", 15, 5, nullable: false),
			new DmoField("jmmRequiredDate", "date", 14, 0, nullable: true),
			new DmoField("jmmQuantityReceived", "numeric", 15, 5, nullable: false),
			new DmoField("jmmScrapQuantityReceived", "numeric", 15, 5, nullable: false),
			new DmoField("jmmReceivedComplete", "bit", 1, 0, nullable: false),
			new DmoField("jmmRelatedJobOperationID", "int", 5, 0, nullable: false),
			new DmoField("jmmBackflush", "bit", 1, 0, nullable: false),
			new DmoField("jmmClosed", "bit", 1, 0, nullable: false),
			new DmoField("jmmQuantityToInspect", "numeric", 15, 5, nullable: false),
			new DmoField("jmmRFQID", "nvarchar", 10, 0, nullable: false),
			new DmoField("jmmDocuments", "nvarchar(max)", 50, 0, nullable: true),
			new DmoField("jmmLeadTime1", "smallint", 3, 0, nullable: false),
			new DmoField("jmmLeadTime2", "smallint", 3, 0, nullable: false),
			new DmoField("jmmLeadTime3", "smallint", 3, 0, nullable: false),
			new DmoField("jmmLeadTime4", "smallint", 3, 0, nullable: false),
			new DmoField("jmmLeadTime5", "smallint", 3, 0, nullable: false),
			new DmoField("jmmLeadTime6", "smallint", 3, 0, nullable: false),
			new DmoField("jmmLeadTime7", "smallint", 3, 0, nullable: false),
			new DmoField("jmmLeadTime8", "smallint", 3, 0, nullable: false),
			new DmoField("jmmLeadTime9", "smallint", 3, 0, nullable: false),
			new DmoField("jmmCostOverride", "bit", 1, 0, nullable: false),
			new DmoField("jmmPurchaseToJobQuantity", "numeric", 15, 5, nullable: false),
			new DmoField("jmmPullFromStockQuantity", "numeric", 15, 5, nullable: false),
			new DmoField("jmmPullAllFromStock", "bit", 1, 0, nullable: false),
			new DmoField("jmmCreatedBy", "nvarchar", 20, 0, nullable: false),
			new DmoField("jmmCreatedDate", "datetime", 14, 0, nullable: true),
			new DmoField("jmmUniqueID", "uniqueidentifier", 16, 0, nullable: false)
		}, new DmoIndex[21]
		{
			new DmoIndex("JMMJOBID,JMMJOBASSEMBLYID,JMMJOBMATERIALID", unique: true),
			new DmoIndex("JMMUNIQUEID", unique: true),
			new DmoIndex("jmmJobID", unique: false),
			new DmoIndex("jmmJobAssemblyID", unique: false),
			new DmoIndex("jmmJobMaterialID", unique: false),
			new DmoIndex("jmmPartID", unique: false),
			new DmoIndex("jmmPartRevisionID", unique: false),
			new DmoIndex("jmmPartWarehouseLocationID", unique: false),
			new DmoIndex("jmmPartBinID", unique: false),
			new DmoIndex("jmmKitPart", unique: false),
			new DmoIndex("jmmSupplierOrganizationID", unique: false),
			new DmoIndex("jmmPurchaseLocationID", unique: false),
			new DmoIndex("jmmRequiredDate", unique: false),
			new DmoIndex("jmmReceivedComplete", unique: false),
			new DmoIndex("jmmRelatedJobOperationID", unique: false),
			new DmoIndex("jmmBackflush", unique: false),
			new DmoIndex("jmmClosed", unique: false),
			new DmoIndex("jmmCostOverride", unique: false),
			new DmoIndex("jmmPurchaseToJobQuantity", unique: false),
			new DmoIndex("jmmPullFromStockQuantity", unique: false),
			new DmoIndex("jmmPullAllFromStock", unique: false)
		}, mergeCustomFields: true, disableTriggers: true);
	}
}
