using M1.Core;

namespace M1.Ax.Erp.DD;

[DBConversion("8.10.050", "Convert ARInvoiceLines to support unicode", "2013-10-17")]
public class v810RebuildARInvoiceLines
{
	public v810RebuildARInvoiceLines(DBConversionParms parms)
	{
		parms.Dmo.RebuildTable(null, parms.User, parms.DataDictionary, parms.DatabaseName, "ARInvoiceLines", new DmoField[109]
		{
			new DmoField("arlARInvoiceID", "nvarchar", 10, 0, nullable: false),
			new DmoField("arlARInvoiceLineID", "smallint", 4, 0, nullable: false),
			new DmoField("arlLineType", "tinyint", 1, 0, nullable: false),
			new DmoField("arlPartID", "nvarchar", 30, 0, nullable: false),
			new DmoField("arlOrgPartID", "nvarchar", 30, 0, nullable: false),
			new DmoField("arlPartRevisionID", "nvarchar", 15, 0, nullable: false),
			new DmoField("arlUnitOfMeasure", "nvarchar", 2, 0, nullable: false),
			new DmoField("arlPartShortDescription", "nvarchar", 50, 0, nullable: false),
			new DmoField("arlOrgPartShortDescription", "nvarchar", 50, 0, nullable: false),
			new DmoField("arlPartLongDescriptionRTF", "nvarchar(max)", 50, 0, nullable: true),
			new DmoField("arlPartLongDescriptionText", "nvarchar(max)", 50, 0, nullable: true),
			new DmoField("arlPartGroupID", "nvarchar", 5, 0, nullable: false),
			new DmoField("arlOrderQuantity", "numeric", 15, 5, nullable: false),
			new DmoField("arlInvoiceQuantity", "numeric", 15, 5, nullable: false),
			new DmoField("arlFullUnitPriceBase", "numeric", 15, 5, nullable: false),
			new DmoField("arlFullUnitPriceForeign", "numeric", 15, 5, nullable: false),
			new DmoField("arlDiscountPercent", "numeric", 6, 2, nullable: false),
			new DmoField("arlUnitDiscountBase", "numeric", 15, 5, nullable: false),
			new DmoField("arlUnitDiscountForeign", "numeric", 15, 5, nullable: false),
			new DmoField("arlUnitPriceBase", "numeric", 15, 5, nullable: false),
			new DmoField("arlUnitPriceForeign", "numeric", 15, 5, nullable: false),
			new DmoField("arlFullExtendedPriceBase", "money", 12, 2, nullable: false),
			new DmoField("arlFullExtendedPriceForeign", "money", 12, 2, nullable: false),
			new DmoField("arlExtendedDiscountBase", "money", 12, 2, nullable: false),
			new DmoField("arlExtendedDiscountForeign", "money", 12, 2, nullable: false),
			new DmoField("arlExtendedPriceBase", "money", 12, 2, nullable: false),
			new DmoField("arlExtendedPriceForeign", "money", 12, 2, nullable: false),
			new DmoField("arlFreightAmountBase", "money", 12, 2, nullable: false),
			new DmoField("arlFreightAmountForeign", "money", 12, 2, nullable: false),
			new DmoField("arlTaxDate", "date", 14, 0, nullable: true),
			new DmoField("arlTaxCodeID", "nvarchar", 5, 0, nullable: false),
			new DmoField("arlNonTaxReasonID", "nvarchar", 5, 0, nullable: false),
			new DmoField("arlTaxAmountBase", "money", 14, 4, nullable: false),
			new DmoField("arlTaxAmountForeign", "money", 14, 4, nullable: false),
			new DmoField("arlSecondTaxCodeID", "nvarchar", 5, 0, nullable: false),
			new DmoField("arlSecondTaxAmountBase", "money", 14, 4, nullable: false),
			new DmoField("arlSecondTaxAmountForeign", "money", 14, 4, nullable: false),
			new DmoField("arlPayCommission", "bit", 1, 0, nullable: false),
			new DmoField("arlCommissionRate", "numeric", 5, 2, nullable: false),
			new DmoField("arlCommissionAmount", "money", 12, 2, nullable: false),
			new DmoField("arlAmtForResellerCommission", "money", 12, 2, nullable: false),
			new DmoField("arlAmtForSalesCommission", "money", 12, 2, nullable: false),
			new DmoField("arlCustomerPO", "nvarchar", 40, 0, nullable: false),
			new DmoField("arlSalesOrderID", "nvarchar", 10, 0, nullable: false),
			new DmoField("arlSalesOrderLineID", "smallint", 4, 0, nullable: false),
			new DmoField("arlSalesOrderDeliveryID", "smallint", 4, 0, nullable: false),
			new DmoField("arlDeliveryInvoicedComplete", "bit", 1, 0, nullable: false),
			new DmoField("arlShipmentID", "nvarchar", 10, 0, nullable: false),
			new DmoField("arlShipmentLineID", "smallint", 4, 0, nullable: false),
			new DmoField("arlAssetID", "nvarchar", 10, 0, nullable: false),
			new DmoField("arlEstUnitMaterialCost", "numeric", 15, 5, nullable: false),
			new DmoField("arlEstUnitSubcontractCost", "numeric", 15, 5, nullable: false),
			new DmoField("arlEstUnitLaborCost", "numeric", 15, 5, nullable: false),
			new DmoField("arlEstUnitOverheadCost", "numeric", 15, 5, nullable: false),
			new DmoField("arlEstUnitCostOfGoodsSold", "numeric", 15, 5, nullable: false),
			new DmoField("arlEstTotalMaterialCost", "money", 12, 2, nullable: false),
			new DmoField("arlEstTotalSubcontractCost", "money", 12, 2, nullable: false),
			new DmoField("arlEstTotalLaborCost", "money", 12, 2, nullable: false),
			new DmoField("arlEstTotalOverheadCost", "money", 12, 2, nullable: false),
			new DmoField("arlEstTotalCostOfGoodsSold", "money", 12, 2, nullable: false),
			new DmoField("arlActualUnitMaterialCost", "numeric", 15, 5, nullable: false),
			new DmoField("arlActualUnitSubcontractCost", "numeric", 15, 5, nullable: false),
			new DmoField("arlActualUnitLaborCost", "numeric", 15, 5, nullable: false),
			new DmoField("arlActualUnitOverheadCost", "numeric", 15, 5, nullable: false),
			new DmoField("arlActualUnitCostOfGoodsSold", "numeric", 15, 5, nullable: false),
			new DmoField("arlActualTotalMaterialCost", "money", 12, 2, nullable: false),
			new DmoField("arlActualTotalSubcontractCost", "money", 12, 2, nullable: false),
			new DmoField("arlActualTotalLaborCost", "money", 12, 2, nullable: false),
			new DmoField("arlActualTotalOverheadCost", "money", 12, 2, nullable: false),
			new DmoField("arlActualTotalCostOfGoodsSold", "money", 12, 2, nullable: false),
			new DmoField("arlCOGSCalculatedDate", "datetime", 14, 0, nullable: true),
			new DmoField("arlCOGSPostedToGL", "bit", 1, 0, nullable: false),
			new DmoField("arlRMAClaimID", "nvarchar", 10, 0, nullable: false),
			new DmoField("arlRMAClaimLineID", "smallint", 4, 0, nullable: false),
			new DmoField("arlRMAReceiptID", "nvarchar", 10, 0, nullable: false),
			new DmoField("arlRMAReceiptLineID", "smallint", 4, 0, nullable: false),
			new DmoField("arlProjectID", "nvarchar", 10, 0, nullable: false),
			new DmoField("arlProjectAreaID", "nvarchar", 15, 0, nullable: false),
			new DmoField("arlPOSSessionID", "nvarchar", 10, 0, nullable: false),
			new DmoField("arlPOSTransactionID", "nvarchar", 10, 0, nullable: false),
			new DmoField("arlPOSTransactionLineID", "smallint", 4, 0, nullable: false),
			new DmoField("arlIncludeTaxInRetention", "bit", 1, 0, nullable: false),
			new DmoField("arlRetentionPercent", "numeric", 6, 2, nullable: false),
			new DmoField("arlRetention", "bit", 1, 0, nullable: false),
			new DmoField("arlRetentionAmountBase", "money", 12, 2, nullable: false),
			new DmoField("arlRetentionAmountForeign", "money", 12, 2, nullable: false),
			new DmoField("arlRetentionDueDate", "datetime", 14, 0, nullable: true),
			new DmoField("arlARRecurringInvoiceID", "int", 6, 0, nullable: false),
			new DmoField("arlARRecurringInvoiceLineID", "smallint", 4, 0, nullable: false),
			new DmoField("arlPostedToGL", "bit", 1, 0, nullable: false),
			new DmoField("arlDepositLine", "bit", 1, 0, nullable: false),
			new DmoField("arlDepositInvoiceID", "nvarchar", 10, 0, nullable: false),
			new DmoField("arlDepositAmountBase", "money", 12, 2, nullable: false),
			new DmoField("arlDepositAmountForeign", "money", 12, 2, nullable: false),
			new DmoField("arlDepositBalanceBase", "money", 12, 2, nullable: false),
			new DmoField("arlDepositBalanceForeign", "money", 12, 2, nullable: false),
			new DmoField("arlDepositTransferredBase", "money", 12, 2, nullable: false),
			new DmoField("arlDepositTransferredForeign", "money", 12, 2, nullable: false),
			new DmoField("arlDepositInvoiceLineID", "smallint", 4, 0, nullable: false),
			new DmoField("arlCreatedBy", "nvarchar", 20, 0, nullable: false),
			new DmoField("arlCreatedDate", "datetime", 14, 0, nullable: true),
			new DmoField("arlUniqueID", "uniqueidentifier", 16, 0, nullable: false),
			new DmoField("arlCallID", "nvarchar", 10, 0, nullable: false),
			new DmoField("arlJobID", "nvarchar", 20, 0, nullable: false),
			new DmoField("arlJobAssemblyID", "int", 5, 0, nullable: false),
			new DmoField("arlJobMaterialID", "int", 5, 0, nullable: false),
			new DmoField("arlAssetAdjustmentID", "int", 9, 0, nullable: false),
			new DmoField("arlAvalaraIgnoreLine", "bit", 1, 0, nullable: false),
			new DmoField("arlFinanceSourceInvoiceID", "nvarchar", 10, 0, nullable: false)
		}, new DmoIndex[27]
		{
			new DmoIndex("ARLARINVOICEID,ARLARINVOICELINEID", unique: true),
			new DmoIndex("ARLUNIQUEID", unique: true),
			new DmoIndex("arlARInvoiceID", unique: false),
			new DmoIndex("arlARInvoiceLineID", unique: false),
			new DmoIndex("arlPartID", unique: false),
			new DmoIndex("arlOrgPartID", unique: false),
			new DmoIndex("arlPartRevisionID", unique: false),
			new DmoIndex("arlSalesOrderID", unique: false),
			new DmoIndex("arlSalesOrderLineID", unique: false),
			new DmoIndex("arlShipmentID", unique: false),
			new DmoIndex("arlShipmentLineID", unique: false),
			new DmoIndex("arlAssetID", unique: false),
			new DmoIndex("arlRMAClaimID", unique: false),
			new DmoIndex("arlRMAClaimLineID", unique: false),
			new DmoIndex("arlProjectID", unique: false),
			new DmoIndex("arlProjectAreaID", unique: false),
			new DmoIndex("arlPOSSessionID", unique: false),
			new DmoIndex("arlPOSTransactionID", unique: false),
			new DmoIndex("arlARRecurringInvoiceID", unique: false),
			new DmoIndex("arlARRecurringInvoiceLineID", unique: false),
			new DmoIndex("arlPostedToGL", unique: false),
			new DmoIndex("arlDepositInvoiceID", unique: false),
			new DmoIndex("arlCallID", unique: false),
			new DmoIndex("arlJobID", unique: false),
			new DmoIndex("arlJobAssemblyID", unique: false),
			new DmoIndex("arlJobMaterialID", unique: false),
			new DmoIndex("arlAssetAdjustmentID", unique: false)
		}, mergeCustomFields: true, disableTriggers: true);
	}
}
