using M1.Core;

namespace M1.Ax.Erp.DD;

[DBConversion("8.10.050", "Convert Form941YearQuarters to support unicode", "2013-10-17")]
public class v810RebuildForm941YearQuarters
{
	public v810RebuildForm941YearQuarters(DBConversionParms parms)
	{
		parms.Dmo.RebuildTable(null, parms.User, parms.DataDictionary, parms.DatabaseName, "Form941YearQuarters", new DmoField[91]
		{
			new DmoField("ptqYearID", "smallint", 4, 0, nullable: false),
			new DmoField("ptqQuarterID", "tinyint", 1, 0, nullable: false),
			new DmoField("ptqPlantID", "nvarchar", 5, 0, nullable: false),
			new DmoField("ptqNumberOfEmployees", "int", 6, 0, nullable: false),
			new DmoField("ptqCompensation", "money", 10, 2, nullable: false),
			new DmoField("ptqTaxWithheld", "money", 10, 2, nullable: false),
			new DmoField("ptqNoCompensation", "bit", 1, 0, nullable: false),
			new DmoField("ptqTaxableSSWages", "money", 10, 2, nullable: false),
			new DmoField("ptqTaxableSSTips", "money", 10, 2, nullable: false),
			new DmoField("ptqTaxableMCCompensation", "money", 10, 2, nullable: false),
			new DmoField("ptqTotalTaxes", "money", 10, 2, nullable: false),
			new DmoField("ptqSSWageTax", "money", 10, 2, nullable: false),
			new DmoField("ptqSSTipsTax", "money", 10, 2, nullable: false),
			new DmoField("ptqMCCompensationTax", "money", 10, 2, nullable: false),
			new DmoField("ptqTaxBeforeAdjust", "money", 10, 2, nullable: false),
			new DmoField("ptqAdjustFractionCents", "money", 10, 2, nullable: false),
			new DmoField("ptqAdjustSickPay", "money", 10, 2, nullable: false),
			new DmoField("ptqAdjustTipLifeInsurance", "money", 10, 2, nullable: false),
			new DmoField("ptqTotalAdjustments", "money", 10, 2, nullable: false),
			new DmoField("ptqTotalTaxAfterAdjustments", "money", 10, 2, nullable: false),
			new DmoField("ptqAdvanceEICPayments", "money", 10, 2, nullable: false),
			new DmoField("ptqTotalTaxAfterEICAdjust", "money", 10, 2, nullable: false),
			new DmoField("ptqTotalDepositsForQuarter", "money", 10, 2, nullable: false),
			new DmoField("ptqCOBRAPayments", "money", 10, 2, nullable: false),
			new DmoField("ptqCOBRAEmployees", "int", 6, 0, nullable: false),
			new DmoField("ptqTotalDepositsIncCOBRA", "money", 10, 2, nullable: false),
			new DmoField("ptqBalanceDue", "money", 10, 2, nullable: false),
			new DmoField("ptqOverpayment", "money", 10, 2, nullable: false),
			new DmoField("ptqOverpaymentOption", "tinyint", 1, 0, nullable: false),
			new DmoField("ptqState", "nvarchar", 2, 0, nullable: false),
			new DmoField("ptqDepositFrequency", "tinyint", 1, 0, nullable: false),
			new DmoField("ptqBusinessClosed", "bit", 1, 0, nullable: false),
			new DmoField("ptqBusinessClosedDate", "date", 14, 0, nullable: true),
			new DmoField("ptqSeasonalEmployer", "bit", 1, 0, nullable: false),
			new DmoField("ptqThirdParty", "tinyint", 1, 0, nullable: false),
			new DmoField("ptqThirdPartyName", "nvarchar", 50, 0, nullable: false),
			new DmoField("ptqThirdPartyPhone", "nvarchar", 20, 0, nullable: false),
			new DmoField("ptqThirdPartyPIN", "nvarchar", 5, 0, nullable: false),
			new DmoField("ptqAuthorisedPerson", "nvarchar", 50, 0, nullable: false),
			new DmoField("ptqAuthorisedPersonTitle", "nvarchar", 50, 0, nullable: false),
			new DmoField("ptqAuthorisedPersonPhone", "nvarchar", 20, 0, nullable: false),
			new DmoField("ptqDate", "date", 14, 0, nullable: true),
			new DmoField("ptqMonth1", "money", 10, 2, nullable: false),
			new DmoField("ptqMonth2", "money", 10, 2, nullable: false),
			new DmoField("ptqMonth3", "money", 10, 2, nullable: false),
			new DmoField("ptqClosed", "bit", 1, 0, nullable: false),
			new DmoField("ptqTotalLiability", "money", 10, 2, nullable: false),
			new DmoField("ptqSSTaxRate", "numeric", 5, 4, nullable: false),
			new DmoField("ptqDescription", "nvarchar", 12, 0, nullable: false),
			new DmoField("ptqTipsTaxRate", "numeric", 5, 4, nullable: false),
			new DmoField("ptqMCTaxRate", "numeric", 5, 4, nullable: false),
			new DmoField("ptqCreatedBy", "nvarchar", 20, 0, nullable: false),
			new DmoField("ptqCreatedDate", "date", 14, 0, nullable: true),
			new DmoField("ptqUniqueID", "uniqueidentifier", 16, 0, nullable: false),
			new DmoField("ptqTaxableAdditionalMedicare", "money", 10, 2, nullable: false),
			new DmoField("ptqAdditionalMedicareRate", "numeric", 5, 4, nullable: false),
			new DmoField("ptqAdditionalMedicareTax", "money", 10, 2, nullable: false),
			new DmoField("ptqTaxDueOnUnreportedTips", "money", 10, 2, nullable: false),
			new DmoField("ptqAbleSickLeaveWages", "money", 12, 2, nullable: false),
			new DmoField("ptqAbleSickLeaveWagesRate", "numeric", 5, 4, nullable: false),
			new DmoField("ptqAbleSickLeaveWagesTotal", "money", 12, 2, nullable: false),
			new DmoField("ptqAbleFamilyLeaveWages", "money", 12, 2, nullable: false),
			new DmoField("ptqAbleFamilyLeaveWagesRate", "numeric", 5, 4, nullable: false),
			new DmoField("ptqAbleFamilyLeaveWagesTotal", "money", 12, 2, nullable: false),
			new DmoField("ptqQualifiedSmallTaxCredit", "money", 12, 2, nullable: false),
			new DmoField("ptqNonrefundablePortionCredit", "money", 12, 2, nullable: false),
			new DmoField("ptqNonPortionRetentionCredit", "money", 12, 2, nullable: false),
			new DmoField("ptqNonPortionCreditWages", "money", 12, 2, nullable: false),
			new DmoField("ptqNonrefundablePortionCobra", "money", 12, 2, nullable: false),
			new DmoField("ptqNumberIndividualsCobra", "money", 12, 2, nullable: false),
			new DmoField("ptqTotalNonrefundableCredits", "money", 12, 2, nullable: false),
			new DmoField("ptqTotalTaxesAdjustCredits", "money", 12, 2, nullable: false),
			new DmoField("ptqReservedFutureUse", "money", 12, 2, nullable: false),
			new DmoField("ptqRefunPortionCreditWages", "money", 12, 2, nullable: false),
			new DmoField("ptqRefunPortionEmployeeCredit", "money", 12, 2, nullable: false),
			new DmoField("ptqRefPortionCreditWages", "money", 12, 2, nullable: false),
			new DmoField("ptqRefunPortionCobraCredit", "money", 12, 2, nullable: false),
			new DmoField("ptqTotalDepositsRefunCredits", "money", 12, 2, nullable: false),
			new DmoField("ptqTotalAdvReceivedFilingForms", "money", 12, 2, nullable: false),
			new DmoField("ptqTotalDepositsLessAdvances", "money", 12, 2, nullable: false),
			new DmoField("ptqEmployeeRetentionCredit", "bit", 1, 0, nullable: false),
			new DmoField("ptqAblePlanSickLeaveWages", "money", 12, 2, nullable: false),
			new DmoField("ptqAblePlanFamilyLeaveWages", "money", 12, 2, nullable: false),
			new DmoField("ptqAbleEmployeeRetentionCredit", "money", 12, 2, nullable: false),
			new DmoField("ptqAbleHealthEmployeeCredit", "money", 12, 2, nullable: false),
			new DmoField("ptqAbleSickLeaveAfterMarch31", "money", 12, 2, nullable: false),
			new DmoField("ptqAbleHealthWagesReported23", "money", 12, 2, nullable: false),
			new DmoField("ptqAmountsBargainedAllocable", "money", 12, 2, nullable: false),
			new DmoField("ptqAbleFamilyLeaveAfterMarch31", "money", 12, 2, nullable: false),
			new DmoField("ptqAbleHealthFamilyReported", "money", 12, 2, nullable: false),
			new DmoField("ptqAmtBargainedFamilyWages", "money", 12, 2, nullable: false)
		}, new DmoIndex[3]
		{
			new DmoIndex("PTQYEARID,PTQPLANTID,PTQQUARTERID", unique: true),
			new DmoIndex("PTQUNIQUEID", unique: true),
			new DmoIndex("ptqPlantID", unique: false)
		}, mergeCustomFields: true, disableTriggers: true);
	}
}
