using M1.Core;

namespace M1.Ax.Erp.DD;

[DBConversion("8.10.050", "Convert ShippingProperties to support unicode", "2013-10-17")]
public class v810RebuildShippingProperties
{
	public v810RebuildShippingProperties(DBConversionParms parms)
	{
		parms.Dmo.RebuildTable(null, parms.User, parms.DataDictionary, parms.DatabaseName, "ShippingProperties", new DmoField[83]
		{
			new DmoField("xsmUSDCurrencyCode", "nvarchar", 5, 0, nullable: false),
			new DmoField("xsmFdxAccountNumber", "nvarchar", 15, 0, nullable: false),
			new DmoField("xsmFdxMeterNumber", "numeric", 10, 0, nullable: false),
			new DmoField("xsmFdxSubscribedServices", "nvarchar(max)", 50, 0, nullable: true),
			new DmoField("xsmFdxHostAddress", "nvarchar", 120, 0, nullable: false),
			new DmoField("xsmFdxHostPort", "int", 4, 0, nullable: false),
			new DmoField("xsmFdxHostService", "nvarchar", 120, 0, nullable: false),
			new DmoField("xsmFdxName", "nvarchar", 50, 0, nullable: false),
			new DmoField("xsmFdxAddressLine1", "nvarchar", 50, 0, nullable: false),
			new DmoField("xsmFdxAddressLine2", "nvarchar", 50, 0, nullable: false),
			new DmoField("xsmFdxCity", "nvarchar", 30, 0, nullable: false),
			new DmoField("xsmFdxState", "nvarchar", 3, 0, nullable: false),
			new DmoField("xsmFdxPostCode", "nvarchar", 10, 0, nullable: false),
			new DmoField("xsmFdxCountry", "nvarchar", 2, 0, nullable: false),
			new DmoField("xsmFdxDepartment", "nvarchar", 30, 0, nullable: false),
			new DmoField("xsmFdxPersonName", "nvarchar", 50, 0, nullable: false),
			new DmoField("xsmFdxPhoneNumber", "nvarchar", 20, 0, nullable: false),
			new DmoField("xsmFdxFaxNumber", "nvarchar", 20, 0, nullable: false),
			new DmoField("xsmFdxPagerNumber", "nvarchar", 20, 0, nullable: false),
			new DmoField("xsmFdxEmailAddress", "nvarchar(max)", 50, 0, nullable: true),
			new DmoField("xsmFdxDropOffType", "nvarchar", 30, 0, nullable: false),
			new DmoField("xsmFdxReturnShipIndicator", "nvarchar", 30, 0, nullable: false),
			new DmoField("xsmFdxPackaging", "nvarchar", 14, 0, nullable: false),
			new DmoField("xsmFdxPayorType", "nvarchar", 10, 0, nullable: false),
			new DmoField("xsmFdxPackageLength", "int", 3, 0, nullable: false),
			new DmoField("xsmFdxPackageWidth", "int", 3, 0, nullable: false),
			new DmoField("xsmFdxPackageHeight", "int", 3, 0, nullable: false),
			new DmoField("xsmFdxDeclaredValueCurrency", "nvarchar", 3, 0, nullable: false),
			new DmoField("xsmFdxHandlingCost", "numeric", 7, 2, nullable: false),
			new DmoField("xsmFdxPackagingCost", "numeric", 7, 2, nullable: false),
			new DmoField("xsmFdxShipCostMarkupPct", "numeric", 5, 2, nullable: false),
			new DmoField("xsmFdxOneItemPerShipment", "bit", 1, 0, nullable: false),
			new DmoField("xsmFdxNonstandardContainer", "bit", 1, 0, nullable: false),
			new DmoField("xsmFdxSignatureOption", "nvarchar", 30, 0, nullable: false),
			new DmoField("xsmFdxLabelType", "nvarchar", 10, 0, nullable: false),
			new DmoField("xsmFdxLabelImageType", "nvarchar", 10, 0, nullable: false),
			new DmoField("xsmFdxWeightUnitOfMeasure", "nvarchar", 3, 0, nullable: false),
			new DmoField("xsmFdxDimensionsUnitOfMeasure", "nvarchar", 3, 0, nullable: false),
			new DmoField("xsmFedExUserName", "nvarchar", 50, 0, nullable: false),
			new DmoField("xsmFedExPassword", "nvarchar", 30, 0, nullable: false),
			new DmoField("xsmFedExAccessKey", "nvarchar", 20, 0, nullable: false),
			new DmoField("xsmFdxWebRateRequestType", "nvarchar", 10, 0, nullable: false),
			new DmoField("xsmFdxAddrValAccuracyIndicator", "nvarchar", 10, 0, nullable: false),
			new DmoField("xsmFdxShipDocImageType", "nvarchar", 10, 0, nullable: false),
			new DmoField("xsmFdxLabelFormatType", "nvarchar", 50, 0, nullable: false),
			new DmoField("xsmFdxLabelStockType", "nvarchar", 35, 0, nullable: false),
			new DmoField("xsmFdxLblPrintOrientType", "nvarchar", 30, 0, nullable: false),
			new DmoField("xsmFdxBareCostOfDuty", "bit", 1, 0, nullable: false),
			new DmoField("xsmFdxResidentialAddress", "bit", 1, 0, nullable: false),
			new DmoField("xsmFdxRateTypeBasis", "nvarchar", 10, 0, nullable: false),
			new DmoField("xsmFdxRateElementBasis", "nvarchar", 30, 0, nullable: false),
			new DmoField("xsmUPSUsername", "nvarchar", 250, 0, nullable: false),
			new DmoField("xsmUPSPassword", "nvarchar", 20, 0, nullable: false),
			new DmoField("xsmUPSAccessKey", "nvarchar", 20, 0, nullable: false),
			new DmoField("xsmUPSAccountNo", "nvarchar", 10, 0, nullable: false),
			new DmoField("xsmUPSLocIDPref", "nvarchar", 1, 0, nullable: false),
			new DmoField("xsmUPSLocPostCodePref", "nvarchar", 1, 0, nullable: false),
			new DmoField("xsmFdxBareTrasportationCost", "bit", 1, 0, nullable: false),
			new DmoField("xsmUPSLabelType", "nvarchar", 3, 0, nullable: false),
			new DmoField("xsmUPSLabelStoreLocation", "nvarchar", 250, 0, nullable: false),
			new DmoField("xsmUPSLabelStockSize", "nvarchar", 10, 0, nullable: false),
			new DmoField("xsmFdxHomeDeliveryType", "nvarchar", 12, 0, nullable: false),
			new DmoField("xsmFdxLabelStoreLocation", "nvarchar", 250, 0, nullable: false),
			new DmoField("xsmUPSIsProduction", "bit", 1, 0, nullable: false),
			new DmoField("xsmFdxRateRequestType", "nvarchar", 7, 0, nullable: false),
			new DmoField("xsmFedExIsProduction", "bit", 1, 0, nullable: false),
			new DmoField("xsmFdxAccessibility", "nvarchar", 12, 0, nullable: false),
			new DmoField("xsmFdxInsidePickup", "bit", 1, 0, nullable: false),
			new DmoField("xsmFdxInsideDelivery", "bit", 1, 0, nullable: false),
			new DmoField("xsmFdxSaturdayPickup", "bit", 1, 0, nullable: false),
			new DmoField("xsmFdxSaturdayDelivery", "bit", 1, 0, nullable: false),
			new DmoField("xsmFdxVHCAmountOrPercentage", "numeric", 9, 2, nullable: false),
			new DmoField("xsmFdxVHCType", "nvarchar", 40, 0, nullable: false),
			new DmoField("xsmFdxVHCLevel", "nvarchar", 8, 0, nullable: false),
			new DmoField("xsmFdxHomeDeliveryDate", "date", 14, 0, nullable: true),
			new DmoField("xsmFdxCODCollectionAmount", "numeric", 13, 2, nullable: false),
			new DmoField("xsmFdxCODCollectionType", "nvarchar", 16, 0, nullable: false),
			new DmoField("xsmFdxHoldAtLocation", "bit", 1, 0, nullable: false),
			new DmoField("xsmFdxCOD", "bit", 1, 0, nullable: false),
			new DmoField("xsmFdxCurrencyType", "nvarchar", 3, 0, nullable: false),
			new DmoField("xsmCreatedBy", "nvarchar", 20, 0, nullable: false),
			new DmoField("xsmCreatedDate", "datetime", 14, 0, nullable: true),
			new DmoField("xsmUniqueID", "uniqueidentifier", 16, 0, nullable: false)
		}, new DmoIndex[1]
		{
			new DmoIndex("XSMUNIQUEID", unique: true)
		}, mergeCustomFields: true, disableTriggers: true);
	}
}
