using M1.Core;

namespace M1.Ax.Erp.DD;

[DBConversion("8.10.050", "Convert OrganizationLocations to support unicode", "2013-10-17")]
public class v810RebuildOrganizationLocations
{
	public v810RebuildOrganizationLocations(DBConversionParms parms)
	{
		parms.Dmo.RebuildTable(null, parms.User, parms.DataDictionary, parms.DatabaseName, "OrganizationLocations", new DmoField[84]
		{
			new DmoField("cmlOrganizationID", "nvarchar", 10, 0, nullable: false),
			new DmoField("cmlLocationID", "nvarchar", 5, 0, nullable: false),
			new DmoField("cmlFinanceOrganizationID", "nvarchar", 10, 0, nullable: false),
			new DmoField("cmlName", "nvarchar", 50, 0, nullable: false),
			new DmoField("cmlAddressLine1", "nvarchar", 50, 0, nullable: false),
			new DmoField("cmlAddressLine2", "nvarchar", 50, 0, nullable: false),
			new DmoField("cmlAddressLine3", "nvarchar", 50, 0, nullable: false),
			new DmoField("cmlCity", "nvarchar", 30, 0, nullable: false),
			new DmoField("cmlCounty", "nvarchar", 30, 0, nullable: false),
			new DmoField("cmlState", "nvarchar", 3, 0, nullable: false),
			new DmoField("cmlPostCode", "nvarchar", 10, 0, nullable: false),
			new DmoField("cmlCountry", "nvarchar", 20, 0, nullable: false),
			new DmoField("cmlPhoneNumber", "nvarchar", 20, 0, nullable: false),
			new DmoField("cmlAlternatePhoneNumber", "nvarchar", 20, 0, nullable: false),
			new DmoField("cmlFaxNumber", "nvarchar", 20, 0, nullable: false),
			new DmoField("cmlEMailAddress", "nvarchar(max)", 50, 0, nullable: true),
			new DmoField("cmlQuoteLocation", "bit", 1, 0, nullable: false),
			new DmoField("cmlQuoteContactID", "nvarchar", 5, 0, nullable: false),
			new DmoField("cmlShipLocation", "bit", 1, 0, nullable: false),
			new DmoField("cmlShipContactID", "nvarchar", 5, 0, nullable: false),
			new DmoField("cmlARInvoiceLocation", "bit", 1, 0, nullable: false),
			new DmoField("cmlARInvoiceContactID", "nvarchar", 5, 0, nullable: false),
			new DmoField("cmlPurchaseLocation", "bit", 1, 0, nullable: false),
			new DmoField("cmlPurchaseContactID", "nvarchar", 5, 0, nullable: false),
			new DmoField("cmlAPInvoiceLocation", "bit", 1, 0, nullable: false),
			new DmoField("cmlAPInvoiceContactID", "nvarchar", 5, 0, nullable: false),
			new DmoField("cmlCustomerTaxable", "bit", 1, 0, nullable: false),
			new DmoField("cmlCustomerTaxCodeID", "nvarchar", 5, 0, nullable: false),
			new DmoField("cmlCustomerSecondTaxCodeID", "nvarchar", 5, 0, nullable: false),
			new DmoField("cmlCustomerShippingMethodID", "nvarchar", 5, 0, nullable: false),
			new DmoField("cmlCustomerShipPaymentTypeID", "nvarchar", 5, 0, nullable: false),
			new DmoField("cmlTaxExemptNumber", "nvarchar", 16, 0, nullable: false),
			new DmoField("cmlNonTaxReasonID", "nvarchar", 5, 0, nullable: false),
			new DmoField("cmlCustomerPaymentTermID", "nvarchar", 5, 0, nullable: false),
			new DmoField("cmlCurrencyRateID", "nvarchar", 5, 0, nullable: false),
			new DmoField("cmlARInvoicePerShipmentLine", "bit", 1, 0, nullable: false),
			new DmoField("cmlSupplierPaymentTermID", "nvarchar", 5, 0, nullable: false),
			new DmoField("cmlSupplierShippingMethodID", "nvarchar", 5, 0, nullable: false),
			new DmoField("cmlInactive", "bit", 1, 0, nullable: false),
			new DmoField("cmlInactiveDate", "date", 14, 0, nullable: true),
			new DmoField("cmlUPSAcctNumber", "nvarchar", 6, 0, nullable: false),
			new DmoField("cmlUPSBillingOption", "nvarchar", 20, 0, nullable: false),
			new DmoField("cmlResidentialAddress", "bit", 1, 0, nullable: false),
			new DmoField("cmlCreditCheckForLocation", "bit", 1, 0, nullable: false),
			new DmoField("cmlCustomerCreditLimit", "money", 12, 2, nullable: false),
			new DmoField("cmlCreditHold", "bit", 1, 0, nullable: false),
			new DmoField("cmlDirectPayment", "bit", 1, 0, nullable: false),
			new DmoField("cmlBankInitials", "nvarchar", 3, 0, nullable: false),
			new DmoField("cmlBSBNumber", "nvarchar", 10, 0, nullable: false),
			new DmoField("cmlBankAccountName", "nvarchar", 50, 0, nullable: false),
			new DmoField("cmlBankAccountNumber", "nvarchar", 20, 0, nullable: false),
			new DmoField("cmlEFTDescription", "nvarchar", 20, 0, nullable: false),
			new DmoField("cmlBankAccountType", "nvarchar", 2, 0, nullable: false),
			new DmoField("cmlCountryCode", "nvarchar", 2, 0, nullable: false),
			new DmoField("cmlHDAttachmentFilePath", "nvarchar(max)", 50, 0, nullable: true),
			new DmoField("cmlFreeOnBoardDescription", "nvarchar", 15, 0, nullable: false),
			new DmoField("cmlCreatedBy", "nvarchar", 20, 0, nullable: false),
			new DmoField("cmlCreatedDate", "datetime", 14, 0, nullable: true),
			new DmoField("cmlUniqueID", "uniqueidentifier", 16, 0, nullable: false),
			new DmoField("cmlUPS3rdPartyOrganizationID", "nvarchar", 10, 0, nullable: false),
			new DmoField("cmlUPS3rdPartyLocationID", "nvarchar", 5, 0, nullable: false),
			new DmoField("cmlEFTCode", "nvarchar", 12, 0, nullable: false),
			new DmoField("cmlEFTParticulars", "nvarchar", 12, 0, nullable: false),
			new DmoField("cmlAvalaraUseCodes", "nvarchar", 1, 0, nullable: false),
			new DmoField("cmlAvalaraAddressValidated", "bit", 1, 0, nullable: false),
			new DmoField("cmlContractor", "bit", 1, 0, nullable: false),
			new DmoField("cmlTaxReportable", "bit", 1, 0, nullable: false),
			new DmoField("cmlLastName", "nvarchar", 30, 0, nullable: false),
			new DmoField("cmlFirstGivenName", "nvarchar", 15, 0, nullable: false),
			new DmoField("cmlSecondGivenName", "nvarchar", 15, 0, nullable: false),
			new DmoField("cmlTradingName", "nvarchar(max)", 50, 0, nullable: true),
			new DmoField("cmlCreatedFromMobile", "bit", 1, 0, nullable: false),
			new DmoField("cmlBareCostOfDuty", "bit", 1, 0, nullable: false),
			new DmoField("cmlBareTransportationCost", "bit", 1, 0, nullable: false),
			new DmoField("cmlIgnoreAvalara", "bit", 1, 0, nullable: false),
			new DmoField("cmlUPSValidated", "bit", 1, 0, nullable: false),
			new DmoField("cmlEDIIntegrated", "bit", 1, 0, nullable: false),
			new DmoField("cmlFedExAccountNumber", "nvarchar", 15, 0, nullable: false),
			new DmoField("cmlFedEx3rdPartyOrganizationID", "nvarchar", 10, 0, nullable: false),
			new DmoField("cmlFedEx3rdPartyLocationID", "nvarchar", 5, 0, nullable: false),
			new DmoField("cmlFedExBillingOption", "nvarchar", 20, 0, nullable: false),
			new DmoField("cmlBIC", "nvarchar", 50, 0, nullable: false),
			new DmoField("cmlIBAN", "nvarchar", 50, 0, nullable: false),
			new DmoField("cmlUPSWSBillingOption", "nvarchar", 20, 0, nullable: false)
		}, new DmoIndex[14]
		{
			new DmoIndex("CMLORGANIZATIONID,CMLLOCATIONID", unique: true),
			new DmoIndex("CMLUNIQUEID", unique: true),
			new DmoIndex("cmlOrganizationID", unique: false),
			new DmoIndex("cmlLocationID", unique: false),
			new DmoIndex("cmlFinanceOrganizationID", unique: false),
			new DmoIndex("cmlName", unique: false),
			new DmoIndex("cmlQuoteLocation", unique: false),
			new DmoIndex("cmlShipLocation", unique: false),
			new DmoIndex("cmlARInvoiceLocation", unique: false),
			new DmoIndex("cmlARInvoiceContactID", unique: false),
			new DmoIndex("cmlPurchaseLocation", unique: false),
			new DmoIndex("cmlAPInvoiceLocation", unique: false),
			new DmoIndex("cmlAPInvoiceContactID", unique: false),
			new DmoIndex("cmlInactive", unique: false)
		}, mergeCustomFields: true, disableTriggers: true);
	}
}
