using M1.Core;

namespace M1.Ax.Erp.DD;

[DBConversion("8.10.050", "Convert PurchaseOrderLines to support unicode", "2013-10-17")]
public class v810RebuildPurchaseOrderLines
{
	public v810RebuildPurchaseOrderLines(DBConversionParms parms)
	{
		parms.ServerManager.ExecuteCommand(null, parms.User, parms.DatabaseName, "Update PurchaseOrderLines Set pmlForm1099Box = 0 Where pmlForm1099Box = -1");
		parms.Dmo.RebuildTable(null, parms.User, parms.DataDictionary, parms.DatabaseName, "PurchaseOrderLines", new DmoField[72]
		{
			new DmoField("pmlPurchaseOrderID", "nvarchar", 10, 0, nullable: false),
			new DmoField("pmlPurchaseOrderLineID", "smallint", 4, 0, nullable: false),
			new DmoField("pmlPurchaseType", "tinyint", 1, 0, nullable: false),
			new DmoField("pmlJobID", "nvarchar", 20, 0, nullable: false),
			new DmoField("pmlJobAssemblyID", "int", 5, 0, nullable: false),
			new DmoField("pmlJobType", "tinyint", 1, 0, nullable: false),
			new DmoField("pmlJobMaterialID", "int", 5, 0, nullable: false),
			new DmoField("pmlJobOperationID", "int", 5, 0, nullable: false),
			new DmoField("pmlPartID", "nvarchar", 30, 0, nullable: false),
			new DmoField("pmlOrgPartID", "nvarchar", 30, 0, nullable: false),
			new DmoField("pmlPartRevisionID", "nvarchar", 15, 0, nullable: false),
			new DmoField("pmlPartWarehouseLocationID", "nvarchar", 5, 0, nullable: false),
			new DmoField("pmlPartBinID", "nvarchar", 15, 0, nullable: false),
			new DmoField("pmlPartShortDescription", "nvarchar", 50, 0, nullable: false),
			new DmoField("pmlOrgPartShortDescription", "nvarchar", 50, 0, nullable: false),
			new DmoField("pmlPartLongDescriptionRTF", "nvarchar(max)", 50, 0, nullable: true),
			new DmoField("pmlPartLongDescriptionText", "nvarchar(max)", 50, 0, nullable: true),
			new DmoField("pmlPurchaseQuantity", "numeric", 15, 5, nullable: false),
			new DmoField("pmlPurchaseUnitOfMeasure", "nvarchar", 2, 0, nullable: false),
			new DmoField("pmlPurchaseUnitCostBase", "numeric", 15, 5, nullable: false),
			new DmoField("pmlPurchaseUnitCostForeign", "numeric", 15, 5, nullable: false),
			new DmoField("pmlSetupChargeBase", "numeric", 9, 2, nullable: false),
			new DmoField("pmlSetupChargeForeign", "numeric", 9, 2, nullable: false),
			new DmoField("pmlExtendedCostBase", "money", 12, 2, nullable: false),
			new DmoField("pmlExtendedCostForeign", "money", 12, 2, nullable: false),
			new DmoField("pmlPurchaseQuantityReceived", "numeric", 15, 5, nullable: false),
			new DmoField("pmlConversionFactor", "numeric", 14, 8, nullable: false),
			new DmoField("pmlInventoryQuantity", "numeric", 15, 5, nullable: false),
			new DmoField("pmlInventoryUnitOfMeasure", "nvarchar", 2, 0, nullable: false),
			new DmoField("pmlInventoryQuantityReceived", "numeric", 15, 5, nullable: false),
			new DmoField("pmlLeadTime", "smallint", 3, 0, nullable: false),
			new DmoField("pmlDueDate", "date", 14, 0, nullable: true),
			new DmoField("pmlInTransit", "bit", 1, 0, nullable: false),
			new DmoField("pmlTrackingNumber", "nvarchar", 30, 0, nullable: false),
			new DmoField("pmlReceivedComplete", "bit", 1, 0, nullable: false),
			new DmoField("pmlInvoicedComplete", "bit", 1, 0, nullable: false),
			new DmoField("pmlTaxable", "bit", 1, 0, nullable: false),
			new DmoField("pmlTaxCodeID", "nvarchar", 5, 0, nullable: false),
			new DmoField("pmlTaxAmountBase", "money", 14, 4, nullable: false),
			new DmoField("pmlTaxAmountForeign", "money", 14, 4, nullable: false),
			new DmoField("pmlNonTaxReasonID", "nvarchar", 5, 0, nullable: false),
			new DmoField("pmlSecondTaxCodeID", "nvarchar", 5, 0, nullable: false),
			new DmoField("pmlSecondTaxAmountBase", "money", 14, 4, nullable: false),
			new DmoField("pmlSecondTaxAmountForeign", "money", 14, 4, nullable: false),
			new DmoField("pmlRFQID", "nvarchar", 10, 0, nullable: false),
			new DmoField("pmlRFQLineID", "smallint", 4, 0, nullable: false),
			new DmoField("pmlRMAClaimID", "nvarchar", 10, 0, nullable: false),
			new DmoField("pmlDMRClaimID", "nvarchar", 10, 0, nullable: false),
			new DmoField("pmlRMAClaimLineID", "smallint", 4, 0, nullable: false),
			new DmoField("pmlDMRClaimLineID", "smallint", 4, 0, nullable: false),
			new DmoField("pmlDocuments", "nvarchar(max)", 50, 0, nullable: true),
			new DmoField("pmlClosed", "bit", 1, 0, nullable: false),
			new DmoField("pmlProjectID", "nvarchar", 10, 0, nullable: false),
			new DmoField("pmlProjectAreaID", "nvarchar", 15, 0, nullable: false),
			new DmoField("pmlSalesOrderID", "nvarchar", 10, 0, nullable: false),
			new DmoField("pmlSalesOrderLineID", "smallint", 4, 0, nullable: false),
			new DmoField("pmlSalesOrderDeliveryID", "smallint", 4, 0, nullable: false),
			new DmoField("pmlAssetTypeID", "nvarchar", 5, 0, nullable: false),
			new DmoField("pmlAssetID", "nvarchar", 10, 0, nullable: false),
			new DmoField("pmlItemType", "nvarchar", 1, 0, nullable: false),
			new DmoField("pmlPriceOverride", "bit", 1, 0, nullable: false),
			new DmoField("pmlTotalExtendedCostBase", "money", 12, 2, nullable: false),
			new DmoField("pmlTotalExtendedCostForeign", "money", 12, 2, nullable: false),
			new DmoField("pmlSourcePurchaseOrderID", "nvarchar", 10, 0, nullable: false),
			new DmoField("pmlSourcePurchaseOrderLineID", "smallint", 4, 0, nullable: false),
			new DmoField("pmlRequiresInspection", "bit", 1, 0, nullable: false),
			new DmoField("pmlLandedCostID", "nvarchar", 10, 0, nullable: false),
			new DmoField("pmlInTransitJournalsCreated", "bit", 1, 0, nullable: false),
			new DmoField("pmlCreatedBy", "nvarchar", 20, 0, nullable: false),
			new DmoField("pmlCreatedDate", "datetime", 14, 0, nullable: true),
			new DmoField("pmlUniqueID", "uniqueidentifier", 16, 0, nullable: false),
			new DmoField("pmlForm1099Box", "tinyint", 2, 0, nullable: false)
		}, new DmoIndex[36]
		{
			new DmoIndex("PMLPURCHASEORDERID,PMLPURCHASEORDERLINEID", unique: true),
			new DmoIndex("PMLUNIQUEID", unique: true),
			new DmoIndex("pmlPurchaseOrderID", unique: false),
			new DmoIndex("pmlPurchaseOrderLineID", unique: false),
			new DmoIndex("pmlPurchaseType", unique: false),
			new DmoIndex("pmlJobID", unique: false),
			new DmoIndex("pmlJobAssemblyID", unique: false),
			new DmoIndex("pmlJobType", unique: false),
			new DmoIndex("pmlJobMaterialID", unique: false),
			new DmoIndex("pmlJobOperationID", unique: false),
			new DmoIndex("pmlPartID", unique: false),
			new DmoIndex("pmlOrgPartID", unique: false),
			new DmoIndex("pmlPartRevisionID", unique: false),
			new DmoIndex("pmlPartWarehouseLocationID", unique: false),
			new DmoIndex("pmlPartBinID", unique: false),
			new DmoIndex("pmlDueDate", unique: false),
			new DmoIndex("pmlReceivedComplete", unique: false),
			new DmoIndex("pmlInvoicedComplete", unique: false),
			new DmoIndex("pmlRFQID", unique: false),
			new DmoIndex("pmlRFQLineID", unique: false),
			new DmoIndex("pmlRMAClaimID", unique: false),
			new DmoIndex("pmlDMRClaimID", unique: false),
			new DmoIndex("pmlRMAClaimLineID", unique: false),
			new DmoIndex("pmlDMRClaimLineID", unique: false),
			new DmoIndex("pmlClosed", unique: false),
			new DmoIndex("pmlProjectID", unique: false),
			new DmoIndex("pmlProjectAreaID", unique: false),
			new DmoIndex("pmlSalesOrderID", unique: false),
			new DmoIndex("pmlSalesOrderLineID", unique: false),
			new DmoIndex("pmlSalesOrderDeliveryID", unique: false),
			new DmoIndex("pmlAssetTypeID", unique: false),
			new DmoIndex("pmlAssetID", unique: false),
			new DmoIndex("pmlSourcePurchaseOrderID", unique: false),
			new DmoIndex("pmlSourcePurchaseOrderLineID", unique: false),
			new DmoIndex("pmlLandedCostID", unique: false),
			new DmoIndex("pmlInTransitJournalsCreated", unique: false)
		}, mergeCustomFields: true, disableTriggers: true);
	}
}
