using M1.Core;

namespace M1.Ax.Erp.DD;

[DBConversion("8.10.050", "Convert Calls to support unicode", "2013-10-17")]
public class v810RebuildCalls
{
	public v810RebuildCalls(DBConversionParms parms)
	{
		parms.Dmo.RebuildTable(null, parms.User, parms.DataDictionary, parms.DatabaseName, "Calls", new DmoField[63]
		{
			new DmoField("kbpCallID", "nvarchar", 10, 0, nullable: false),
			new DmoField("kbpOrganizationID", "nvarchar", 10, 0, nullable: false),
			new DmoField("kbpPartShortDescription", "nvarchar", 50, 0, nullable: false),
			new DmoField("kbpLocationID", "nvarchar", 5, 0, nullable: false),
			new DmoField("kbpContactID", "nvarchar", 5, 0, nullable: false),
			new DmoField("kbpCallTypeID", "nvarchar", 5, 0, nullable: false),
			new DmoField("kbpOpenedByEmployeeID", "nvarchar", 10, 0, nullable: false),
			new DmoField("kbpOpenedDate", "datetime", 14, 0, nullable: true),
			new DmoField("kbpAssignedToEmployeeID", "nvarchar", 10, 0, nullable: false),
			new DmoField("kbpAssignedDate", "datetime", 14, 0, nullable: true),
			new DmoField("kbpAcceptedDate", "datetime", 14, 0, nullable: true),
			new DmoField("kbpDueDate", "datetime", 14, 0, nullable: true),
			new DmoField("kbpClosedByEmployeeID", "nvarchar", 10, 0, nullable: false),
			new DmoField("kbpClosedDate", "datetime", 14, 0, nullable: true),
			new DmoField("kbpPartID", "nvarchar", 30, 0, nullable: false),
			new DmoField("kbpPartRevisionID", "nvarchar", 15, 0, nullable: false),
			new DmoField("kbpOrgPartID", "nvarchar", 30, 0, nullable: false),
			new DmoField("kbpShortDescription", "nvarchar", 70, 0, nullable: false),
			new DmoField("kbpLongDescriptionRTF", "nvarchar(max)", 50, 0, nullable: true),
			new DmoField("kbpLongDescriptionText", "nvarchar(max)", 50, 0, nullable: true),
			new DmoField("kbpPhoneNumber", "nvarchar", 20, 0, nullable: false),
			new DmoField("kbpStatus", "nvarchar", 1, 0, nullable: false),
			new DmoField("kbpReasonID", "nvarchar", 5, 0, nullable: false),
			new DmoField("kbpPriorityID", "tinyint", 2, 0, nullable: false),
			new DmoField("kbpBillable", "bit", 1, 0, nullable: false),
			new DmoField("kbpContactMethodID", "nvarchar", 5, 0, nullable: false),
			new DmoField("kbpInbound", "bit", 1, 0, nullable: false),
			new DmoField("kbpInternalOnly", "bit", 1, 0, nullable: false),
			new DmoField("kbpTimeSpent", "numeric", 7, 2, nullable: false),
			new DmoField("kbpExtraTime", "numeric", 7, 2, nullable: false),
			new DmoField("kbpTotalTime", "numeric", 7, 2, nullable: false),
			new DmoField("kbpLeadID", "nvarchar", 10, 0, nullable: false),
			new DmoField("kbpQuoteID", "nvarchar", 10, 0, nullable: false),
			new DmoField("kbpSalesOrderID", "nvarchar", 10, 0, nullable: false),
			new DmoField("kbpJobID", "nvarchar", 20, 0, nullable: false),
			new DmoField("kbpShipmentID", "nvarchar", 10, 0, nullable: false),
			new DmoField("kbpARInvoiceID", "nvarchar", 10, 0, nullable: false),
			new DmoField("kbpPurchaseOrderID", "nvarchar", 10, 0, nullable: false),
			new DmoField("kbpReceiptID", "nvarchar", 10, 0, nullable: false),
			new DmoField("kbpAPInvoiceID", "nvarchar", 10, 0, nullable: false),
			new DmoField("kbpProjectID", "nvarchar", 10, 0, nullable: false),
			new DmoField("kbpRMAClaimID", "nvarchar", 10, 0, nullable: false),
			new DmoField("kbpDMRClaimID", "nvarchar", 10, 0, nullable: false),
			new DmoField("kbpPublished", "bit", 1, 0, nullable: false),
			new DmoField("kbpTemplateFile", "nvarchar", byte.MaxValue, 0, nullable: false),
			new DmoField("kbpProjectAreaID", "nvarchar", 15, 0, nullable: false),
			new DmoField("kbpSerialNumberID", "nvarchar", 30, 0, nullable: false),
			new DmoField("kbpFieldServiceJobCreated", "bit", 1, 0, nullable: false),
			new DmoField("kbpMethodPartID", "nvarchar", 30, 0, nullable: false),
			new DmoField("kbpMethodRevisionID", "nvarchar", 15, 0, nullable: false),
			new DmoField("kbpARInvoiceOrganizationID", "nvarchar", 10, 0, nullable: false),
			new DmoField("kbpARInvoiceLocationID", "nvarchar", 5, 0, nullable: false),
			new DmoField("kbpARInvoiceContactID", "nvarchar", 5, 0, nullable: false),
			new DmoField("kbpPartGroupID", "nvarchar", 5, 0, nullable: false),
			new DmoField("kbpRFQID", "nvarchar", 10, 0, nullable: false),
			new DmoField("kbpInvoicedComplete", "bit", 1, 0, nullable: false),
			new DmoField("kbpCurrencyRateID", "nvarchar", 5, 0, nullable: false),
			new DmoField("kbpCustomRate", "bit", 1, 0, nullable: false),
			new DmoField("kbpExchangeRate", "numeric", 13, 6, nullable: false),
			new DmoField("kbpCreatedFromMobile", "bit", 1, 0, nullable: false),
			new DmoField("kbpCreatedBy", "nvarchar", 20, 0, nullable: false),
			new DmoField("kbpCreatedDate", "datetime", 14, 0, nullable: true),
			new DmoField("kbpUniqueID", "uniqueidentifier", 16, 0, nullable: false)
		}, new DmoIndex[34]
		{
			new DmoIndex("KBPCALLID", unique: true),
			new DmoIndex("KBPUNIQUEID", unique: true),
			new DmoIndex("kbpOrganizationID", unique: false),
			new DmoIndex("kbpLocationID", unique: false),
			new DmoIndex("kbpContactID", unique: false),
			new DmoIndex("kbpCallTypeID", unique: false),
			new DmoIndex("kbpPartID", unique: false),
			new DmoIndex("kbpPartRevisionID", unique: false),
			new DmoIndex("kbpOrgPartID", unique: false),
			new DmoIndex("kbpStatus", unique: false),
			new DmoIndex("kbpReasonID", unique: false),
			new DmoIndex("kbpPriorityID", unique: false),
			new DmoIndex("kbpContactMethodID", unique: false),
			new DmoIndex("kbpInternalOnly", unique: false),
			new DmoIndex("kbpLeadID", unique: false),
			new DmoIndex("kbpQuoteID", unique: false),
			new DmoIndex("kbpSalesOrderID", unique: false),
			new DmoIndex("kbpJobID", unique: false),
			new DmoIndex("kbpShipmentID", unique: false),
			new DmoIndex("kbpARInvoiceID", unique: false),
			new DmoIndex("kbpPurchaseOrderID", unique: false),
			new DmoIndex("kbpReceiptID", unique: false),
			new DmoIndex("kbpAPInvoiceID", unique: false),
			new DmoIndex("kbpProjectID", unique: false),
			new DmoIndex("kbpRMAClaimID", unique: false),
			new DmoIndex("kbpDMRClaimID", unique: false),
			new DmoIndex("kbpPublished", unique: false),
			new DmoIndex("kbpProjectAreaID", unique: false),
			new DmoIndex("kbpSerialNumberID", unique: false),
			new DmoIndex("kbpARInvoiceOrganizationID", unique: false),
			new DmoIndex("kbpARInvoiceLocationID", unique: false),
			new DmoIndex("kbpARInvoiceContactID", unique: false),
			new DmoIndex("kbpRFQID", unique: false),
			new DmoIndex("kbpInvoicedComplete", unique: false)
		}, mergeCustomFields: true, disableTriggers: true);
	}
}
