using M1.Core;

namespace M1.Ax.Erp.DD;

[DBConversion("8.10.050", "Convert WebGearProperties to support unicode", "2013-10-17")]
public class v810RebuildWebGearProperties
{
	public v810RebuildWebGearProperties(DBConversionParms parms)
	{
		parms.Dmo.RebuildTable(null, parms.User, parms.DataDictionary, parms.DatabaseName, "WebGearProperties", new DmoField[103]
		{
			new DmoField("wgwWebGearWebsiteURL", "nvarchar", 50, 0, nullable: false),
			new DmoField("wgwGridSearchDisplayRows", "int", 4, 0, nullable: false),
			new DmoField("wgwLogAnonymousSessions", "tinyint", 1, 0, nullable: false),
			new DmoField("wgwLogKnownSessions", "tinyint", 1, 0, nullable: false),
			new DmoField("wgwAllowContactSelfActivation", "bit", 1, 0, nullable: false),
			new DmoField("wgwCreateWithNoExpiration", "bit", 1, 0, nullable: false),
			new DmoField("wgwExpirationDuration", "int", 4, 0, nullable: false),
			new DmoField("wgwShowCart", "bit", 1, 0, nullable: false),
			new DmoField("wgwPartImageFileName", "nvarchar", 70, 0, nullable: false),
			new DmoField("wgwPartImagesFilePath", "nvarchar(max)", 50, 0, nullable: true),
			new DmoField("wgwShowPartGroupSelector", "bit", 1, 0, nullable: false),
			new DmoField("wgwPartCategoriesToDisplay", "int", 4, 0, nullable: false),
			new DmoField("wgwShowAlternateParts", "bit", 1, 0, nullable: false),
			new DmoField("wgwAllowAddPartReviews", "bit", 1, 0, nullable: false),
			new DmoField("wgwShowPartsAlsoPurchased", "bit", 1, 0, nullable: false),
			new DmoField("wgwShowMostPopularParts", "bit", 1, 0, nullable: false),
			new DmoField("wgwShowPartAttachments", "bit", 1, 0, nullable: false),
			new DmoField("wgwHideQuotePartsOnSearch", "bit", 1, 0, nullable: false),
			new DmoField("wgwHideXrefParts", "bit", 1, 0, nullable: false),
			new DmoField("wgwFdxShowRealtimeRates", "bit", 1, 0, nullable: false),
			new DmoField("wgwShowPartPrices", "bit", 1, 0, nullable: false),
			new DmoField("wgwPriceLabel", "nvarchar", 80, 0, nullable: false),
			new DmoField("wgwShowPartAvailability", "bit", 1, 0, nullable: false),
			new DmoField("wgwNewLocDefaultResidential", "bit", 1, 0, nullable: false),
			new DmoField("wgwDefaultWebShippingMethodID", "nvarchar", 5, 0, nullable: false),
			new DmoField("wgwDefaultPaymentTermID", "nvarchar", 5, 0, nullable: false),
			new DmoField("wgwDefaultSalesEmployeeID", "nvarchar", 10, 0, nullable: false),
			new DmoField("wgwDefaultCustomerTaxable", "bit", 1, 0, nullable: false),
			new DmoField("wgwDefaultCustomerTaxCodeID", "nvarchar", 5, 0, nullable: false),
			new DmoField("wgwDefaultNonTaxReasonID", "nvarchar", 5, 0, nullable: false),
			new DmoField("wgwDefaultCustomerSecTaxCodeID", "nvarchar", 5, 0, nullable: false),
			new DmoField("wgwAllowNewCustomerCreation", "bit", 1, 0, nullable: false),
			new DmoField("wgwAllowNewLocationCreation", "bit", 1, 0, nullable: false),
			new DmoField("wgwShowPartGroupWithProduct", "bit", 1, 0, nullable: false),
			new DmoField("wgwSalesOrderApprovalRule", "tinyint", 1, 0, nullable: false),
			new DmoField("wgwSalesOrderApprovalAmount", "money", 12, 2, nullable: false),
			new DmoField("wgwSOSendEmailToContact", "bit", 1, 0, nullable: false),
			new DmoField("wgwSOSendEmailAlertToList", "bit", 1, 0, nullable: false),
			new DmoField("wgwSOAlertEmailList", "nvarchar(max)", 50, 0, nullable: true),
			new DmoField("wgwSOEmailSubject", "nvarchar", 80, 0, nullable: false),
			new DmoField("wgwSOEmailBody", "nvarchar(max)", 50, 0, nullable: true),
			new DmoField("wgwTakeCallsOnWeb", "bit", 1, 0, nullable: false),
			new DmoField("wgwCallTypeID", "nvarchar", 5, 0, nullable: false),
			new DmoField("wgwReopenCallStatus", "nvarchar", 1, 0, nullable: false),
			new DmoField("wgwCallOpenedByEmployeeID", "nvarchar", 10, 0, nullable: false),
			new DmoField("wgwCallAssignedToEmployeeID", "nvarchar", 10, 0, nullable: false),
			new DmoField("wgwCallReasonID", "nvarchar", 5, 0, nullable: false),
			new DmoField("wgwCallPriorityID", "tinyint", 2, 0, nullable: false),
			new DmoField("wgwCallContactMethodID", "nvarchar", 5, 0, nullable: false),
			new DmoField("wgwCallPartID", "nvarchar", 30, 0, nullable: false),
			new DmoField("wgwSendEmailAlertToAssignedTo", "bit", 1, 0, nullable: false),
			new DmoField("wgwSendEmailAlertToList", "bit", 1, 0, nullable: false),
			new DmoField("wgwAlertEmailList", "nvarchar(max)", 50, 0, nullable: true),
			new DmoField("wgwRevisionText", "nvarchar", 5, 0, nullable: false),
			new DmoField("wgwDefaultLocationToContact", "bit", 1, 0, nullable: false),
			new DmoField("wgwCLNewSendEmailToContact", "bit", 1, 0, nullable: false),
			new DmoField("wgwCLEditSendEmailToContact", "bit", 1, 0, nullable: false),
			new DmoField("wgwCLEmailSubject", "nvarchar", 80, 0, nullable: false),
			new DmoField("wgwCLEmailBody", "nvarchar(max)", 50, 0, nullable: true),
			new DmoField("wgwAllowAttachmentsOnWeb", "bit", 1, 0, nullable: false),
			new DmoField("wgwAttachmentTypeID", "nvarchar", 5, 0, nullable: false),
			new DmoField("wgwAttachmentFilePath", "nvarchar(max)", 50, 0, nullable: true),
			new DmoField("wgwAttachmentKnownMegaBytes", "smallint", 4, 0, nullable: false),
			new DmoField("wgwAttachmentAnonMegaBytes", "smallint", 4, 0, nullable: false),
			new DmoField("wgwAttachmentKnownFileCount", "smallint", 4, 0, nullable: false),
			new DmoField("wgwAttachmentAnonFileCount", "smallint", 4, 0, nullable: false),
			new DmoField("wgwQRMAOnWeb", "bit", 1, 0, nullable: false),
			new DmoField("wgwQRMASendEmailToContact", "bit", 1, 0, nullable: false),
			new DmoField("wgwQRMASendEmailToList", "bit", 1, 0, nullable: false),
			new DmoField("wgwQRMAEmailSubjectContact", "nvarchar", 80, 0, nullable: false),
			new DmoField("wgwQRMAEmailBodyContact", "nvarchar(max)", 50, 0, nullable: true),
			new DmoField("wgwQRMAOpenedByEmployeeID", "nvarchar", 10, 0, nullable: false),
			new DmoField("wgwQRMAAssignedToEmployeeID", "nvarchar", 10, 0, nullable: false),
			new DmoField("wgwQRMAEmailSubjectList", "nvarchar", 80, 0, nullable: false),
			new DmoField("wgwQRMAEmailBodyList", "nvarchar(max)", 50, 0, nullable: true),
			new DmoField("wgwQRMAAlertEMailList", "nvarchar(max)", 50, 0, nullable: true),
			new DmoField("wgwQRMAGridTitle", "nvarchar(max)", 50, 0, nullable: true),
			new DmoField("wgwQRMAFormInstructions", "nvarchar(max)", 50, 0, nullable: true),
			new DmoField("wgwHTMLStringWelcome", "nvarchar(max)", 50, 0, nullable: true),
			new DmoField("wgwHTMLStringBanner", "nvarchar(max)", 50, 0, nullable: true),
			new DmoField("wgwHTMLStringCrystalViewer", "nvarchar(max)", 50, 0, nullable: true),
			new DmoField("wgwHTMLStringWelcomeLogin", "nvarchar(max)", 50, 0, nullable: true),
			new DmoField("wgwHTMLStringFaq", "nvarchar(max)", 50, 0, nullable: true),
			new DmoField("wgwHTMLStringSearch", "nvarchar(max)", 50, 0, nullable: true),
			new DmoField("wgwHTMLStringLegal", "nvarchar(max)", 50, 0, nullable: true),
			new DmoField("wgwHTMLStringLogin", "nvarchar(max)", 50, 0, nullable: true),
			new DmoField("wgwHTMLStringPricing", "nvarchar(max)", 50, 0, nullable: true),
			new DmoField("wgwHTMLStringContact", "nvarchar(max)", 50, 0, nullable: true),
			new DmoField("wgwHTMLStringPrivacy", "nvarchar(max)", 50, 0, nullable: true),
			new DmoField("wgwHTMLStringReturns", "nvarchar(max)", 50, 0, nullable: true),
			new DmoField("wgwHTMLStringShipping", "nvarchar(max)", 50, 0, nullable: true),
			new DmoField("wgwHTMLStringCreditCardInfo", "nvarchar(max)", 50, 0, nullable: true),
			new DmoField("wgwQuantityOnHandFormula", "nvarchar", byte.MaxValue, 0, nullable: false),
			new DmoField("wgwCreateContractOwnersOnWeb", "bit", 1, 0, nullable: false),
			new DmoField("wgwDisplayAllDiscounts", "bit", 1, 0, nullable: false),
			new DmoField("wgwWebConfigPriceRule", "tinyint", 1, 0, nullable: false),
			new DmoField("wgwWebConfigMode", "tinyint", 1, 0, nullable: false),
			new DmoField("wgwCreatedBy", "nvarchar", 20, 0, nullable: false),
			new DmoField("wgwCreatedDate", "datetime", 14, 0, nullable: true),
			new DmoField("wgwUniqueID", "uniqueidentifier", 16, 0, nullable: false),
			new DmoField("wgwTheme", "nvarchar", 50, 0, nullable: false),
			new DmoField("wgwAnonymousCustomerGroupID", "nvarchar", 5, 0, nullable: false),
			new DmoField("wgwContractOwnerEdit", "tinyint", 1, 0, nullable: false)
		}, new DmoIndex[1]
		{
			new DmoIndex("WGWUNIQUEID", unique: true)
		}, mergeCustomFields: true, disableTriggers: true);
	}
}
