using M1.Core;

namespace M1.Ax.Erp.DD;

[DBConversion("8.10.050", "Convert Shipments to support unicode", "2013-10-17")]
public class v810RebuildShipments
{
	public v810RebuildShipments(DBConversionParms parms)
	{
		parms.Dmo.RebuildTable(null, parms.User, parms.DataDictionary, parms.DatabaseName, "Shipments", new DmoField[80]
		{
			new DmoField("smpWeightSubtotal", "numeric", 15, 5, nullable: false),
			new DmoField("smpShipmentID", "nvarchar", 10, 0, nullable: false),
			new DmoField("smpPlantDepartmentID", "nvarchar", 5, 0, nullable: false),
			new DmoField("smpPlantID", "nvarchar", 5, 0, nullable: false),
			new DmoField("smpShipDate", "datetime", 14, 0, nullable: true),
			new DmoField("smpCustomerOrganizationID", "nvarchar", 10, 0, nullable: false),
			new DmoField("smpARInvoiceLocationID", "nvarchar", 5, 0, nullable: false),
			new DmoField("smpARInvoiceContactID", "nvarchar", 5, 0, nullable: false),
			new DmoField("smpShipOrganizationID", "nvarchar", 10, 0, nullable: false),
			new DmoField("smpShipLocationID", "nvarchar", 5, 0, nullable: false),
			new DmoField("smpShipContactID", "nvarchar", 5, 0, nullable: false),
			new DmoField("smpShippingMethodID", "nvarchar", 5, 0, nullable: false),
			new DmoField("smpShippingPaymentTypeID", "nvarchar", 5, 0, nullable: false),
			new DmoField("smpNumberOfLabels", "smallint", 3, 0, nullable: false),
			new DmoField("smpFreightSubtotal", "money", 12, 2, nullable: false),
			new DmoField("smpFreightCharge", "money", 12, 2, nullable: false),
			new DmoField("smpFreightTotal", "money", 12, 2, nullable: false),
			new DmoField("smpStandardMessageID", "nvarchar", 10, 0, nullable: false),
			new DmoField("smpShippingCommentsRTF", "nvarchar(max)", 50, 0, nullable: true),
			new DmoField("smpShippingCommentsText", "nvarchar(max)", 50, 0, nullable: true),
			new DmoField("smpPrintPackingSlip", "bit", 1, 0, nullable: false),
			new DmoField("smpPrintLabels", "bit", 1, 0, nullable: false),
			new DmoField("smpTrackingNumber", "nvarchar", 30, 0, nullable: false),
			new DmoField("smpShipmentSubtotal", "money", 12, 2, nullable: false),
			new DmoField("smpShipmentTotal", "money", 12, 2, nullable: false),
			new DmoField("smpProjectID", "nvarchar", 10, 0, nullable: false),
			new DmoField("smpClosed", "bit", 1, 0, nullable: false),
			new DmoField("smpClosedDate", "date", 14, 0, nullable: true),
			new DmoField("smpWeightTotal", "numeric", 15, 5, nullable: false),
			new DmoField("smpAdditionalWeight", "numeric", 15, 5, nullable: false),
			new DmoField("smpFreightChargeForeign", "money", 12, 2, nullable: false),
			new DmoField("smpCurrencyRateID", "nvarchar", 5, 0, nullable: false),
			new DmoField("smpCustomRate", "bit", 1, 0, nullable: false),
			new DmoField("smpExchangeRate", "numeric", 13, 6, nullable: false),
			new DmoField("smpFreightSubtotalForeign", "money", 12, 2, nullable: false),
			new DmoField("smpFreightTotalForeign", "money", 12, 2, nullable: false),
			new DmoField("smpPostedToGL", "bit", 1, 0, nullable: false),
			new DmoField("smpShipmentSubtotalForeign", "money", 12, 2, nullable: false),
			new DmoField("smpShipmentTotalForeign", "money", 12, 2, nullable: false),
			new DmoField("smpPostedDate", "date", 14, 0, nullable: true),
			new DmoField("smpReversalEntry", "bit", 1, 0, nullable: false),
			new DmoField("smpCreatedBy", "nvarchar", 20, 0, nullable: false),
			new DmoField("smpCreatedDate", "datetime", 14, 0, nullable: true),
			new DmoField("smpUniqueID", "uniqueidentifier", 16, 0, nullable: false),
			new DmoField("smpListCarrierFreightBase", "money", 12, 2, nullable: false),
			new DmoField("smpListCarrierFreightForeign", "money", 12, 2, nullable: false),
			new DmoField("smpListBaseChargeForeign", "money", 12, 2, nullable: false),
			new DmoField("smpListSurchargeForeign", "money", 12, 2, nullable: false),
			new DmoField("smpAccBaseChargeBase", "money", 12, 2, nullable: false),
			new DmoField("smpAccBaseChargeForeign", "money", 12, 2, nullable: false),
			new DmoField("smpAccSurchargeBase", "money", 12, 2, nullable: false),
			new DmoField("smpAccSurchargeForeign", "money", 12, 2, nullable: false),
			new DmoField("smpListDiscountBase", "money", 12, 2, nullable: false),
			new DmoField("smpListDiscountForeign", "money", 12, 2, nullable: false),
			new DmoField("smpAccDiscountBase", "money", 12, 2, nullable: false),
			new DmoField("smpAccDiscountForeign", "money", 12, 2, nullable: false),
			new DmoField("smpAccCarrierFreightBase", "money", 12, 2, nullable: false),
			new DmoField("smpAccCarrierFreightForeign", "money", 12, 2, nullable: false),
			new DmoField("smpReturnInstructionsRTF", "nvarchar(max)", 50, 0, nullable: true),
			new DmoField("smpReturnInstructionsText", "nvarchar(max)", 50, 0, nullable: true),
			new DmoField("smpUPS3rdPartyOrganizationID", "nvarchar", 10, 0, nullable: false),
			new DmoField("smpUPS3rdPartyLocationID", "nvarchar", 5, 0, nullable: false),
			new DmoField("smpShipmentIDNumber", "nvarchar", 20, 0, nullable: false),
			new DmoField("smpCarrierDocumentFilePath", "nvarchar(max)", 50, 0, nullable: true),
			new DmoField("smpExportingCarrier", "nvarchar", 35, 0, nullable: false),
			new DmoField("smpDocuments", "nvarchar(max)", 50, 0, nullable: true),
			new DmoField("smpAESITN", "nvarchar", 30, 0, nullable: false),
			new DmoField("smpReasonForExport", "nvarchar", 20, 0, nullable: false),
			new DmoField("smpListBaseChargeBase", "money", 12, 2, nullable: false),
			new DmoField("smpListSurchargeBase", "money", 12, 2, nullable: false),
			new DmoField("smpCODLabelFilePath", "nvarchar(max)", 50, 0, nullable: true),
			new DmoField("smpUPSBillingOption", "nvarchar", 20, 0, nullable: false),
			new DmoField("smpUPSAccountNumber", "nvarchar", 6, 0, nullable: false),
			new DmoField("smpFedExAccountNumber", "nvarchar", 15, 0, nullable: false),
			new DmoField("smpFedExBillingOption", "nvarchar", 20, 0, nullable: false),
			new DmoField("smpBlindShipOrganizationID", "nvarchar", 10, 0, nullable: false),
			new DmoField("smpBlindShipLocationID", "nvarchar", 5, 0, nullable: false),
			new DmoField("smpBlindShipContactID", "nvarchar", 5, 0, nullable: false),
			new DmoField("smpFedEx3rdPartyOrganizationID", "nvarchar", 10, 0, nullable: false),
			new DmoField("smpFedEx3rdPartyLocationID", "nvarchar", 5, 0, nullable: false)
		}, new DmoIndex[12]
		{
			new DmoIndex("SMPSHIPMENTID", unique: true),
			new DmoIndex("SMPUNIQUEID", unique: true),
			new DmoIndex("smpPlantDepartmentID", unique: false),
			new DmoIndex("smpPlantID", unique: false),
			new DmoIndex("smpShipDate", unique: false),
			new DmoIndex("smpCustomerOrganizationID", unique: false),
			new DmoIndex("smpARInvoiceLocationID", unique: false),
			new DmoIndex("smpShipOrganizationID", unique: false),
			new DmoIndex("smpPrintPackingSlip", unique: false),
			new DmoIndex("smpPrintLabels", unique: false),
			new DmoIndex("smpProjectID", unique: false),
			new DmoIndex("smpClosed", unique: false)
		}, mergeCustomFields: true, disableTriggers: true);
	}
}
