using System.Text;
using M1.Core;

namespace M1.Ax.Erp.DD;

[DBConversion("9.00.134", "Insert lot/serial number transactions for material issue / mfg / misc receipts", "2016-02-22")]
public class v900134a
{
	public v900134a(DBConversionParms parms)
	{
		if (parms.Dmo.DoesTableExist(null, parms.User, parms.DatabaseName, "SerialNumberTransactions") && parms.Dmo.DoesTableExist(null, parms.User, parms.DatabaseName, "LotNumberTransactions"))
		{
			StringBuilder stringBuilder = new StringBuilder();
			stringBuilder.AppendLine("insert into LotNumberTransactions(abtPartID, abtPartRevisionID, abtPartWarehouseLocationID, abtPartBinID, abtLotNumberID, abtTransactionType,abtTransactionDate, abtQuantity, abtJobID, abtJobAssemblyID, abtJobMaterialID, abtPartTransactionID, abtCreatedBy, abtCreatedDate, abtTableName, abtTableUniqueID) select abtPartID, abtPartRevisionID, abtPartWarehouseLocationID, abtPartBinID, abtLotNumberID, 32, abtTransactionDate, abtQuantity, abtJobID, abtJobAssemblyID, abtJobMaterialID, abtPartTransactionID, 'CONVERSION' as abtCreatedBy, Getdate() as abtCreatedDate, abtTableName, abtTableUniqueID from LotNumberTransactions where abtTransactionType = 4 and abtTableName = 'MaterialIssueLines' and abtPartTransactionID not in (select abtPartTransactionID from LotNumberTransactions where abtTransactionType = 32);");
			stringBuilder.AppendLine("insert into LotNumberTransactions (abtPartID, abtPartRevisionID, abtPartWarehouseLocationID, abtPartBinID, abtLotNumberID, abtTransactionType,abtTransactionDate, abtQuantity, abtJobID, abtJobAssemblyID, abtJobMaterialID, abtPartTransactionID, abtCreatedBy, abtCreatedDate, abtTableName, abtTableUniqueID) select abtPartID, abtPartRevisionID, abtPartWarehouseLocationID, abtPartBinID, abtLotNumberID, 33, abtTransactionDate, abtQuantity, abtJobID,abtJobAssemblyID, abtJobMaterialID, abtPartTransactionID, 'CONVERSION' as abtCreatedBy, Getdate() as abtCreatedDate, abtTableName, abtTableUniqueID from LotNumberTransactions where abtTransactionType = 22 and abtTableName = 'MaterialIssueLines' and abtPartTransactionID not in (select abtPartTransactionID from LotNumberTransactions where abtTransactionType = 33); ");
			stringBuilder.AppendLine("insert into LotNumberTransactions (abtPartID, abtPartRevisionID, abtPartWarehouseLocationID, abtPartBinID, abtLotNumberID, abtTransactionType,abtTransactionDate, abtQuantity, abtJobID, abtJobAssemblyID, abtJobMaterialID, abtPartTransactionID, abtCreatedBy, abtCreatedDate, abtTableName, abtTableUniqueID) select abtPartID, abtPartRevisionID, abtPartWarehouseLocationID, abtPartBinID, abtLotNumberID, 30, abtTransactionDate, abtQuantity, abtJobID,abtJobAssemblyID, abtJobMaterialID, abtPartTransactionID, 'CONVERSION' as abtCreatedBy, Getdate() as abtCreatedDate, abtTableName, abtTableUniqueID from LotNumberTransactions where abtTransactionType = 20 and abtTableName = 'MaterialIssueLines' and abtPartTransactionID not in (select abtPartTransactionID from LotNumberTransactions where abtTransactionType = 30); ");
			stringBuilder.AppendLine("insert into LotNumberTransactions (abtPartID, abtPartRevisionID, abtPartWarehouseLocationID, abtPartBinID, abtLotNumberID, abtTransactionType,abtTransactionDate, abtQuantity, abtJobID, abtJobAssemblyID, abtJobMaterialID, abtPartTransactionID, abtCreatedBy, abtCreatedDate, abtTableName, abtTableUniqueID) select abtPartID, abtPartRevisionID, abtPartWarehouseLocationID, abtPartBinID, abtLotNumberID, 31, abtTransactionDate, abtQuantity, abtJobID,abtJobAssemblyID, abtJobMaterialID, abtPartTransactionID, 'CONVERSION' as abtCreatedBy, Getdate() as abtCreatedDate, abtTableName, abtTableUniqueID from LotNumberTransactions where abtTransactionType = 23 and abtTableName = 'MaterialIssueLines' and abtPartTransactionID not in (select abtPartTransactionID from LotNumberTransactions where abtTransactionType = 31); ");
			stringBuilder.AppendLine("insert into LotNumberTransactions (abtPartID, abtPartRevisionID, abtPartWarehouseLocationID, abtPartBinID, abtLotNumberID, abtTransactionType, abtTransactionDate, abtQuantity, abtJobID, abtJobAssemblyID, abtJobMaterialID, abtPartTransactionID, abtCreatedBy, abtCreatedDate, abtTableName, abtTableUniqueID) select abtPartID, abtPartRevisionID, abtPartWarehouseLocationID, abtPartBinID, abtLotNumberID, 28, abtTransactionDate, abtQuantity, abtJobID,abtJobAssemblyID, abtJobMaterialID, abtPartTransactionID, 'CONVERSION' as abtCreatedBy, Getdate() as abtCreatedDate, abtTableName, abtTableUniqueID from LotNumberTransactions where abtTransactionType = 21 and abtTableName = 'MaterialIssueLines' and abtPartTransactionID not in (select abtPartTransactionID from LotNumberTransactions where abtTransactionType = 28); ");
			stringBuilder.AppendLine("insert into LotNumberTransactions (abtPartID, abtPartRevisionID, abtPartWarehouseLocationID, abtPartBinID, abtLotNumberID, abtTransactionType, abtTransactionDate, abtQuantity, abtJobID, abtJobAssemblyID, abtJobMaterialID, abtPartTransactionID, abtCreatedBy, abtCreatedDate, abtTableName, abtTableUniqueID) select abtPartID, abtPartRevisionID, abtPartWarehouseLocationID, abtPartBinID, abtLotNumberID, 29, abtTransactionDate, abtQuantity, abtJobID,abtJobAssemblyID, abtJobMaterialID, abtPartTransactionID, 'CONVERSION' as abtCreatedBy, Getdate() as abtCreatedDate, abtTableName, abtTableUniqueID from LotNumberTransactions where abtTransactionType = 17 and abtTableName = 'MaterialIssueLines' and abtPartTransactionID not in (select abtPartTransactionID from LotNumberTransactions where abtTransactionType = 29); ");
			stringBuilder.AppendLine("insert into LotNumberTransactions (abtPartID, abtPartRevisionID, abtPartWarehouseLocationID, abtPartBinID, abtLotNumberID, abtTransactionType, abtTransactionDate, abtQuantity, abtJobID, abtJobAssemblyID, abtJobMaterialID, abtPartTransactionID, abtCreatedBy, abtCreatedDate, abtTableName, abtTableUniqueID) select abtPartID, abtPartRevisionID, abtPartWarehouseLocationID, abtPartBinID, abtLotNumberID, 37, abtTransactionDate, abtQuantity, abtJobID,abtJobAssemblyID, abtJobMaterialID, abtPartTransactionID, 'CONVERSION' as abtCreatedBy, Getdate() as abtCreatedDate, abtTableName, abtTableUniqueID from LotNumberTransactions where abtTransactionType = 4 and abtTableName = 'MfgReceipts' and abtPartTransactionID not in (select abtPartTransactionID from LotNumberTransactions where abtTransactionType = 37); ");
			stringBuilder.AppendLine("insert into LotNumberTransactions (abtPartID, abtPartRevisionID, abtPartWarehouseLocationID, abtPartBinID, abtLotNumberID, abtTransactionType, abtTransactionDate, abtQuantity, abtJobID, abtJobAssemblyID, abtJobMaterialID, abtPartTransactionID, abtCreatedBy, abtCreatedDate, abtTableName, abtTableUniqueID) select abtPartID, abtPartRevisionID, abtPartWarehouseLocationID, abtPartBinID, abtLotNumberID, 38, abtTransactionDate, abtQuantity, abtJobID,abtJobAssemblyID, abtJobMaterialID, abtPartTransactionID, 'CONVERSION' as abtCreatedBy, Getdate() as abtCreatedDate, abtTableName, abtTableUniqueID from LotNumberTransactions where abtTransactionType = 2 and abtTableName = 'MfgReceipts' and abtPartTransactionID not in (select abtPartTransactionID from LotNumberTransactions where abtTransactionType = 38); ");
			stringBuilder.AppendLine("insert into LotNumberTransactions (abtPartID, abtPartRevisionID, abtPartWarehouseLocationID, abtPartBinID, abtLotNumberID, abtTransactionType, abtTransactionDate, abtQuantity, abtJobID, abtJobAssemblyID, abtJobMaterialID, abtPartTransactionID, abtCreatedBy, abtCreatedDate, abtTableName, abtTableUniqueID) select abtPartID, abtPartRevisionID, abtPartWarehouseLocationID, abtPartBinID, abtLotNumberID, Case When abtInspect = 0 Then 34 Else 39 End, abtTransactionDate, abtQuantity, abtJobID,abtJobAssemblyID, abtJobMaterialID, abtPartTransactionID, 'CONVERSION' as abtCreatedBy, Getdate() as abtCreatedDate, abtTableName, abtTableUniqueID from LotNumberTransactions where abtTransactionType = 3 and abtTableName = 'MfgReceipts' and abtPartTransactionID not in (select abtPartTransactionID from LotNumberTransactions where abtTransactionType = 34); ");
			stringBuilder.AppendLine("insert into LotNumberTransactions (abtPartID, abtPartRevisionID, abtPartWarehouseLocationID, abtPartBinID, abtLotNumberID, abtTransactionType, abtTransactionDate, abtQuantity, abtJobID, abtJobAssemblyID, abtJobMaterialID, abtPartTransactionID, abtCreatedBy, abtCreatedDate, abtTableName, abtTableUniqueID) select abtPartID, abtPartRevisionID, abtPartWarehouseLocationID, abtPartBinID, abtLotNumberID, 35, abtTransactionDate, abtQuantity, abtJobID,abtJobAssemblyID, abtJobMaterialID, abtPartTransactionID, 'CONVERSION' as abtCreatedBy, Getdate() as abtCreatedDate, abtTableName, abtTableUniqueID from LotNumberTransactions where abtTransactionType = 23 and abtTableName = 'MfgReceipts' and abtPartTransactionID not in (select abtPartTransactionID from LotNumberTransactions where abtTransactionType = 35); ");
			stringBuilder.AppendLine("insert into LotNumberTransactions (abtPartID, abtPartRevisionID, abtPartWarehouseLocationID, abtPartBinID, abtLotNumberID, abtTransactionType, abtTransactionDate, abtQuantity, abtJobID, abtJobAssemblyID, abtJobMaterialID, abtPartTransactionID, abtCreatedBy, abtCreatedDate, abtTableName, abtTableUniqueID) select abtPartID, abtPartRevisionID, abtPartWarehouseLocationID, abtPartBinID, abtLotNumberID, 39, abtTransactionDate, abtQuantity, abtJobID,abtJobAssemblyID, abtJobMaterialID, abtPartTransactionID, 'CONVERSION' as abtCreatedBy, Getdate() as abtCreatedDate, abtTableName, abtTableUniqueID from LotNumberTransactions where abtTransactionType = 13 and abtTableName = 'MfgReceipts' and abtPartTransactionID not in (select abtPartTransactionID from LotNumberTransactions where abtTransactionType = 39); ");
			stringBuilder.AppendLine("insert into SerialNumberTransactions (sntPartID, sntPartRevisionID, sntPartWarehouseLocationID, sntPartBinID, sntSerialNumberID, sntTransactionType, sntStatus, sntTransactionDate, sntQuantity, sntJobID, sntJobAssemblyID, sntJobMaterialID, sntPartTransactionID, sntCreatedBy, sntCreatedDate, sntTableName, sntTableUniqueID) select sntPartID, sntPartRevisionID, sntPartWarehouseLocationID, sntPartBinID, sntSerialNumberID, 32, sntStatus, sntTransactionDate, sntQuantity, sntJobID, sntJobAssemblyID, sntJobMaterialID, sntPartTransactionID, 'CONVERSION' as sntCreatedBy, Getdate() as sntCreatedDate, sntTableName, sntTableUniqueID from SerialNumberTransactions where sntTransactionType = 4 and sntTableName = 'MaterialIssueLines' and sntPartTransactionID not in (select sntPartTransactionID from SerialNumberTransactions where sntTransactionType = 32);");
			stringBuilder.AppendLine("insert into SerialNumberTransactions (sntPartID, sntPartRevisionID, sntPartWarehouseLocationID, sntPartBinID, sntSerialNumberID, sntTransactionType, sntStatus, sntTransactionDate, sntQuantity, sntJobID, sntJobAssemblyID, sntJobMaterialID, sntPartTransactionID, sntCreatedBy, sntCreatedDate, sntTableName, sntTableUniqueID) select sntPartID, sntPartRevisionID, sntPartWarehouseLocationID, sntPartBinID, sntSerialNumberID, 33, sntStatus, sntTransactionDate, sntQuantity, sntJobID,sntJobAssemblyID, sntJobMaterialID, sntPartTransactionID, 'CONVERSION' as sntCreatedBy, Getdate() as sntCreatedDate, sntTableName, sntTableUniqueID from SerialNumberTransactions where sntTransactionType = 22 and sntTableName = 'MaterialIssueLines' and sntPartTransactionID not in (select sntPartTransactionID from SerialNumberTransactions where sntTransactionType = 33); ");
			stringBuilder.AppendLine("insert into SerialNumberTransactions (sntPartID, sntPartRevisionID, sntPartWarehouseLocationID, sntPartBinID, sntSerialNumberID, sntTransactionType, sntStatus, sntTransactionDate, sntQuantity, sntJobID, sntJobAssemblyID, sntJobMaterialID, sntPartTransactionID, sntCreatedBy, sntCreatedDate, sntTableName, sntTableUniqueID) select sntPartID, sntPartRevisionID, sntPartWarehouseLocationID, sntPartBinID, sntSerialNumberID, 30, sntStatus, sntTransactionDate, sntQuantity, sntJobID,sntJobAssemblyID, sntJobMaterialID, sntPartTransactionID, 'CONVERSION' as sntCreatedBy, Getdate() as sntCreatedDate, sntTableName, sntTableUniqueID from SerialNumberTransactions where sntTransactionType = 20 and sntTableName = 'MaterialIssueLines' and sntPartTransactionID not in (select sntPartTransactionID from SerialNumberTransactions where sntTransactionType = 30); ");
			stringBuilder.AppendLine("insert into SerialNumberTransactions (sntPartID, sntPartRevisionID, sntPartWarehouseLocationID, sntPartBinID, sntSerialNumberID, sntTransactionType, sntStatus, sntTransactionDate, sntQuantity, sntJobID, sntJobAssemblyID, sntJobMaterialID, sntPartTransactionID, sntCreatedBy, sntCreatedDate, sntTableName, sntTableUniqueID) select sntPartID, sntPartRevisionID, sntPartWarehouseLocationID, sntPartBinID, sntSerialNumberID, 31, sntStatus, sntTransactionDate, sntQuantity, sntJobID,sntJobAssemblyID, sntJobMaterialID, sntPartTransactionID, 'CONVERSION' as sntCreatedBy, Getdate() as sntCreatedDate, sntTableName, sntTableUniqueID from SerialNumberTransactions where sntTransactionType = 23 and sntTableName = 'MaterialIssueLines' and sntPartTransactionID not in (select sntPartTransactionID from SerialNumberTransactions where sntTransactionType = 31); ");
			stringBuilder.AppendLine("insert into SerialNumberTransactions (sntPartID, sntPartRevisionID, sntPartWarehouseLocationID, sntPartBinID, sntSerialNumberID, sntTransactionType, sntStatus, sntTransactionDate, sntQuantity, sntJobID, sntJobAssemblyID, sntJobMaterialID, sntPartTransactionID, sntCreatedBy, sntCreatedDate, sntTableName, sntTableUniqueID) select sntPartID, sntPartRevisionID, sntPartWarehouseLocationID, sntPartBinID, sntSerialNumberID, 28, sntStatus, sntTransactionDate, sntQuantity, sntJobID,sntJobAssemblyID, sntJobMaterialID, sntPartTransactionID, 'CONVERSION' as sntCreatedBy, Getdate() as sntCreatedDate, sntTableName, sntTableUniqueID from SerialNumberTransactions where sntTransactionType = 21 and sntTableName = 'MaterialIssueLines' and sntPartTransactionID not in (select sntPartTransactionID from SerialNumberTransactions where sntTransactionType = 28); ");
			stringBuilder.AppendLine("insert into SerialNumberTransactions (sntPartID, sntPartRevisionID, sntPartWarehouseLocationID, sntPartBinID, sntSerialNumberID, sntTransactionType, sntStatus, sntTransactionDate, sntQuantity, sntJobID, sntJobAssemblyID, sntJobMaterialID, sntPartTransactionID, sntCreatedBy, sntCreatedDate, sntTableName, sntTableUniqueID) select sntPartID, sntPartRevisionID, sntPartWarehouseLocationID, sntPartBinID, sntSerialNumberID, 29, sntStatus, sntTransactionDate, sntQuantity, sntJobID,sntJobAssemblyID, sntJobMaterialID, sntPartTransactionID, 'CONVERSION' as sntCreatedBy, Getdate() as sntCreatedDate, sntTableName, sntTableUniqueID from SerialNumberTransactions where sntTransactionType = 17 and sntTableName = 'MaterialIssueLines' and sntPartTransactionID not in (select sntPartTransactionID from SerialNumberTransactions where sntTransactionType = 29); ");
			stringBuilder.AppendLine("insert into SerialNumberTransactions (sntPartID, sntPartRevisionID, sntPartWarehouseLocationID, sntPartBinID, sntSerialNumberID, sntTransactionType, sntStatus, sntTransactionDate, sntQuantity, sntJobID, sntJobAssemblyID, sntJobMaterialID, sntPartTransactionID, sntCreatedBy, sntCreatedDate, sntTableName, sntTableUniqueID) select sntPartID, sntPartRevisionID, sntPartWarehouseLocationID, sntPartBinID, sntSerialNumberID, 37, sntStatus, sntTransactionDate, sntQuantity, sntJobID,sntJobAssemblyID, sntJobMaterialID, sntPartTransactionID, 'CONVERSION' as sntCreatedBy, Getdate() as sntCreatedDate, sntTableName, sntTableUniqueID from SerialNumberTransactions where sntTransactionType = 4 and sntTableName = 'MfgReceipts' and sntPartTransactionID not in (select sntPartTransactionID from SerialNumberTransactions where sntTransactionType = 37); ");
			stringBuilder.AppendLine("insert into SerialNumberTransactions (sntPartID, sntPartRevisionID, sntPartWarehouseLocationID, sntPartBinID, sntSerialNumberID, sntTransactionType, sntStatus, sntTransactionDate, sntQuantity, sntJobID, sntJobAssemblyID, sntJobMaterialID, sntPartTransactionID, sntCreatedBy, sntCreatedDate, sntTableName, sntTableUniqueID) select sntPartID, sntPartRevisionID, sntPartWarehouseLocationID, sntPartBinID, sntSerialNumberID, 38, sntStatus, sntTransactionDate, sntQuantity, sntJobID,sntJobAssemblyID, sntJobMaterialID, sntPartTransactionID, 'CONVERSION' as sntCreatedBy, Getdate() as sntCreatedDate, sntTableName, sntTableUniqueID from SerialNumberTransactions where sntTransactionType = 2 and sntTableName = 'MfgReceipts' and sntPartTransactionID not in (select sntPartTransactionID from SerialNumberTransactions where sntTransactionType = 38); ");
			stringBuilder.AppendLine("insert into SerialNumberTransactions (sntPartID, sntPartRevisionID, sntPartWarehouseLocationID, sntPartBinID, sntSerialNumberID, sntTransactionType, sntStatus, sntTransactionDate, sntQuantity, sntJobID, sntJobAssemblyID, sntJobMaterialID, sntPartTransactionID, sntCreatedBy, sntCreatedDate, sntTableName, sntTableUniqueID) select sntPartID, sntPartRevisionID, sntPartWarehouseLocationID, sntPartBinID, sntSerialNumberID, Case When sntInspect = 0 Then 34 Else 39 End, sntStatus, sntTransactionDate, sntQuantity, sntJobID,sntJobAssemblyID, sntJobMaterialID, sntPartTransactionID, 'CONVERSION' as sntCreatedBy, Getdate() as sntCreatedDate, sntTableName, sntTableUniqueID from SerialNumberTransactions where sntTransactionType = 3 and sntTableName = 'MfgReceipts' and sntPartTransactionID not in (select sntPartTransactionID from SerialNumberTransactions where sntTransactionType = 34); ");
			stringBuilder.AppendLine("insert into SerialNumberTransactions (sntPartID, sntPartRevisionID, sntPartWarehouseLocationID, sntPartBinID, sntSerialNumberID, sntTransactionType, sntStatus, sntTransactionDate, sntQuantity, sntJobID, sntJobAssemblyID, sntJobMaterialID, sntPartTransactionID, sntCreatedBy, sntCreatedDate, sntTableName, sntTableUniqueID) select sntPartID, sntPartRevisionID, sntPartWarehouseLocationID, sntPartBinID, sntSerialNumberID, 35, sntStatus, sntTransactionDate, sntQuantity, sntJobID,sntJobAssemblyID, sntJobMaterialID, sntPartTransactionID, 'CONVERSION' as sntCreatedBy, Getdate() as sntCreatedDate, sntTableName, sntTableUniqueID from SerialNumberTransactions where sntTransactionType = 23 and sntTableName = 'MfgReceipts' and sntPartTransactionID not in (select sntPartTransactionID from SerialNumberTransactions where sntTransactionType = 35); ");
			stringBuilder.AppendLine("insert into SerialNumberTransactions (sntPartID, sntPartRevisionID, sntPartWarehouseLocationID, sntPartBinID, sntSerialNumberID, sntTransactionType, sntStatus, sntTransactionDate, sntQuantity, sntJobID, sntJobAssemblyID, sntJobMaterialID, sntPartTransactionID, sntCreatedBy, sntCreatedDate, sntTableName, sntTableUniqueID) select sntPartID, sntPartRevisionID, sntPartWarehouseLocationID, sntPartBinID, sntSerialNumberID, 39, sntStatus, sntTransactionDate, sntQuantity, sntJobID,sntJobAssemblyID, sntJobMaterialID, sntPartTransactionID, 'CONVERSION' as sntCreatedBy, Getdate() as sntCreatedDate, sntTableName, sntTableUniqueID from SerialNumberTransactions where sntTransactionType = 13 and sntTableName = 'MfgReceipts' and sntPartTransactionID not in (select sntPartTransactionID from SerialNumberTransactions where sntTransactionType = 39); ");
			parms.ServerManager.ExecuteCommand(null, parms.User, parms.DatabaseName, stringBuilder.ToString());
		}
	}
}
