using System.Collections.Generic;
using System.Text;
using M1.Core;

namespace M1.Ax.Erp.DD;

[DBConversion("9.1.069", "Update product configurator code for references to App properties and methods", "2016-06-06")]
public class v91069b
{
	public v91069b(DBConversionParms parms)
	{
		List<TranslateInfo> list = new List<TranslateInfo>();
		list.AddRange(new TranslateInfo[192]
		{
			new TranslateInfo("App.CalculateQtyWithScrap", "App.JobFunctions.CalculateQtyWithScrap", ignoreCase: true),
			new TranslateInfo("App.CalculateProductionHours", "App.JobFunctions.CalculateProductionHours", ignoreCase: true),
			new TranslateInfo("App.CalculateDiscountAndDueDate", "App.Financial.CalculateDiscountAndDueDate", ignoreCase: true),
			new TranslateInfo("App.CalculateTaxOnTotal", "App.Financial.CalculateTaxOnTotal", ignoreCase: true),
			new TranslateInfo("App.CalculateTaxOnSubTotal", "App.Financial.CalculateTaxOnSubTotal", ignoreCase: true),
			new TranslateInfo("App.CalculateSecondaryTax", "App.Financial.CalculateSecondaryTax", ignoreCase: true),
			new TranslateInfo("App.ExchangeCurrency", "App.LegacyFunctions.ExchangeCurrency", ignoreCase: true),
			new TranslateInfo("App.RefreshCurrencyForDetails", "App.LegacyFunctions.RefreshCurrencyForDetails", ignoreCase: true),
			new TranslateInfo("App.GetExchangeRate", "App.Financial.GetExchangeRate", ignoreCase: true),
			new TranslateInfo("App.OrgMemoCheck", "App.LegacyFunctions.OrgMemoCheck", ignoreCase: true),
			new TranslateInfo("App.PartMemoCheck", "App.LegacyFunctions.PartMemoCheck", ignoreCase: true),
			new TranslateInfo("App.RunCustomAppCode", "App.Script.RunCustomAppCode", ignoreCase: true),
			new TranslateInfo("App.DatasetID", "Mid(App.Database,4)", ignoreCase: true),
			new TranslateInfo("App.ShowAboutForm", "Forms.Show.About", ignoreCase: true),
			new TranslateInfo("App.ShowCallQueue", "Forms.Show.CallQueue", ignoreCase: true),
			new TranslateInfo("App.ShowChangeLog", "Forms.Show.ChangeLog", ignoreCase: true),
			new TranslateInfo("App.ShowChangePasswordForm", "Forms.Show.ChangePassword", ignoreCase: true),
			new TranslateInfo("App.ShowCompanyMessageForm", "Forms.Show.CompanyMessage", ignoreCase: true),
			new TranslateInfo("App.ShowConflictsForm", "Forms.Show.Conflicts", ignoreCase: true),
			new TranslateInfo("App.CreateQuickCall", "Forms.Show.QuickCall", ignoreCase: true),
			new TranslateInfo("App.ShowCreditCardPaymentNET1Form", "Forms.Show.CreditCardPaymentNET1", ignoreCase: true),
			new TranslateInfo("App.ShowCreditCardPaymentNET1WizardForm", "Forms.Show.CreditCardPaymentNET1Wizard", ignoreCase: true),
			new TranslateInfo("App.ShowCurrentActivityForm", "Forms.Show.CurrentActivity", ignoreCase: true),
			new TranslateInfo("App.ShowCurrentSqlConnectionsForm", "Forms.Show.CurrentSqlConnections", ignoreCase: true),
			new TranslateInfo("App.ShowCustomForm", "Forms.Show.CustomForm", ignoreCase: true),
			new TranslateInfo("App.ShowCustomizeGridForm", "Forms.Show.CustomizeGrid", ignoreCase: true),
			new TranslateInfo("App.ShowDatabaseOptionsForm", "Forms.Show.DatabaseOptions", ignoreCase: true),
			new TranslateInfo("App.ShowDataMapManager", "Forms.Show.DataMapManager", ignoreCase: true),
			new TranslateInfo("App.ShowDesignStudio", "Forms.Show.DesignStudio", ignoreCase: true),
			new TranslateInfo("App.ShowFormulaEditorForm", "Forms.Show.FormulaEditor", ignoreCase: true),
			new TranslateInfo("App.MapLocation", "Forms.Show.MapLocation", ignoreCase: true),
			new TranslateInfo("App.ShowOpenWithEditor", "Forms.Show.OpenWithEditor", ignoreCase: true),
			new TranslateInfo("App.ShowPayPalPasswordForm", "Forms.Show.PayPalPassword", ignoreCase: true),
			new TranslateInfo("App.ShowProductConfiguratorForm", "Forms.Show.ProductConfigurator", ignoreCase: true),
			new TranslateInfo("App.ShowPurgeForm", "Forms.Show.Purge", ignoreCase: true),
			new TranslateInfo("App.RunQuery", "Forms.Show.RunQuery", ignoreCase: true),
			new TranslateInfo("App.SaveAs", "Forms.Show.SaveAs", ignoreCase: true),
			new TranslateInfo("App.ShowScheduleMoveOperations", "Forms.Show.ScheduleMoveOperations", ignoreCase: true),
			new TranslateInfo("App.ShowSelectDatasetsForm", "Forms.Show.SelectDatasets", ignoreCase: true),
			new TranslateInfo("App.ShowSelectFieldsForm", "Forms.Show.SelectFields", ignoreCase: true),
			new TranslateInfo("App.ShowSelectGridForm", "Forms.Show.SelectGrid", ignoreCase: true),
			new TranslateInfo("App.ShowSetDefaultValueForm", "Forms.Show.SetDefaultValue", ignoreCase: true),
			new TranslateInfo("App.ShowSpellCheck", "Forms.Show.SpellCheck", ignoreCase: true),
			new TranslateInfo("App.ShowTableSecurityAccessWizard", "Forms.Show.TableSecurityAccessWizard", ignoreCase: true),
			new TranslateInfo("App.ShowUserAdministrationForm", "Forms.Show.UserAdministration", ignoreCase: true),
			new TranslateInfo("App.ShowUserOptionsForm", "Forms.Show.UserOptions", ignoreCase: true),
			new TranslateInfo("App.ShowValidationMsg", "Forms.Show.ValidationMessage", ignoreCase: true),
			new TranslateInfo("App.ShowWhereUsed", "Forms.Show.WhereUsed", ignoreCase: true),
			new TranslateInfo("App.OpenPhoneManager", "Forms.Show.PhoneManager", ignoreCase: true),
			new TranslateInfo("App.OpenM1Explorer", "Forms.Show.M1Explorer", ignoreCase: true),
			new TranslateInfo("App.OpenSearch", "Forms.Show.Search", ignoreCase: true),
			new TranslateInfo("App.PromptToScheduleJob", "Forms.Show.ScheduleJob", ignoreCase: true),
			new TranslateInfo("App.PrintRelatedDocuments", "Forms.Show.PrintRelatedDocuments", ignoreCase: true),
			new TranslateInfo("App.PromptToSearch", "Forms.Show.Search", ignoreCase: true),
			new TranslateInfo("App.PromptForAppointmentColor", "Forms.CommonDialogs.AppointmentColor", ignoreCase: true),
			new TranslateInfo("App.ActivateExplorerObjectById", "Forms.Show.ExplorerObject", ignoreCase: true),
			new TranslateInfo("App.ActivateExplorerSearchByGridID", "Forms.Show.ExplorerSearch", ignoreCase: true),
			new TranslateInfo("App.OpenReport", "Forms.Report.Open", ignoreCase: true),
			new TranslateInfo("App.RunReport", "Forms.Report.Run", ignoreCase: true),
			new TranslateInfo("App.RunReportByTableKeys", "Forms.Report.RunByTableKeys", ignoreCase: true),
			new TranslateInfo("App.JobFunctions.ShowScheduleJobsForm", "Forms.Show.ScheduleJobs", ignoreCase: true),
			new TranslateInfo("App.JobFunctions.PromptToScheduleJob", "Forms.Show.ScheduleJob", ignoreCase: true),
			new TranslateInfo("App.JobFunctions.OpenJobWizard", "Forms.Show.JobWizard", ignoreCase: true),
			new TranslateInfo("App.JobFunctions.OpenSchedulingBoard", "Forms.Show.SchedulingBoard", ignoreCase: true),
			new TranslateInfo("App.TimecardFunctions.ShowLeaveBoard", "Forms.Show.LeaveBoard", ignoreCase: true),
			new TranslateInfo("App.POFunctions.OpenPOWizard", "Forms.Show.PurchasingWizard", ignoreCase: true),
			new TranslateInfo("App.ExportRs.MailMerge", "Forms.MailMerge", ignoreCase: true),
			new TranslateInfo("App.ExportRs.Prompt", "Forms.CommonDialogs.Export", ignoreCase: true),
			new TranslateInfo("App.ImportFunctions.ExportFile", "Forms.CommonDialogs.DataMapExport", ignoreCase: true),
			new TranslateInfo("App.ImportFunctions.ImportFile", "Forms.CommonDialogs.DataMapImport", ignoreCase: true),
			new TranslateInfo("App.CommonDialogs.", "Forms.CommonDialogs.", ignoreCase: true),
			new TranslateInfo("App.ExportRs.", "App.Export.", ignoreCase: true),
			new TranslateInfo("App.LoadForm", "Forms.LoadForm", ignoreCase: true),
			new TranslateInfo("App.LoadFormReturn", "Forms.LoadFormReturn", ignoreCase: true),
			new TranslateInfo("App.OpenForm", "Forms.OpenForm", ignoreCase: true),
			new TranslateInfo("App.ShowForm", "Forms.ShowForm", ignoreCase: true),
			new TranslateInfo("App.MsgWindow", "Forms.MessageWindow", ignoreCase: true),
			new TranslateInfo("App.MessageBox", "Forms.MessageBox", ignoreCase: true),
			new TranslateInfo("App.CloseForm", "Forms.CloseForm", ignoreCase: true),
			new TranslateInfo("App.ForceForegroundWindow", "Forms.ForceForegroundWindow", ignoreCase: true),
			new TranslateInfo("App.GetActiveHwnd", "Forms.GetActiveHwnd", ignoreCase: true),
			new TranslateInfo("App.GetFormFromHwnd", "Forms.GetFormFromHwnd", ignoreCase: true),
			new TranslateInfo("App.GetFormHwnd", "Forms.GetFormHwnd", ignoreCase: true),
			new TranslateInfo("App.IsFormOpen", "Forms.IsFormOpen", ignoreCase: true),
			new TranslateInfo("App.MousePointer", "Forms.MousePointer", ignoreCase: true),
			new TranslateInfo("App.PlaySound", "Forms.PlaySound", ignoreCase: true),
			new TranslateInfo("App.SetFocusToForm", "Forms.SetFocusToForm", ignoreCase: true),
			new TranslateInfo("App.OpenHelp", "Forms.OpenHelp", ignoreCase: true),
			new TranslateInfo("App.RunScript", "Forms.RunScript", ignoreCase: true),
			new TranslateInfo("App.OpenObject", "Forms.OpenObject", ignoreCase: true),
			new TranslateInfo("App.ShellPrintDocument", "Forms.ShellOpenDocument", ignoreCase: true),
			new TranslateInfo("App.ShellOpenDoc", "Forms.ShellOpenDocument", ignoreCase: true),
			new TranslateInfo("App.ShellExecute", "Forms.ShellExecute", ignoreCase: true),
			new TranslateInfo("App.SendMessageEx", "Forms.SendEmail", ignoreCase: true),
			new TranslateInfo("App.SendMessage", "Forms.SendEmail", ignoreCase: true),
			new TranslateInfo("App.SendHTMLMessage", "Forms.SendEmail", ignoreCase: true),
			new TranslateInfo("App.OpenBlankEmail", "Forms.SendEmail", ignoreCase: true),
			new TranslateInfo("App.SendCodeAsAttachment", "Forms.SendCodeAsAttachment", ignoreCase: true),
			new TranslateInfo("App.SendChangeRequestEmail", "Forms.Ax(\"ChangeRequests\").SendChangeRequestEmail", ignoreCase: true),
			new TranslateInfo("App.ExportFollowUpToOutlook", "Forms.Ax(\"FollowUps\").ExportFollowUpToOutlook", ignoreCase: true),
			new TranslateInfo("App.ExportScheduleToOutlook", "Forms.Ax(\"Jobs\").ExportScheduleToOutlook", ignoreCase: true),
			new TranslateInfo("App.ExportEmployeeToOutlook", "Forms.Ax(\"Employees\").ExportEmployeeToOutlook", ignoreCase: true),
			new TranslateInfo("App.RefreshFollowupsFromOutlook", "Forms.Ax(\"FollowUps\").RefreshFollowupsFromOutlook", ignoreCase: true),
			new TranslateInfo("App.Clipboard", "Forms.Clipboard", ignoreCase: true),
			new TranslateInfo("App.AddQuotes", "App.Convert.StringToSql", ignoreCase: true),
			new TranslateInfo("App.ConvertNumberToSql", "App.Convert.NumberToSql", ignoreCase: true),
			new TranslateInfo("App.ConvertDateTimeToSql", "App.Convert.DateTimeToSql", ignoreCase: true),
			new TranslateInfo("App.ConvertDateToSQL", "App.Convert.DateToSql", ignoreCase: true),
			new TranslateInfo("App.ConvertUnknownToSQL", "App.Convert.ToSql", ignoreCase: true),
			new TranslateInfo("App.FormatUnknownForScript", "App.Convert.ToScript", ignoreCase: true),
			new TranslateInfo("App.Forms", "Forms", ignoreCase: true),
			new TranslateInfo("App.GetYearAndPeriod", "App.Ax(\"Financial\").GetYearAndPeriod", ignoreCase: true),
			new TranslateInfo("App.GetYear", "App.Ax(\"Financial\").GetYear", ignoreCase: true),
			new TranslateInfo("App.GetFiscalYearStartDate", "App.Ax(\"Financial\").GetFiscalYearStartDate", ignoreCase: true),
			new TranslateInfo("App.GetFiscalYearEndDate", "App.Ax(\"Financial\").GetFiscalYearEndDate", ignoreCase: true),
			new TranslateInfo("App.GetPeriod", "App.Ax(\"Financial\").GetPeriod", ignoreCase: true),
			new TranslateInfo("App.ARFunctions.DisableTaxFields", "App.Ax(\"AR\").DisableTaxFields", ignoreCase: true),
			new TranslateInfo("App.APFunctions.DisableTaxFields", "App.Ax(\"AP\").DisableTaxFields", ignoreCase: true),
			new TranslateInfo("App.SendEmployeeMessage", "App.Ax(\"Employee\").SendEmployeeMessage", ignoreCase: true),
			new TranslateInfo("App.DoRoleCheck", "Forms.DoRoleCheck", ignoreCase: true),
			new TranslateInfo("App.DoReportCheck", "Forms.DoReportCheck", ignoreCase: true),
			new TranslateInfo("App.DoRoleByTableCheck", "Forms.DoRoleByTableCheck", ignoreCase: true),
			new TranslateInfo("App.ARFunctions.", "App.Ax(\"ARFunctions\").", ignoreCase: true),
			new TranslateInfo("App.APFunctions.", "App.Ax(\"APFunctions\").", ignoreCase: true),
			new TranslateInfo("App.GLFunctions.", "App.Ax(\"GLFunctions\").", ignoreCase: true),
			new TranslateInfo("App.LeadFunctions.", "App.Ax(\"LeadFunctions\").", ignoreCase: true),
			new TranslateInfo("App.QuoteFunctions.", "App.Ax(\"QuoteFunctions\").", ignoreCase: true),
			new TranslateInfo("App.OrderFunctions.", "App.Ax(\"OrderFunctions\").", ignoreCase: true),
			new TranslateInfo("App.ClaimFunctions.", "App.Ax(\"ClaimFunctions\").", ignoreCase: true),
			new TranslateInfo("App.ShipmentFunctions.", "App.Ax(\"ShipmentFunctions\").", ignoreCase: true),
			new TranslateInfo("App.FreightFunctions.", "App.Ax(\"FreightFunctions\").", ignoreCase: true),
			new TranslateInfo("App.ReceiptFunctions.", "App.Ax(\"ReceiptFunctions\").", ignoreCase: true),
			new TranslateInfo("App.RFQFunctions.", "App.Ax(\"RFQFunctions\").", ignoreCase: true),
			new TranslateInfo("App.POFunctions.", "App.Ax(\"POFunctions\").", ignoreCase: true),
			new TranslateInfo("App.QAFunctions.", "App.Ax(\"QAFunctions\").", ignoreCase: true),
			new TranslateInfo("App.ProjectFunctions.", "App.Ax(\"ProjectFunctions\").", ignoreCase: true),
			new TranslateInfo("App.JobFunctions.", "App.Ax(\"JobFunctions\").", ignoreCase: true),
			new TranslateInfo("App.PartFunctions.", "App.Ax(\"PartFunctions\").", ignoreCase: true),
			new TranslateInfo("App.TimecardFunctions.", "App.Ax(\"TimecardFunctions\").", ignoreCase: true),
			new TranslateInfo("App.LandedCostFunctions.", "App.Ax(\"LandedCostFunctions\").", ignoreCase: true),
			new TranslateInfo("App.PayrollFunctions.", "App.Ax(\"PayrollFunctions\").", ignoreCase: true),
			new TranslateInfo("Forms.Show.ScheduleMoveOperations", "Forms.Ax(\"Jobs\").ShowScheduleMoveOperations", ignoreCase: true),
			new TranslateInfo("Forms.Show.ScheduleJobs", "Forms.Ax(\"Jobs\").ShowScheduleJobs", ignoreCase: true),
			new TranslateInfo("Forms.Show.ScheduleJob", "Forms.Ax(\"Jobs\").ShowScheduleJob", ignoreCase: true),
			new TranslateInfo("Forms.Show.JobWizard", "Forms.Ax(\"Jobs\").ShowJobWizard", ignoreCase: true),
			new TranslateInfo("Forms.Show.SchedulingBoard", "Forms.Ax(\"Jobs\").ShowSchedulingBoard", ignoreCase: true),
			new TranslateInfo("Forms.Show.CallQueue", "Forms.Ax(\"Calls\").ShowCallQueue", ignoreCase: true),
			new TranslateInfo("Forms.Show.QuickCall", "Forms.Ax(\"Calls\").ShowQuickCall", ignoreCase: true),
			new TranslateInfo("Forms.Show.RFQSavePrices", "Forms.Ax(\"Rfqs\").ShowRfqSavePrices", ignoreCase: true),
			new TranslateInfo("Forms.Show.RFQPullQuote", "Forms.Ax(\"Rfqs\").ShowRfqPullQuote", ignoreCase: true),
			new TranslateInfo("Forms.Show.RFQPullJob", "Forms.Ax(\"Rfqs\").ShowRfqPullJob", ignoreCase: true),
			new TranslateInfo("Forms.Show.RFQUpdateSelectedSuppliers", "Forms.Ax(\"Rfqs\").ShowRfqUpdateSelectedSuppliers", ignoreCase: true),
			new TranslateInfo("Forms.Show.CreatePOFromRFQ", "Forms.Ax(\"Rfqs\").ShowCreatePOFromRFQ", ignoreCase: true),
			new TranslateInfo("Forms.Show.CreditCardPaymentNET1Wizard", "Forms.Ax(\"Financial\").CreditCardPaymentNET1Wizard", ignoreCase: true),
			new TranslateInfo("Forms.Show.CreditCardPaymentNET1", "Forms.Ax(\"Financial\").CreditCardPaymentNET1", ignoreCase: true),
			new TranslateInfo("Forms.Show.PurchasingWizard", "Forms.Ax(\"PurchaseOrders\").ShowPurchasingWizard", ignoreCase: true),
			new TranslateInfo("Forms.Show.LeaveBoard", "Forms.Ax(\"Payroll\").ShowLeaveBoard", ignoreCase: true),
			new TranslateInfo("App.BuyQuantityDecimals", "App.Ax(\"Production\").BuyQuantityDecimals", ignoreCase: true),
			new TranslateInfo("App.SellQuantityDecimals", "App.Ax(\"Production\").SellQuantityDecimals", ignoreCase: true),
			new TranslateInfo("App.InventoryQuantityDecimals", "App.Ax(\"Production\").InventoryQuantityDecimals", ignoreCase: true),
			new TranslateInfo("App.BuyerID", "App.Ax(\"Production\").BuyerID", ignoreCase: true),
			new TranslateInfo("App.BuyerAmount", "App.Ax(\"Production\").BuyerAmount", ignoreCase: true),
			new TranslateInfo("App.InspectorID", "App.Ax(\"Production\").InspectorID", ignoreCase: true),
			new TranslateInfo("App.InspectorAmount", "App.Ax(\"Production\").InspectorAmount", ignoreCase: true),
			new TranslateInfo("App.EngineerID", "App.Ax(\"Production\").EngineerID", ignoreCase: true),
			new TranslateInfo("App.PlannerID", "App.Ax(\"Production\").PlannerID", ignoreCase: true),
			new TranslateInfo("App.SalesPersonID", "App.Ax(\"Production\").SalesPersonID", ignoreCase: true),
			new TranslateInfo("App.SalesPersonAmount", "App.Ax(\"Production\").SalesPersonAmount", ignoreCase: true),
			new TranslateInfo("App.UserEmployeeID", "App.Ax(\"Production\").EmployeeID", ignoreCase: true),
			new TranslateInfo("App.UserPlantID", "App.Ax(\"Production\").PlantID", ignoreCase: true),
			new TranslateInfo("App.UserPlantDepartmentID", "App.Ax(\"Production\").PlantDepartmentID", ignoreCase: true),
			new TranslateInfo("App.PaypalActivated", "App.Ax(\"Financial\").PaypalActivated", ignoreCase: true),
			new TranslateInfo("App.NET1Activated", "App.Ax(\"Financial\").NET1Activated", ignoreCase: true),
			new TranslateInfo("App.ViewOnlyUser", "App.Security.ViewOnlyUser", ignoreCase: true),
			new TranslateInfo("App.IsUserInRole", "App.Security.IsInRole", ignoreCase: true),
			new TranslateInfo("App.IsUserInRoleByTable", "App.Security.IsInRoleByTable", ignoreCase: true),
			new TranslateInfo("App.GetObjectAccessLevel", "App.Security.GetObjectAccessLevel", ignoreCase: true),
			new TranslateInfo("App.GetTableAccessLevel", "App.Security.GetTableAccessLevel", ignoreCase: true),
			new TranslateInfo("App.GetGridAccessLevel", "App.Security.GetGridAccessLevel", ignoreCase: true),
			new TranslateInfo("App.GetFormAccessLevel", "App.Security.GetFormAccessLevel", ignoreCase: true),
			new TranslateInfo("App.GetModuleAccessLevel", "App.Security.GetModuleAccessLevel", ignoreCase: true),
			new TranslateInfo("App.GetReportAccessLevel", "App.Security.GetReportAccessLevel", ignoreCase: true),
			new TranslateInfo("App.IsAccessType", "App.Security.IsAccessType", ignoreCase: true),
			new TranslateInfo("App.GetAttachmentPath", "App.Ax(\"Organizations\").GetAttachmentPath", ignoreCase: true),
			new TranslateInfo("App.Ax(\"QuoteFunctions\").TransferQuoteToFollowup", "App.Ax(\"FollowUps\").TransferQuoteToFollowup", ignoreCase: true),
			new TranslateInfo("App.Ax(\"OrderFunctions\").ShowOrderBacklogSearchForReceipt", "Forms.Ax(\"SalesOrders\").ShowOrderBacklogSearchForReceipt", ignoreCase: true),
			new TranslateInfo("App.Ax(\"PartFunctions\").IsKitPart", "App.Ax(\"Part\").IsKitPart", ignoreCase: true),
			new TranslateInfo("App.Ax(\"PartFunctions\").RefreshPartAllocations", "App.Ax(\"Part\").RefreshPartAllocations", ignoreCase: true),
			new TranslateInfo("App.Ax(\"PartFunctions\").RefreshOnOrderQuantitesSales", "App.Ax(\"Part\").RefreshOnOrderQuantitesSales", ignoreCase: true),
			new TranslateInfo("App.Ax(\"PartFunctions\").RefreshOnOrderQuantitesPurchases", "App.Ax(\"Part\").RefreshOnOrderQuantitesPurchases", ignoreCase: true),
			new TranslateInfo("App.Ax(\"QuoteFunctions\").RefreshMatrix", "App.Ax(\"Quote\").RefreshMatrix", ignoreCase: true),
			new TranslateInfo("Call App.PayrollFunctions.ShowLoadTaxTablesForm(\"Import\")", "Forms.OpenProcessForm \"M1.Ax.Erp.ImportTaxTableProcess\"", ignoreCase: true)
		});
		StringBuilder stringBuilder = new StringBuilder();
		stringBuilder.AppendLine("begin");
		stringBuilder.AppendLine("SET NOCOUNT ON");
		stringBuilder.AppendLine("DECLARE");
		stringBuilder.AppendLine("@SQL varchar(max)");
		stringBuilder.AppendLine("set @sql = '");
		foreach (TranslateInfo item in list)
		{
			stringBuilder.AppendLine("Update FormDefinitions Set xaoCode = Replace(xaoCode, ''" + item.SourceText + "'', ''" + item.DestinationText + "'') where xaoCode is not null and xaoCode like ''%" + item.SourceText + "%'' and xaoCustom = 1;");
			stringBuilder.AppendLine("Update PartRules Set pcrCode = Replace(pcrCode, ''" + item.SourceText + "'', ''" + item.DestinationText + "'') where pcrCode is not null and pcrCode like ''%" + item.SourceText + "%'';");
		}
		stringBuilder.AppendLine("'");
		stringBuilder.AppendLine("exec(@sql)");
		stringBuilder.AppendLine("SET NOCOUNT OFF");
		stringBuilder.AppendLine("end;");
		parms.ServerManager.ExecuteCommand(null, parms.User, parms.DatabaseName, stringBuilder.ToString());
		list = null;
	}
}
