using System.Text;
using M1.Core;

namespace M1.Ax.Erp.DD;

[DBConversion("9.2.085", "PartTransactionCosts conversion", "2017-01-24")]
public class v92085b
{
	public v92085b(DBConversionParms parms)
	{
		if (parms.Dmo.DoesTableExist(null, parms.User, parms.DatabaseName, "PartTransactionCosts"))
		{
			StringBuilder stringBuilder = new StringBuilder();
			stringBuilder.AppendLine("begin");
			stringBuilder.AppendLine("SET NOCOUNT ON");
			stringBuilder.AppendLine("DECLARE");
			stringBuilder.AppendLine("@SQL varchar(max)");
			stringBuilder.AppendLine("set @sql = '");
			stringBuilder.AppendLine("SET NOCOUNT ON");
			stringBuilder.AppendLine("DECLARE");
			stringBuilder.AppendLine("@costing_method\t\t AS INT,");
			stringBuilder.AppendLine("@s1\t\t\t\t\t AS char(560),");
			stringBuilder.AppendLine("@rec_count\t\t\t AS INT");
			stringBuilder.AppendLine("SET @costing_method = (Select xapIMCostingMethod From ProductionProperties);");
			stringBuilder.AppendLine("DECLARE TRANS_CURSOR CURSOR FOR");
			stringBuilder.AppendLine("Select ");
			stringBuilder.AppendLine("RIGHT(space(15) + LTrim(Convert(char(15), imtPartTransactionID)), 15) + --1 to 15");
			stringBuilder.AppendLine("RIGHT(space(20) + LTrim(Convert(char(20), imtInventoryQuantityReceived + imtQuantityToInspect + imtQuantityToReturn + imtScrapQuantity)), 20) + --16 to 35");
			stringBuilder.AppendLine("RIGHT(space(20) + LTrim(Convert(char(20), imtUnitLaborCost)), 20) + --36 to 55");
			stringBuilder.AppendLine("RIGHT(space(20) + LTrim(Convert(char(20), imtUnitOverheadCost)), 20) + --56 to 75");
			stringBuilder.AppendLine("RIGHT(space(20) + LTrim(Convert(char(20), imtUnitMaterialCost)), 20) + --76 to 95");
			stringBuilder.AppendLine("RIGHT(space(20) + LTrim(Convert(char(20), imtUnitSubcontractCost)), 20) + --96 to 115");
			stringBuilder.AppendLine("RIGHT(space(20) + LTrim(Convert(char(20), imtUnitDutyCost)), 20) + --116 to 135");
			stringBuilder.AppendLine("RIGHT(space(20) + LTrim(Convert(char(20), imtUnitFreightCost)), 20) + --136 to 155");
			stringBuilder.AppendLine("RIGHT(space(20) + LTrim(Convert(char(20), imtUnitMiscCost)), 20) + --156 to 175");
			stringBuilder.AppendLine("RIGHT(space(20) + LTrim(Convert(char(20), imtPrevUnitLaborCost)), 20) + --176 to 195");
			stringBuilder.AppendLine("RIGHT(space(20) + LTrim(Convert(char(20), imtPrevUnitOverheadCost)), 20) + --196 to 215");
			stringBuilder.AppendLine("RIGHT(space(20) + LTrim(Convert(char(20), imtPrevUnitMaterialCost)), 20) + --216 to 235");
			stringBuilder.AppendLine("RIGHT(space(20) + LTrim(Convert(char(20), imtPrevUnitSubcontractCost)), 20) + --236 to 255");
			stringBuilder.AppendLine("RIGHT(space(20) + LTrim(Convert(char(20), imtPrevUnitDutyCost)), 20) + --256 to 275");
			stringBuilder.AppendLine("RIGHT(space(20) + LTrim(Convert(char(20), imtPrevUnitFreightCost)), 20) + --276 to 295");
			stringBuilder.AppendLine("RIGHT(space(20) + LTrim(Convert(char(20), imtPrevUnitMiscCost)), 20) + --296 to 315");
			stringBuilder.AppendLine("RIGHT(space(20) + LTrim(Convert(char(20), imtActualUnitLaborCost)), 20) + --316 to 335");
			stringBuilder.AppendLine("RIGHT(space(20) + LTrim(Convert(char(20), imtActualUnitOverheadCost)), 20) + --336 to 355");
			stringBuilder.AppendLine("RIGHT(space(20) + LTrim(Convert(char(20), imtActualUnitMaterialCost)), 20) + --356 to 375");
			stringBuilder.AppendLine("RIGHT(space(20) + LTrim(Convert(char(20), imtActualUnitSubcontractCost)), 20) + --376 to 395");
			stringBuilder.AppendLine("RIGHT(space(20) + LTrim(Convert(char(20), imtActualUnitDutyCost)), 20) + --396 to 415");
			stringBuilder.AppendLine("RIGHT(space(20) + LTrim(Convert(char(20), imtActualUnitFreightCost)), 20) + --416 to 435");
			stringBuilder.AppendLine("RIGHT(space(20) + LTrim(Convert(char(20), imtActualUnitMiscCost)), 20) + --436 to 455");
			stringBuilder.AppendLine("RIGHT(space(20) + LTrim(Convert(char(20), imtUnitCostAverage)), 20) + --456 to 475");
			stringBuilder.AppendLine("RIGHT(space(20) + LTrim(Convert(char(20), imtUnitCostLast)), 20) + --476 to 495");
			stringBuilder.AppendLine("RIGHT(space(20) + LTrim(Convert(char(20), imtUnitCostStandard)), 20) + --496 to 515");
			stringBuilder.AppendLine("RIGHT(space(45) + IsNull(LTrim(Convert(char(45), imgUniqueID)), ''00000000-0000-0000-0000-000000000000''), 45)-- 516 to 560");
			stringBuilder.AppendLine("As s1");
			stringBuilder.AppendLine("from PartTransactions Left Join PartBinDetails On imtPartID=imgPartID And imtPartRevisionID=imgPartRevisionID And imtPartWarehouseLocationID=imgWarehouseID And imtPartBinID=imgPartBinID and IsNull(imgQuantityType,1) = 1;");
			stringBuilder.AppendLine("Set @rec_count = 0;");
			stringBuilder.AppendLine("Begin Transaction");
			stringBuilder.AppendLine("Truncate Table PartTransactionCosts;");
			stringBuilder.AppendLine("OPEN TRANS_CURSOR");
			stringBuilder.AppendLine("FETCH NEXT FROM TRANS_CURSOR");
			stringBuilder.AppendLine("INTO @s1");
			stringBuilder.AppendLine("WHILE (@@FETCH_STATUS = 0)");
			stringBuilder.AppendLine("BEGIN");
			stringBuilder.AppendLine("\tSet @rec_count = @rec_count + 1;");
			stringBuilder.AppendLine("\t\t");
			stringBuilder.AppendLine("\tIF @costing_method = 1 Or @costing_method = 4 Or @costing_method = 5 -- Average");
			stringBuilder.AppendLine("\tBEGIN");
			stringBuilder.AppendLine("\t\tInsert Into PartTransactionCosts (intPartTransactionID,intPartTransactionCostID,intCostType,intQuantity,");
			stringBuilder.AppendLine("\t\t\tintUnitLaborCost,intUnitOverheadCost,intUnitMaterialCost,intUnitSubcontractCost,intUnitDutyCost,intUnitFreightCost,intUnitMiscCost,");
			stringBuilder.AppendLine("\t\t\tintPrevUnitLaborCost,intPrevUnitOverheadCost,intPrevUnitMaterialCost,intPrevUnitSubcontractCost,intPrevUnitDutyCost,intPrevUnitFreightCost,intPrevUnitMiscCost,");
			stringBuilder.AppendLine("\t\t\tintActualUnitLaborCost,intActualUnitOverheadCost,intActualUnitMaterialCost,intActualUnitSubcontractCost,intActualUnitDutyCost,intActualUnitFreightCost,intActualUnitMiscCost,");
			stringBuilder.AppendLine("\t\t\tintCreatedBy,intCreatedDate,intSourceTableName,intSourceTableUniqueID) ");
			stringBuilder.AppendLine("\t\tValues ");
			stringBuilder.AppendLine("\t\t(Convert(Int, LTrim(SUBSTRING(@s1, 1, 15))), 1, 1, Convert(Decimal(15,5), LTrim(SUBSTRING(@s1, 16, 20))), -- average");
			stringBuilder.AppendLine("\t\tConvert(Decimal(15,5), LTrim(SUBSTRING(@s1, 36, 20))), Convert(Decimal(15,5), LTrim(SUBSTRING(@s1, 56, 20))), Convert(Decimal(15,5), LTrim(SUBSTRING(@s1, 76, 20))), Convert(Decimal(15,5), LTrim(SUBSTRING(@s1, 96, 20))), Convert(Decimal(15,5), LTrim(SUBSTRING(@s1, 116, 20))), Convert(Decimal(15,5), LTrim(SUBSTRING(@s1, 136, 20))), Convert(Decimal(15,5), LTrim(SUBSTRING(@s1, 156, 20))), ");
			stringBuilder.AppendLine("\t\tConvert(Decimal(15,5), LTrim(SUBSTRING(@s1, 176, 20))), Convert(Decimal(15,5), LTrim(SUBSTRING(@s1, 196, 20))), Convert(Decimal(15,5), LTrim(SUBSTRING(@s1, 216, 20))), Convert(Decimal(15,5), LTrim(SUBSTRING(@s1, 236, 20))), Convert(Decimal(15,5), LTrim(SUBSTRING(@s1, 256, 20))), Convert(Decimal(15,5), LTrim(SUBSTRING(@s1, 276, 20))), Convert(Decimal(15,5), LTrim(SUBSTRING(@s1, 296, 20))), ");
			stringBuilder.AppendLine("\t\tConvert(Decimal(15,5), LTrim(SUBSTRING(@s1, 316, 20))), Convert(Decimal(15,5), LTrim(SUBSTRING(@s1, 336, 20))), Convert(Decimal(15,5), LTrim(SUBSTRING(@s1, 356, 20))), Convert(Decimal(15,5), LTrim(SUBSTRING(@s1, 376, 20))), Convert(Decimal(15,5), LTrim(SUBSTRING(@s1, 396, 20))), Convert(Decimal(15,5), LTrim(SUBSTRING(@s1, 416, 20))), Convert(Decimal(15,5), LTrim(SUBSTRING(@s1, 436, 20))),");
			stringBuilder.AppendLine("\t\t''CONVERSION'',GETDATE(),''PartBinDetails'',Convert(Varchar(45), LTrim(SUBSTRING(@s1, 516, 45)))),");
			stringBuilder.AppendLine("\t\t(Convert(Int, LTrim(SUBSTRING(@s1, 1, 15))), 2, 2, Convert(Decimal(15,5), LTrim(SUBSTRING(@s1, 16, 20))),  -- last");
			stringBuilder.AppendLine("\t\t0, 0, Convert(Decimal(15,5), LTrim(SUBSTRING(@s1, 476, 20))), 0, 0, 0, 0, ");
			stringBuilder.AppendLine("\t\t0, 0, 0, 0, 0, 0, 0, ");
			stringBuilder.AppendLine("\t\t0, 0, Convert(Decimal(15,5), LTrim(SUBSTRING(@s1, 476, 20))), 0, 0, 0, 0, ");
			stringBuilder.AppendLine("\t\t''CONVERSION'',GETDATE(),''PartBinDetails'',Convert(Varchar(45), LTrim(SUBSTRING(@s1, 516, 45)))),");
			stringBuilder.AppendLine("\t\t(Convert(Int, LTrim(SUBSTRING(@s1, 1, 15))), 3, 3, Convert(Decimal(15,5), LTrim(SUBSTRING(@s1, 16, 20))), -- standard");
			stringBuilder.AppendLine("\t\t0, 0, Convert(Decimal(15,5), LTrim(SUBSTRING(@s1, 496, 20))), 0, 0, 0, 0, ");
			stringBuilder.AppendLine("\t\t0, 0, 0, 0, 0, 0, 0, ");
			stringBuilder.AppendLine("\t\t0, 0, Convert(Decimal(15,5), LTrim(SUBSTRING(@s1, 496, 20))), 0, 0, 0, 0, ");
			stringBuilder.AppendLine("\t\t''CONVERSION'',GETDATE(),''PartBinDetails'',Convert(Varchar(45), LTrim(SUBSTRING(@s1, 516, 45)))),");
			stringBuilder.AppendLine("\t\t(Convert(Int, LTrim(SUBSTRING(@s1, 1, 15))), 4, 4, Convert(Decimal(15,5), LTrim(SUBSTRING(@s1, 16, 20))), -- actual");
			stringBuilder.AppendLine("\t\tConvert(Decimal(15,5), LTrim(SUBSTRING(@s1, 36, 20))), Convert(Decimal(15,5), LTrim(SUBSTRING(@s1, 56, 20))), Convert(Decimal(15,5), LTrim(SUBSTRING(@s1, 76, 20))), Convert(Decimal(15,5), LTrim(SUBSTRING(@s1, 96, 20))), Convert(Decimal(15,5), LTrim(SUBSTRING(@s1, 116, 20))), Convert(Decimal(15,5), LTrim(SUBSTRING(@s1, 136, 20))), Convert(Decimal(15,5), LTrim(SUBSTRING(@s1, 156, 20))), ");
			stringBuilder.AppendLine("\t\tConvert(Decimal(15,5), LTrim(SUBSTRING(@s1, 176, 20))), Convert(Decimal(15,5), LTrim(SUBSTRING(@s1, 196, 20))), Convert(Decimal(15,5), LTrim(SUBSTRING(@s1, 216, 20))), Convert(Decimal(15,5), LTrim(SUBSTRING(@s1, 236, 20))), Convert(Decimal(15,5), LTrim(SUBSTRING(@s1, 256, 20))), Convert(Decimal(15,5), LTrim(SUBSTRING(@s1, 276, 20))), Convert(Decimal(15,5), LTrim(SUBSTRING(@s1, 296, 20))), ");
			stringBuilder.AppendLine("\t\tConvert(Decimal(15,5), LTrim(SUBSTRING(@s1, 316, 20))), Convert(Decimal(15,5), LTrim(SUBSTRING(@s1, 336, 20))), Convert(Decimal(15,5), LTrim(SUBSTRING(@s1, 356, 20))), Convert(Decimal(15,5), LTrim(SUBSTRING(@s1, 376, 20))), Convert(Decimal(15,5), LTrim(SUBSTRING(@s1, 396, 20))), Convert(Decimal(15,5), LTrim(SUBSTRING(@s1, 416, 20))), Convert(Decimal(15,5), LTrim(SUBSTRING(@s1, 436, 20))),");
			stringBuilder.AppendLine("\t\t''CONVERSION'',GETDATE(),''PartBinDetails'',Convert(Varchar(45), LTrim(SUBSTRING(@s1, 516, 45))));");
			stringBuilder.AppendLine("\tEND");
			stringBuilder.AppendLine("\tIF @costing_method = 2 -- Last");
			stringBuilder.AppendLine("\tBEGIN");
			stringBuilder.AppendLine("\t\tInsert Into PartTransactionCosts (intPartTransactionID,intPartTransactionCostID,intCostType,intQuantity,");
			stringBuilder.AppendLine("\t\t\tintUnitLaborCost,intUnitOverheadCost,intUnitMaterialCost,intUnitSubcontractCost,intUnitDutyCost,intUnitFreightCost,intUnitMiscCost,");
			stringBuilder.AppendLine("\t\t\tintPrevUnitLaborCost,intPrevUnitOverheadCost,intPrevUnitMaterialCost,intPrevUnitSubcontractCost,intPrevUnitDutyCost,intPrevUnitFreightCost,intPrevUnitMiscCost,");
			stringBuilder.AppendLine("\t\t\tintActualUnitLaborCost,intActualUnitOverheadCost,intActualUnitMaterialCost,intActualUnitSubcontractCost,intActualUnitDutyCost,intActualUnitFreightCost,intActualUnitMiscCost,");
			stringBuilder.AppendLine("\t\t\tintCreatedBy,intCreatedDate,intSourceTableName,intSourceTableUniqueID) ");
			stringBuilder.AppendLine("\t\tValues ");
			stringBuilder.AppendLine("\t\t(Convert(Decimal(15,5), LTrim(SUBSTRING(@s1, 1, 15))), 1, 1, Convert(Decimal(15,5), LTrim(SUBSTRING(@s1, 16, 20))), -- average");
			stringBuilder.AppendLine("\t\t0, 0, Convert(Decimal(15,5), LTrim(SUBSTRING(@s1, 456, 20))), 0, 0, 0, 0, ");
			stringBuilder.AppendLine("\t\t0, 0, 0, 0, 0, 0, 0, ");
			stringBuilder.AppendLine("\t\t0, 0, Convert(Decimal(15,5), LTrim(SUBSTRING(@s1, 456, 20))), 0, 0, 0, 0,");
			stringBuilder.AppendLine("\t\t''CONVERSION'',GETDATE(),''PartBinDetails'',Convert(Varchar(45), LTrim(SUBSTRING(@s1, 516, 45)))),");
			stringBuilder.AppendLine("\t\t(Convert(Decimal(15,5), LTrim(SUBSTRING(@s1, 1, 15))), 2, 2, Convert(Decimal(15,5), LTrim(SUBSTRING(@s1, 16, 20))),  -- last");
			stringBuilder.AppendLine("\t\tConvert(Decimal(15,5), LTrim(SUBSTRING(@s1, 36, 20))), Convert(Decimal(15,5), LTrim(SUBSTRING(@s1, 56, 20))), Convert(Decimal(15,5), LTrim(SUBSTRING(@s1, 76, 20))), Convert(Decimal(15,5), LTrim(SUBSTRING(@s1, 96, 20))), Convert(Decimal(15,5), LTrim(SUBSTRING(@s1, 116, 20))), Convert(Decimal(15,5), LTrim(SUBSTRING(@s1, 136, 20))), Convert(Decimal(15,5), LTrim(SUBSTRING(@s1, 156, 20))), ");
			stringBuilder.AppendLine("\t\tConvert(Decimal(15,5), LTrim(SUBSTRING(@s1, 176, 20))), Convert(Decimal(15,5), LTrim(SUBSTRING(@s1, 196, 20))), Convert(Decimal(15,5), LTrim(SUBSTRING(@s1, 216, 20))), Convert(Decimal(15,5), LTrim(SUBSTRING(@s1, 236, 20))), Convert(Decimal(15,5), LTrim(SUBSTRING(@s1, 256, 20))), Convert(Decimal(15,5), LTrim(SUBSTRING(@s1, 276, 20))), Convert(Decimal(15,5), LTrim(SUBSTRING(@s1, 296, 20))), ");
			stringBuilder.AppendLine("\t\tConvert(Decimal(15,5), LTrim(SUBSTRING(@s1, 316, 20))), Convert(Decimal(15,5), LTrim(SUBSTRING(@s1, 336, 20))), Convert(Decimal(15,5), LTrim(SUBSTRING(@s1, 356, 20))), Convert(Decimal(15,5), LTrim(SUBSTRING(@s1, 376, 20))), Convert(Decimal(15,5), LTrim(SUBSTRING(@s1, 396, 20))), Convert(Decimal(15,5), LTrim(SUBSTRING(@s1, 416, 20))), Convert(Decimal(15,5), LTrim(SUBSTRING(@s1, 436, 20))),");
			stringBuilder.AppendLine("\t\t''CONVERSION'',GETDATE(),''PartBinDetails'',Convert(Varchar(45), LTrim(SUBSTRING(@s1, 516, 45)))),");
			stringBuilder.AppendLine("\t\t(Convert(Decimal(15,5), LTrim(SUBSTRING(@s1, 1, 15))), 3, 3, Convert(Decimal(15,5), LTrim(SUBSTRING(@s1, 16, 20))), -- standard");
			stringBuilder.AppendLine("\t\t0, 0, Convert(Decimal(15,5), LTrim(SUBSTRING(@s1, 496, 20))), 0, 0, 0, 0, ");
			stringBuilder.AppendLine("\t\t0, 0, 0, 0, 0, 0, 0, ");
			stringBuilder.AppendLine("\t\t0, 0, Convert(Decimal(15,5), LTrim(SUBSTRING(@s1, 496, 20))), 0, 0, 0, 0, ");
			stringBuilder.AppendLine("\t\t''CONVERSION'',GETDATE(),''PartBinDetails'',Convert(Varchar(45), LTrim(SUBSTRING(@s1, 516, 45)))),");
			stringBuilder.AppendLine("\t\t(Convert(Int, LTrim(SUBSTRING(@s1, 1, 15))), 4, 4, Convert(Decimal(15,5), LTrim(SUBSTRING(@s1, 16, 20))), -- actual");
			stringBuilder.AppendLine("\t\tConvert(Decimal(15,5), LTrim(SUBSTRING(@s1, 36, 20))), Convert(Decimal(15,5), LTrim(SUBSTRING(@s1, 56, 20))), Convert(Decimal(15,5), LTrim(SUBSTRING(@s1, 76, 20))), Convert(Decimal(15,5), LTrim(SUBSTRING(@s1, 96, 20))), Convert(Decimal(15,5), LTrim(SUBSTRING(@s1, 116, 20))), Convert(Decimal(15,5), LTrim(SUBSTRING(@s1, 136, 20))), Convert(Decimal(15,5), LTrim(SUBSTRING(@s1, 156, 20))), ");
			stringBuilder.AppendLine("\t\tConvert(Decimal(15,5), LTrim(SUBSTRING(@s1, 176, 20))), Convert(Decimal(15,5), LTrim(SUBSTRING(@s1, 196, 20))), Convert(Decimal(15,5), LTrim(SUBSTRING(@s1, 216, 20))), Convert(Decimal(15,5), LTrim(SUBSTRING(@s1, 236, 20))), Convert(Decimal(15,5), LTrim(SUBSTRING(@s1, 256, 20))), Convert(Decimal(15,5), LTrim(SUBSTRING(@s1, 276, 20))), Convert(Decimal(15,5), LTrim(SUBSTRING(@s1, 296, 20))), ");
			stringBuilder.AppendLine("\t\tConvert(Decimal(15,5), LTrim(SUBSTRING(@s1, 316, 20))), Convert(Decimal(15,5), LTrim(SUBSTRING(@s1, 336, 20))), Convert(Decimal(15,5), LTrim(SUBSTRING(@s1, 356, 20))), Convert(Decimal(15,5), LTrim(SUBSTRING(@s1, 376, 20))), Convert(Decimal(15,5), LTrim(SUBSTRING(@s1, 396, 20))), Convert(Decimal(15,5), LTrim(SUBSTRING(@s1, 416, 20))), Convert(Decimal(15,5), LTrim(SUBSTRING(@s1, 436, 20))),");
			stringBuilder.AppendLine("\t\t''CONVERSION'',GETDATE(),''PartBinDetails'',Convert(Varchar(45), LTrim(SUBSTRING(@s1, 516, 45))));");
			stringBuilder.AppendLine("\tEND");
			stringBuilder.AppendLine("\tIF @costing_method = 3 -- Standard");
			stringBuilder.AppendLine("\tBEGIN");
			stringBuilder.AppendLine("\t\tInsert Into PartTransactionCosts (intPartTransactionID,intPartTransactionCostID,intCostType,intQuantity,");
			stringBuilder.AppendLine("\t\t\tintUnitLaborCost,intUnitOverheadCost,intUnitMaterialCost,intUnitSubcontractCost,intUnitDutyCost,intUnitFreightCost,intUnitMiscCost,");
			stringBuilder.AppendLine("\t\t\tintPrevUnitLaborCost,intPrevUnitOverheadCost,intPrevUnitMaterialCost,intPrevUnitSubcontractCost,intPrevUnitDutyCost,intPrevUnitFreightCost,intPrevUnitMiscCost,");
			stringBuilder.AppendLine("\t\t\tintActualUnitLaborCost,intActualUnitOverheadCost,intActualUnitMaterialCost,intActualUnitSubcontractCost,intActualUnitDutyCost,intActualUnitFreightCost,intActualUnitMiscCost,");
			stringBuilder.AppendLine("\t\t\tintCreatedBy,intCreatedDate,intSourceTableName,intSourceTableUniqueID) ");
			stringBuilder.AppendLine("\t\tValues ");
			stringBuilder.AppendLine("\t\t(Convert(Decimal(15,5), LTrim(SUBSTRING(@s1, 1, 15))), 1, 1, Convert(Decimal(15,5), LTrim(SUBSTRING(@s1, 16, 20))), -- average");
			stringBuilder.AppendLine("\t\t0, 0, Convert(Decimal(15,5), LTrim(SUBSTRING(@s1, 456, 20))), 0, 0, 0, 0, ");
			stringBuilder.AppendLine("\t\t0, 0, 0, 0, 0, 0, 0, ");
			stringBuilder.AppendLine("\t\t0, 0, Convert(Decimal(15,5), LTrim(SUBSTRING(@s1, 456, 20))), 0, 0, 0, 0,");
			stringBuilder.AppendLine("\t\t''CONVERSION'',GETDATE(),''PartBinDetails'',Convert(Varchar(45), LTrim(SUBSTRING(@s1, 516, 45)))),");
			stringBuilder.AppendLine("\t\t(Convert(Decimal(15,5), LTrim(SUBSTRING(@s1, 1, 15))), 2, 2, Convert(Decimal(15,5), LTrim(SUBSTRING(@s1, 16, 20))),  -- last");
			stringBuilder.AppendLine("\t\t0, 0, Convert(Decimal(15,5), LTrim(SUBSTRING(@s1, 476, 20))), 0, 0, 0, 0, ");
			stringBuilder.AppendLine("\t\t0, 0, 0, 0, 0, 0, 0, ");
			stringBuilder.AppendLine("\t\t0, 0, Convert(Decimal(15,5), LTrim(SUBSTRING(@s1, 476, 20))), 0, 0, 0, 0,");
			stringBuilder.AppendLine("\t\t''CONVERSION'',GETDATE(),''PartBinDetails'',Convert(Varchar(45), LTrim(SUBSTRING(@s1, 516, 45)))),");
			stringBuilder.AppendLine("\t\t(Convert(Decimal(15,5), LTrim(SUBSTRING(@s1, 1, 15))), 3, 3, Convert(Decimal(15,5), LTrim(SUBSTRING(@s1, 16, 20))), -- standard");
			stringBuilder.AppendLine("\t\tConvert(Decimal(15,5), LTrim(SUBSTRING(@s1, 36, 20))), Convert(Decimal(15,5), LTrim(SUBSTRING(@s1, 56, 20))), Convert(Decimal(15,5), LTrim(SUBSTRING(@s1, 76, 20))), Convert(Decimal(15,5), LTrim(SUBSTRING(@s1, 96, 20))), Convert(Decimal(15,5), LTrim(SUBSTRING(@s1, 116, 20))), Convert(Decimal(15,5), LTrim(SUBSTRING(@s1, 136, 20))), Convert(Decimal(15,5), LTrim(SUBSTRING(@s1, 156, 20))), ");
			stringBuilder.AppendLine("\t\tConvert(Decimal(15,5), LTrim(SUBSTRING(@s1, 176, 20))), Convert(Decimal(15,5), LTrim(SUBSTRING(@s1, 196, 20))), Convert(Decimal(15,5), LTrim(SUBSTRING(@s1, 216, 20))), Convert(Decimal(15,5), LTrim(SUBSTRING(@s1, 236, 20))), Convert(Decimal(15,5), LTrim(SUBSTRING(@s1, 256, 20))), Convert(Decimal(15,5), LTrim(SUBSTRING(@s1, 276, 20))), Convert(Decimal(15,5), LTrim(SUBSTRING(@s1, 296, 20))), ");
			stringBuilder.AppendLine("\t\tConvert(Decimal(15,5), LTrim(SUBSTRING(@s1, 316, 20))), Convert(Decimal(15,5), LTrim(SUBSTRING(@s1, 336, 20))), Convert(Decimal(15,5), LTrim(SUBSTRING(@s1, 356, 20))), Convert(Decimal(15,5), LTrim(SUBSTRING(@s1, 376, 20))), Convert(Decimal(15,5), LTrim(SUBSTRING(@s1, 396, 20))), Convert(Decimal(15,5), LTrim(SUBSTRING(@s1, 416, 20))), Convert(Decimal(15,5), LTrim(SUBSTRING(@s1, 436, 20))),");
			stringBuilder.AppendLine("\t\t''CONVERSION'',GETDATE(),''PartBinDetails'',Convert(Varchar(45), LTrim(SUBSTRING(@s1, 516, 45)))),");
			stringBuilder.AppendLine("\t\t(Convert(Int, LTrim(SUBSTRING(@s1, 1, 15))), 4, 4, Convert(Decimal(15,5), LTrim(SUBSTRING(@s1, 16, 20))), -- actual");
			stringBuilder.AppendLine("\t\tConvert(Decimal(15,5), LTrim(SUBSTRING(@s1, 36, 20))), Convert(Decimal(15,5), LTrim(SUBSTRING(@s1, 56, 20))), Convert(Decimal(15,5), LTrim(SUBSTRING(@s1, 76, 20))), Convert(Decimal(15,5), LTrim(SUBSTRING(@s1, 96, 20))), Convert(Decimal(15,5), LTrim(SUBSTRING(@s1, 116, 20))), Convert(Decimal(15,5), LTrim(SUBSTRING(@s1, 136, 20))), Convert(Decimal(15,5), LTrim(SUBSTRING(@s1, 156, 20))), ");
			stringBuilder.AppendLine("\t\tConvert(Decimal(15,5), LTrim(SUBSTRING(@s1, 176, 20))), Convert(Decimal(15,5), LTrim(SUBSTRING(@s1, 196, 20))), Convert(Decimal(15,5), LTrim(SUBSTRING(@s1, 216, 20))), Convert(Decimal(15,5), LTrim(SUBSTRING(@s1, 236, 20))), Convert(Decimal(15,5), LTrim(SUBSTRING(@s1, 256, 20))), Convert(Decimal(15,5), LTrim(SUBSTRING(@s1, 276, 20))), Convert(Decimal(15,5), LTrim(SUBSTRING(@s1, 296, 20))), ");
			stringBuilder.AppendLine("\t\tConvert(Decimal(15,5), LTrim(SUBSTRING(@s1, 316, 20))), Convert(Decimal(15,5), LTrim(SUBSTRING(@s1, 336, 20))), Convert(Decimal(15,5), LTrim(SUBSTRING(@s1, 356, 20))), Convert(Decimal(15,5), LTrim(SUBSTRING(@s1, 376, 20))), Convert(Decimal(15,5), LTrim(SUBSTRING(@s1, 396, 20))), Convert(Decimal(15,5), LTrim(SUBSTRING(@s1, 416, 20))), Convert(Decimal(15,5), LTrim(SUBSTRING(@s1, 436, 20))),");
			stringBuilder.AppendLine("\t\t''CONVERSION'',GETDATE(),''PartBinDetails'',Convert(Varchar(45), LTrim(SUBSTRING(@s1, 516, 45))));");
			stringBuilder.AppendLine("\tEND");
			stringBuilder.AppendLine("\tIf @rec_count = 20000");
			stringBuilder.AppendLine("\tBegin");
			stringBuilder.AppendLine("\t\tCommit Transaction");
			stringBuilder.AppendLine("\t\tset @rec_count = 0;");
			stringBuilder.AppendLine("\t\tBegin Transaction");
			stringBuilder.AppendLine("\tEnd\t");
			stringBuilder.AppendLine("\t");
			stringBuilder.AppendLine("\tFETCH NEXT FROM TRANS_CURSOR");
			stringBuilder.AppendLine("\tINTO @s1");
			stringBuilder.AppendLine("END");
			stringBuilder.AppendLine("CLOSE TRANS_CURSOR");
			stringBuilder.AppendLine("DEALLOCATE TRANS_CURSOR");
			stringBuilder.AppendLine("If @@TRANCOUNT > 0");
			stringBuilder.AppendLine("Begin");
			stringBuilder.AppendLine("\tCommit Transaction;");
			stringBuilder.AppendLine("End ");
			stringBuilder.AppendLine("SET NOCOUNT OFF");
			stringBuilder.AppendLine("'");
			stringBuilder.AppendLine("exec(@sql) ");
			stringBuilder.AppendLine("SET NOCOUNT OFF");
			stringBuilder.AppendLine("end");
			parms.ServerManager.ExecuteCommand(null, parms.User, parms.DatabaseName, stringBuilder.ToString());
		}
	}
}
